### ISSUE TITLE
Initialization taking longer than 30 minutes

### ISSUE THREAD

**Issue by leegenes** [vdesabou/alfred-spotify-mini-player#103]
Getting an error [and it's been stuck this way] that initialization is taking longer than 30 minutes.

![](https://monosnap.com/file/Y15La7Vr5G1O3fSEKQTuTUKWCPRHDN.png)

I have a .tgz file ready. I don't use osx Mail app though. I'm unable to email through the workflow. Let me know what I should do to get that to you.

The short story until: only settings.json is in the com.vdesabou.spotify.mini.player directory. Maybe that doesn't matter, but that's what showing up in debug.log

Thanks for your help.

**Comment by vdesabou** [comment]
Hi,

Send me the TGZ by email(without using the workflow) or by using any service you like(Dropbox, droplr, etc..). The email is in the link I have to you before.
Thanks

Vincent

**Comment by vdesabou** [comment]
Can you provide the TGZ file, that's the only way for me to help...

**Comment by vdesabou** [comment]
Any feedback?

**Comment by vdesabou** [comment]
Closing. Re-open if you want some help..

**Comment by leegenes** [comment]
Sorry for the delay. Just got back to this.
Went to generate a new .tgz for you. The problem seems to have magically resolved itself.
Thanks for your help.
Not re-opening.
