### ISSUE TITLE
No 'error' provided in response body happening almost every time for one user

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#104]
Example:

<img width="535" alt="screen shot on 2015-11-05 at 19_50_31" src="https://cloud.githubusercontent.com/assets/4061923/11031646/426ac2ce-86d6-11e5-84c1-e7b2059e170e.png">

**Comment by roccitman** [comment]
Some background:
I am in the US, but I live in Hawaii (specifically Kauai) so maybe that has something to do with it?
Also about a month ago I was having trouble reaching Spotify's website via browser. I could reach the player just fine, but not the normal website, or their support pages. I would either get a cannot connect to server message (this: http://d.pr/n/1iXIw) or I would get a different language version of the site, something like Malaysian.
(not sure if that helps.)

**Comment by vdesabou** [comment]
Can you install this Beta version https://infinit.io/_/cZadweR and let me know if this is better?
It includes a fix made for this problem https://github.com/jwilsson/spotify-web-api-php/issues/32

**Comment by roccitman** [comment]
Yea! Seems to work great: http://d.pr/v/18ZnV <http://d.pr/v/18ZnV>

**Comment by roccitman** [comment]
Some more odd errors. Might be a different thing. This is low priority, it's still working, just complaining about something
Debug tar: http://d.pr/f/sMNz
Screenshot: http://d.pr/i/LO88
Screenshot: http://d.pr/i/1dIaH

**Comment by roccitman** [comment]
Another API error: http://d.pr/i/13qQV

**Comment by vdesabou** [comment]
>Another API error: http://d.pr/i/13qQV

It looks like an temp error, is it reproducible on your side?

**Comment by vdesabou** [comment]
I fixed the two mentioned exceptions, here is a beta link: https://infinit.io/_/mRMCGBZ

**Comment by roccitman** [comment]
Loading beta now. The API problem seems to go back and forth. Works now: http://d.pr/i/1lnH2

**Comment by vdesabou** [comment]
ok thanks for the feedback!
Would you mind help me test this beta https://infinit.io/_/35S4HVp

I've tried to simplify the `spot_mini_debug` process by automatically generating an email with information and a link to uploaded TGZ file (where sensible data has been removed).

So if you can install the Beta and then call `spot_mini_debug`and then select `Send an email ..`, and then send me the generated email

**Comment by roccitman** [comment]
Email sent. Nice addition.

No sooner than I told you the API was working I started getting this again: http://d.pr/i/Enze. I guess their API service is spotty (no pun intended).

**Comment by vdesabou** [comment]
Thanks for trying the spot_mini_debug command, it worked well!

Can you try to launch multiple times this command in a terminal window and
paste the output:

curl -v https://api.spotify.com



I’ve tried a workaround described here
http://stackoverflow.com/questions/28366402/failed-to-connect-to-www-googleapis-com-port-443-network-unreachable

Can you install this beta version and let me know if you still get this
intermittent issue? https://infinit.io/_/9CTbC4w



On Thu, Nov 12, 2015 at 5:11 PM, roccitman <notifications@github.com> wrote:

> Email sent. Nice addition.
>
> No sooner than I told you the API was working I started getting this
> again: http://d.pr/i/Enze. I guess their API service is spotty (no pun
> intended).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vdesabou/alfred-spotify-mini-player/issues/104#issuecomment-156151291>
> .
>



-- 
Vincent de Saboulin

**Comment by roccitman** [comment]
I'll do this when I get home, but I think therein might lie the problem. I think these issues might be caused by my modem/router. I cannot replicate any of the errors while on a different wi-fi connection.
More soon.

**Comment by roccitman** [comment]
Finally home. Here's a few pastes for you:
http://d.pr/n/1hVa2
http://d.pr/n/iuL1
http://d.pr/n/11HOo
http://d.pr/n/1gm9B

**Comment by vdesabou** [comment]
ok thanks. Let's follow up on new issue https://github.com/vdesabou/alfred-spotify-mini-player/issues/106 because this particular issue is fixed now and version 6.2.4 is out.
Thanks
