### ISSUE TITLE
Growl notifications

### ISSUE THREAD

**Issue by rapcal** [vdesabou/alfred-spotify-mini-player#107]
Great workflow! Thanks :+1: 

This is just a suggestion for an enhancement. Since Alfred v2 offers the option between OSX Notification Center and Growl, maybe you could offer that too.

Here's a sample AppleScript from Growl's website that could somehow be attached to the the workflow.

Thanks again!

```AppleScript
tell application "System Events"
	set isRunning to (count of (every process whose bundle identifier is "com.Growl.GrowlHelperApp")) > 0
end tell

if isRunning then
	tell application id "com.Growl.GrowlHelperApp"
		-- Make a list of all the notification types 
		-- that this script will ever send:
		set the allNotificationsList to ¬
			{"Test Notification", "Another Test Notification"}
		
		-- Make a list of the notifications 
		-- that will be enabled by default.      
		-- Those not enabled by default can be enabled later 
		-- in the 'Applications' tab of the growl prefpane.
		set the enabledNotificationsList to ¬
			{"Test Notification"}
		
		-- Register our script with growl.
		-- You can optionally (as here) set a default icon 
		-- for this script's notifications.
		register as application ¬
			"Growl AppleScript Sample" all notifications allNotificationsList ¬
			default notifications enabledNotificationsList ¬
			icon of application "Script Editor"
		
		--       Send a Notification...
		notify with name ¬
			"Test Notification" title ¬
			"Test Notification" description ¬
			"This is a test AppleScript notification." application name "Growl AppleScript Sample"
		
		notify with name ¬
			"Another Test Notification" title ¬
			"Another Test Notification :) " description ¬
			"Alas — you won't see me until you enable me..." application name "Growl AppleScript Sample"
		
	end tell
end if

**Comment by vdesabou** [comment]
Hi,

I've just added support for [Growl](http://growl.info), can you please Beta test it?
Please install this Beta release https://infinit.io/_/QFUS8tD and let me know if it works fine.

Growl can be activated in settings.

**Comment by rapcal** [comment]
Thanks, @vdesabou ! :smile:

Will test and report back!

**Comment by rapcal** [comment]
Played a lot of tunes, playlists, performed searches and I can state this is working amazingly well. Thanks a lot! :loud_sound:

**Comment by vdesabou** [comment]
ok cool!
Let's keep it open until I get 6.2.5 officially released

**Comment by rapcal** [comment]
Absolutely, @vdesabou. Sorry for that.

**Comment by jiaweihli** [comment]
Hi, this doesn't seem to respect Alfred's option for showing notifications on the current screen - it instead shows on the default screen. Any ideas?

**Comment by vdesabou** [comment]
@jiaweihli Are you talking about Growl or OS X notifications ?

I'm currently using Alfred 3 as Beta and it seems the Growl option in advanced prefs is no longer there
