### ISSUE TITLE
Start song radio

### ISSUE THREAD

**Issue by trzeciakp** [vdesabou/alfred-spotify-mini-player#108]
Hi, 

there is an option to create playlist based on current track radio, but why I can't start song radio without playlist creation? Is it possible to add it as a  feature?

Btw. I'm new alfred user and your workflow is my favourite! Great job!

**Comment by vdesabou** [comment]
Hi,

It is not technically feasible with Spotify APIs..I need to create a playlist in any case. However I have added an auto play option to start the playlist after it has been created, you can try that maybe.

Vincent

**Comment by vdesabou** [comment]
Closing as autoplay was added with https://github.com/vdesabou/alfred-spotify-mini-player/issues/99
