### ISSUE TITLE
Trigger OS X notifications without changing the current music

### ISSUE THREAD

**Issue by roccitman** [vdesabou/alfred-spotify-mini-player#109]
Hey there

Is there a way to trigger the now_playing notifications to start without having to initiate a playlist? I often reboot and the Spotify client will come up with the same song(s) queued. I just hit the play button but the now_playing notifications won't start until I start a new album/playlist/etc.

**Comment by vdesabou** [comment]
I get your point, will think about it.

Vincent

**Comment by roccitman** [comment]
Have a great day!

**Comment by vdesabou** [comment]
Hi,

I've implemented it, if you want to test, here is a beta link https://infinit.io/_/PyuTef7

Thanks

**Comment by roccitman** [comment]
Works as expected! Anything triggers it now. Thanks!

**Comment by vdesabou** [comment]
Thanks for the feedback.
Leaving it opened until 6.2.5 is out

**Comment by roccitman** [comment]
Fair enough. 
(I kinda pushed that button by accident)
