### ISSUE TITLE
add track to my music

### ISSUE THREAD

**Issue by pexxi2** [vdesabou/alfred-spotify-mini-player#110]
Hi,
in using "add track to my playlist" the title is "copied" in myMusic but not marked as checked there is still a cross.

cheers

**Comment by vdesabou** [comment]
Hi,

If you add a track to a playlist, it is not added to Your Music automatically, you need to specifically add it to Your Music. This is same behavior as in Spotify Desktop if I remember correctly.

Can you please provide example and more explanations?

Thanks

**Comment by pexxi2** [comment]
yes you remember correctly.
I have specified that it should add to mymusic. And it does but the icon in the desktop does not switch. If you add a title over the desktop one can click on the "+" sign and it changes into a "V"(checked) and the titel is in the list "mymusic".
If I use the "add track to my playlist" function the titel appears in the my music collection but is not checked with a "V" (checked) there is stll a "+". 
cheers

**Comment by vdesabou** [comment]
Ok, I don't see this behavior, see screencast here http://d.pr/i/1fsdf

But in any case, if the track is correctly added by the workflow, I would say it is a desktop issue, and nothing I can do about that, right?

**Comment by pexxi2** [comment]
Thank you...yes in any case the track is added. And suddenly my expected behavior shows up...as I restarted the spotify app...so everything in finde order now...thank you for your fantastic work I really like the workflow and use it a lot. Thank you for your time.
cheers

**Comment by vdesabou** [comment]
ok cool!
