### ISSUE TITLE
localhost site not starting

### ISSUE THREAD

**Issue by martin-sweeney** [vdesabou/alfred-spotify-mini-player#114]
Hi,
Forgive me - newbie osx user - if this is something simple
Running this on el capitan I get no website showing up on localhost:15298/callback.php

firewall is off...

**Comment by vdesabou** [comment]
Hi,

Can you follow steps described [here](http://alfred-spotify-mini-player.com/articles/support/), I'll have a look when I receive your email

**Comment by martin-sweeney** [comment]
ok - I have done that -  Hopefully an email was sent... 
I dont think the email is sending though - is there a way to get the debug information manually?

**Comment by vdesabou** [comment]
When you click on the "send an email", it should open your default email client with the needed text.

Don't you have a default email client configured?

**Comment by vdesabou** [comment]
Can you install this version of workflow https://infinit.io/_/bqS7pS7

You should get the needed information in the clipboard when you click on the "send an email" button 
Then copy/paste it in an email send to alfred.spotify.mini.player AT gmail.com

**Comment by martin-sweeney** [comment]
ok thanks.. I will give that a go

**Comment by martin-sweeney** [comment]
I'm sorry that doesnt seem to copy anything to the clipboard - I reset the settings and retried the authorisation on the new version you linked to. Same error with nothing running on localhost:15298 

I found the location of the scripts though - can I run them manually and show you the output?

I also do not see a debug.tgz file being generated at all....

I noticed that OSX was blocking the app cause it wasnt trusted - but even after that I dont see the app actually doing anything when I run the Authorise command apart from open the website that is not present.

**Comment by vdesabou** [comment]
Any chance you can do a screen cast to see what is going on, as I don't see why you cannot generate the debug.tgz file

Vincent

**Comment by vdesabou** [comment]
Ok I see why you could not use ```spot_mini_debug``` command successfully. Can you please install this beta version https://infinit.io/_/suTB4Xp and then invoke  ```spot_mini_debug``` again, you should have the email created (or at least a text in the clipboard).

**Comment by martin-sweeney** [comment]
Ok thanks - I will try that...

**Comment by martin-sweeney** [comment]
sent you an email with two separate attempts in it...

**Comment by vdesabou** [comment]
Thanks. 
So the problem is this error:

```
Unknown: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided
```

Can you execute this command in a terminal and copy/paste results here:

```
php -S localhost:15298
```

On my side, I get:

```
$ php -S localhost:15298
PHP 5.5.30 Development Server started at Wed Mar 16 13:04:35 2016
Listening on http://localhost:15298
Document root is /Users/vdesabou
Press Ctrl-C to quit.
```

**Comment by martin-sweeney** [comment]
<br />
<b>Warning</b>:  Unknown: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in <b>Unknown</b> on line <b>0</b><br />
[Wed Mar 16 12:32:14 2016] Failed to listen on localhost:15298 (reason: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known)

**Comment by vdesabou** [comment]
Are you using El Capitan? Did you change anything to PHP.ini or recompile by yourself PHP?

There are some discussions about this error [here](http://stackoverflow.com/questions/2223620/php5-fails-to-resolve-hostnames-when-not-in-interactive-mode)

They suggest either to change PHP.ini, recompile without IPv6

Can you try this command:

```
php -S 127.0.0.1:15298
```

Also can you copy/paste this:

```
cat /etc/hosts
```

Thanks

**Comment by martin-sweeney** [comment]
I didnt change the PHP.ini file... but some apps might of during installation.

My hosts file is very specific - it has alot of work ip's etc... 

Ok - so `php -S 127.0.0.1:15298`  works fine
and 
`php -S localhost:15298`  doesnt work at all

**Comment by martin-sweeney** [comment]
ok - solved it - the hosts file has a setting in it for work to redirect 127.0.0.1 to a locally developed website...

**Comment by vdesabou** [comment]
Ok, can you try with this new BETA then https://infinit.io/_/4GCEVwB

If « php -S 127.0.0.1:15298 » works for you, then authentication should
work now with this BETA

On Wed, Mar 16, 2016 at 2:40 PM, martin-sweeney <notifications@github.com>
wrote:

> I didnt change the PHP.ini file... but some apps might of during
> installation.
>
> My hosts file is very specific - it has alot of work ip's etc...
>
> Ok - so php -S 127.0.0.1:15298 works fine
> and
> php -S localhost:15298 doesnt work at all
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/vdesabou/alfred-spotify-mini-player/issues/114#issuecomment-197335103>
>



-- 
Vincent de Saboulin

**Comment by martin-sweeney** [comment]
with the BETA - `Hello ! You are now successfully logged and you can close this window.`

**Comment by vdesabou** [comment]
ok good. But if that's something in your /etc/hosts, I'm not going to release the change in latest BETA to other people.
So you can stay like this, and if you need to do authentication again in the future, change your /etc/hosts for a short time.

Cheers!

**Comment by martin-sweeney** [comment]
Sure - sounds like a plan - its possible that you could consider using 127.0.0.1 instead of localhost though? 

Just a thought

**Comment by vdesabou** [comment]
> its possible that you could consider using 127.0.0.1 instead of localhost though?

Good point, that's what I did in 3a2ac8e
