### ISSUE TITLE
Now playing pops up even when disabled.

### ISSUE THREAD

**Issue by lsc** [vdesabou/alfred-spotify-mini-player#115]
I have the now playing notification disabled, see image below.

<img width="542" alt="screenshot 2016-03-15 13 48 32" src="https://cloud.githubusercontent.com/assets/2591/13778213/cab311f8-eab4-11e5-9989-796d0ae5422f.png">

But when I start playing I still get a popup about now playing, this is true when issuing the next track command. 
 
<img width="360" alt="screenshot 2016-03-15 13 49 17" src="https://cloud.githubusercontent.com/assets/2591/13778214/cab59dc4-eab4-11e5-95c2-fbe653b4f42c.png">

**Comment by vdesabou** [comment]
Hi,

You're right, it does not make really sense. Can you please test this BETA release https://infinit.io/_/hKZSzpW 

Thanks

**Comment by lsc** [comment]
I will test it out right away. Thank you!
