### ISSUE TITLE
Missing required parameter in Spotify authentication step

### ISSUE THREAD

**Issue by kschillz** [vdesabou/alfred-spotify-mini-player#117]
I'm not sure why, but today I had to enter my Client ID/Secret again. After doing so and selecting `Authenticate to Spotify`, my browser opened

`https://accounts.spotify.com/authorize/?client_id=<client_id>&response_type=code&scope=user-library-read+user-read-email+user-read-private+user-library-modify+user-follow-modify+user-follow-read+playlist-read-private+playlist-modify-public+playlist-modify-private+playlist-read-collaborative&show_dialog=true`

which responded with 'Missing required parameter'.

**Comment by vdesabou** [comment]
I suspect a corrupted settings.json file. Can you do execute in Alfred command `spot_mini_reset_settings` and then execute again the workflow to do authentication process again?

If this is still not working, please send TGZ file by using `spot_mini_debug` command

**Comment by kschillz** [comment]
Resetting settings worked. Thanks!
