### ISSUE TITLE
how can I swap around modifier key behaviours?

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#119]
There is a choice to press certain modifier keys to produce some action like add to playlist, play current artist and few more. However I more often than not add songs to my playlists from that menu so I would much rather move 'add to playlist' from fn key to cmd key and then move my 'play current artist to fn key for example or even better move it to opt key and move what is on opt key before 'play album' to fn key. This would be absolutely perfect.

Here is an image of what I mean :

![2016-04-25 at 11 57](https://cloud.githubusercontent.com/assets/6391776/14780373/f0ba7f38-0adc-11e6-80b6-00c5bd7faf0f.png)

I understand that I can just change these values there and that works

![2016-04-25 at 12 01](https://cloud.githubusercontent.com/assets/6391776/14780504/6e8c8b0e-0add-11e6-8c2f-5ba721caf8da.png)

However I still get the text of what was set by default. Can you please help me edit these text values appropriately so if I were to change them, the text descriptions would also represent the behaviour I have set them out to do.

Thank you.

**Comment by vdesabou** [comment]
Hi,

For this particular example, you'll need to edit menu.php file, on line 2957

```
		$subtitle             = "⌥ (play album) ⌘ (play artist) ctrl (lookup online)";
```

There is an issue opened to enhance the workflow to have modifiers keys configurable (https://github.com/vdesabou/alfred-spotify-mini-player/issues/102) but I have not much time to work on it right now unfortunately..

**Comment by nikitavoloboev** [comment]
Thank you. That worked perfectly.

**Comment by nikitavoloboev** [comment]
This seemed to make the workflow stop the authentication between spotify and the workflow.

When I went on to write my client ID and client secret, after it gives me the option to authenticate I get this safari tab that opens and says 'Missing required parameter: redirect_uri'. However I do not see anywhere where I should type this. 

Should I delete the web app from Spotify all together now and start the process again? 

![2016-04-25 at 22 32](https://cloud.githubusercontent.com/assets/6391776/14798006/b2787cee-0b35-11e6-8366-3e6cd9fb357c.png)

Thank you for your help.

**Comment by vdesabou** [comment]
Please follow steps here http://alfred-spotify-mini-player.com/articles/support/ for me to help

Vincent
