### ISSUE TITLE
it never ends updating

### ISSUE THREAD

**Issue by Xusqui** [vdesabou/alfred-spotify-mini-player#12]
Hello.

I have tried several times to update my library (8000 songs from 3000 artists in about 30 playlists) but it never ends. Sometimes it hangs retrieving songs, some retrieving playlists and some other retrieving the artists. But it has never been able to completely update the library.

Any tips?

Thanks in advance

**Comment by Xusqui** [comment]
Sorry... I don't use the workflow anymore... Actually I never managed to use it 100%...

**Comment by vdesabou** [comment]
You should try again it's very stable now..
Thanks for feedback anyway

**Comment by Xusqui** [comment]
Ok... I will...
