### ISSUE TITLE
Lyrics not found

### ISSUE THREAD

**Issue by Athosone** [vdesabou/alfred-spotify-mini-player#120]
I can't have alfred-spotify-mini-player to find me lyrics:

[ERROR: alfred.workflow.input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 64.)'. Row (null), Col (null): 'XML declaration allowed only at the start of the document' in XML:
<?xml version="1.0" encoding="UTF-8"?>
<items><item arg="" valid="no"><arg></arg><title>No update available</title><subtitle>You are good to go!</subtitle><icon>./images/info.png</icon><text></text></item></items>
<?xml version="1.0" encoding="UTF-8"?>
<items><item arg="" valid="no"><arg></arg><title>No update available</title><subtitle>You are good to go!</subtitle><icon>./images/info.png</icon><text></text></item></items>
[INFO: alfred.workflow.trigger.external] Processing output 'alfred.workflow.action.script' with arg 'spotify:track:17baAghWcrewNOcc9dCewx'

**Comment by vdesabou** [comment]
Thanks for reporting this. Can you try this beta release, it should fix broken lyrics.

https://infinit.io/_/7hY5PXh

**Comment by Athosone** [comment]
nice its working :) 👍  thanks !
