### ISSUE TITLE
I updated Alfred to version 3 and now I cannot get the workflow to work 

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#121]
I get the following screen : 

![2016-05-10 at 19 08](https://cloud.githubusercontent.com/assets/6391776/15155409/a4238a68-16e2-11e6-9adc-c11b048f2470.png)

But inserting the token, does not do anything, it seems that pressing return does not work nor is pressing these buttons. Will it be possible to update the workflow to the version 3 as I really love it.

**Comment by vdesabou** [comment]
Hello,

Can you please try this beta release for Alfred v3? You can download it [here](https://infinit.io/_/6EVXPKY)

**Comment by nikitavoloboev** [comment]
That worked perfectly. Thank you. :)
