### ISSUE TITLE
Toggle repeat on / off from the workflow.

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#122]
Could such a thing be done, perhaps it exists already but I couldn't find a way to either toggle on / off the repeat nor the shuffle from the alfred workflow prompt itself.

**Comment by vdesabou** [comment]
Hi,

Shuffling is already there, see the list of commands here http://alfred-spotify-mini-player.com/articles/keyword-inputs/

Repeating can be done. I could add it in some future release

**Comment by vdesabou** [comment]
This is the applescript for activating repeating

![screen shot 2016-05-11 a 13 06 28](https://cloud.githubusercontent.com/assets/4061923/15178970/34935eac-1779-11e6-9329-aa54da87e1b1.jpg)

**Comment by nikitavoloboev** [comment]
Hey @vdesabou 

Is it possible to turn on repeating of currently playing song?

This option:
![2018-05-31 at 16 54](https://user-images.githubusercontent.com/6391776/40789670-431ed540-64f3-11e8-884e-63bfa0018cbb.png)

There is `Repeating` action in workflow but it only toggles repeat on/off, not for a single song.

**Comment by vdesabou** [comment]
Hi @nikitavoloboev ,

I've added this possibility in beta https://transfer.sh/WWkfm/spotifyminiplayer-beta.alfredworkflow

there is a new command **repeating_current_track**

![screenshot 2018-06-07 at 13 16 51](https://user-images.githubusercontent.com/4061923/41096505-162b06a0-6a55-11e8-82da-e09d76ef7dff.jpg)

It is also possible to use modifier key COMMAND to use it 

NOTE: it is only possible to use when using Spotify Connect. Mopidy or AppleScript APIs do not provide this possibility
