### ISSUE TITLE
Cannot create the library with alfred 3

### ISSUE THREAD

**Issue by nsolcampbell** [vdesabou/alfred-spotify-mini-player#123]
Hi I just used spotify_mini_player with alfred3 and cannot create library. I got "spot_mini_debug Web API Exception: No internet connection ". Actually I'm in China and using VPN to connect Spotify. Is that the reason I can't use the alfred-spotify-mini-player?

**Comment by vdesabou** [comment]
Hi,

To check internet connectivity, I ping google.com, so maybe it is blocked by your VPN. 
Can you try this BETA release instead, I ping api.spotify.com instead. Beta download (Alfred V3 only): https://infinit.io/_/9aX3q2T

**Comment by nsolcampbell** [comment]
It works. Thank you very much!

**Comment by lenybernard** [comment]
Hello,

I have also an issue when I try to create the library with alfred 3.
Here is the stack trace:

```
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Generated: 2017-07-05 16:19:40
* display_name: Leny Bernard

* oauth_client_secret: ************some***secret***client***token***************************

* oauth_access_token:  ************some***secret***access***token***************************

* oauth_refresh_token: ************some***secret***refresh***token***************************

****
The file /Users/lenybernard/Library/Application Support/Alfred 3/Workflow Data/com.vdesabou.spotify.mini.player/library.db is not present
The file /Users/lenybernard/Library/Application Support/Alfred 3/Workflow Data/com.vdesabou.spotify.mini.player/library_new.db is not present
The file /Users/lenybernard/Library/Application Support/Alfred 3/Workflow Data/com.vdesabou.spotify.mini.player/library_old.db is not present
The file /Users/lenybernard/Library/Application Support/Alfred 3/Workflow Data/com.vdesabou.spotify.mini.player/history.json is not present
The directory /Users/lenybernard/Library/Application Support/Alfred 3/Workflow Data/com.vdesabou.spotify.mini.player/users is not present
Darwin MacBook-Air-de-Leny.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
10.12.5
hw.memsize: 8589934592
alfred_version:3.3.2
alfred_version_build:818
alfred_workflow_version:7.1
alfred_debug:
Spotify desktop version:1.0.57.474.gca9c9538
xattr Spotify Mini Player.app returned: com.apple.quarantine
****
```

Thank you for your time 💙

**Comment by vdesabou** [comment]
@lenybernard Can you please follow these steps http://alfred-spotify-mini-player.com/articles/support/ to generate the ZIP and send it to me. The output you're showing is not the stack trace, it's just some information on your setup. I will be able to help when I get the ZIP file

**Comment by lenybernard** [comment]
That's what I did but it doesn't generate any zip to me.
The only thing I've changed is the secret keys that I won't put in a github issue so I sent you an email with the infos.

**Comment by lenybernard** [comment]
Ok, I figured out ! That was my litle snitch (firewall)... What should be open ?

**Comment by vdesabou** [comment]
The workflow connects to:

- https://api.spotify.com (for interaction with Spotify)
- https://raw.githubusercontent.com (for downloading new release from Packal)
- https://github.com/ (for downloading images when changing theme)
- http://api.stathat.com (for statistics)
- https://transfer.sh (for DEBUG Zip file)
