### ISSUE TITLE
nothing happens after typing client id

### ISSUE THREAD

**Issue by shigg1120** [vdesabou/alfred-spotify-mini-player#126]
I registered my app on Spotify, opened Alfred,pasted my client id hit enter,and nothing happened.I am using Alfred 3.

<img width="581" alt="screen shot 2016-05-20 at 3 12 54 pm" src="https://cloud.githubusercontent.com/assets/15307586/15418888/71284b18-1e9d-11e6-93aa-c71c14ae02de.png">

**Comment by vdesabou** [comment]
Hi,

Are you using Alfred v3, if so you should use the beta release from here https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/beta_alfred_v3

Otherwise, send me a TGZ file by following http://alfred-spotify-mini-player.com/articles/support/

**Comment by shigg1120** [comment]
yes.I am using Alfred 3.The 6.3 release solved the problem
