### ISSUE TITLE
Add a variable to disable notifications

### ISSUE THREAD

**Issue by grimborg** [vdesabou/alfred-spotify-mini-player#127]
I couldn't find an easy way to disable notifications (I've just commented out the script that creates them). There should be an easy way to do that: notifications can be very distracting when you're working.

**Comment by vdesabou** [comment]
You can use normal OS X Notification Center settings to disable notifications, more info here http://alfred-spotify-mini-player.com/articles/now-playing/

Vincent

**Comment by vdesabou** [comment]
Closing.

**Comment by nikitavoloboev** [comment]
I can't hide notifications as there is no Spotify Mini Player in Notifications:

![2019-10-29 at 10 38](https://user-images.githubusercontent.com/6391776/67755344-47ba1200-fa38-11e9-879b-d741f3a4c856.png)

I searched through it all.

I still get notifications.

What can I do to disable them?
