### ISSUE TITLE
Shortcut for saving current song "Save to Your Music"

### ISSUE THREAD

**Issue by djan92** [vdesabou/alfred-spotify-mini-player#131]
![image](https://cloud.githubusercontent.com/assets/1806397/16463317/296f7b90-3dea-11e6-8b0c-a11a27dca31f.png)

Shortcut to push the + button.

**Comment by vdesabou** [comment]
Hi,

It should be there already:

I suggest you configure to "control Your Music", see http://alfred-spotify-mini-player.com/articles/alfred-playlist/

And then you have multiple options to add tracks to Your Music easily, and also the command:

![screen shot 2016-06-30 a 09 13 53]
(https://cloud.githubusercontent.com/assets/4061923/16479848/33a69c38-3ea3-11e6-8f3d-97df270e1bba.jpg)

For which you can setup an hotkey of course http://alfred-spotify-mini-player.com/articles/hotkeys/
