### ISSUE TITLE
Allow users to remove the song playing from the current playlist

### ISSUE THREAD

**Issue by sparkdevelopment** [vdesabou/alfred-spotify-mini-player#133]
If I'm listening to a song from a playlist and I want to remove it, I would like a spotify-mini command to do this

**Comment by vdesabou** [comment]
You can use keyword:

![screen shot 2016-06-30 a 15 29 09](https://cloud.githubusercontent.com/assets/4061923/16489820/6e36d672-3ed7-11e6-8977-901e3ac92610.jpg)


Or in Current Track menu:

![screen shot 2016-06-30 a 15 28 39](https://cloud.githubusercontent.com/assets/4061923/16489830/78e83976-3ed7-11e6-87f4-7701a23fee38.jpg)

**Comment by sparkdevelopment** [comment]
Ah, my bad. I looked as well.
