### ISSUE TITLE
Clicking Growl Notifications causes "unidentified developer" message

### ISSUE THREAD

**Issue by dncrews** [vdesabou/alfred-spotify-mini-player#136]
If I click on any of the growl notifications, I get the following error message. I can't seem to find the actual app to manually run it and give it permission, and I'm not interested in disabling Gatekeeper.

![image](https://cloud.githubusercontent.com/assets/353090/16923405/53f9d940-4cd7-11e6-8bf7-a8ddaac39144.png)

Please assist.

**Comment by dncrews** [comment]
For the sake of searchability for anyone in the future:

"Spotify Mini Player.app" can't be opened because it is from an unidentified developer.

**Comment by vdesabou** [comment]
Type ```spot_mini_debug ``` and select Browse to Alfred workflow folder:

![screen shot 2016-07-19 a 09 05 54](https://cloud.githubusercontent.com/assets/4061923/16941403/25f38cee-4d90-11e6-8e9a-e6e9656709c8.jpg)

Then in Finder, right click on Spotify Mini Player.app and select open. Accept the warning message

**Comment by dncrews** [comment]
That did it for me.
