### ISSUE TITLE
garbled characters in playlists

### ISSUE THREAD

**Issue by jostyee** [vdesabou/alfred-spotify-mini-player#139]
v6.3

![screen shot 2016-08-02 at 12 54 48](https://cloud.githubusercontent.com/assets/88564/17317465/93d0e1fa-58b0-11e6-92cb-69a1549094c3.png)

There're unrecognizable chars in every playlists, and it can't handle CJK names.

**Comment by vdesabou** [comment]
Try to install the beta here https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/beta-v6.4

It contains fix for weird characters

Vincent

**Comment by vdesabou** [comment]
Closing as no feedback
