### ISSUE TITLE
latency

### ISSUE THREAD

**Issue by pexxi2** [vdesabou/alfred-spotify-mini-player#140]
commands take about 45 sec to have effect

**Comment by vdesabou** [comment]
It is not normal at all.
Can you follow this http://alfred-spotify-mini-player.com/articles/support/ in order to send me the TGZ file

Vincent

**Comment by vdesabou** [comment]
Any feedback?

**Comment by pexxi2** [comment]
I will Check again tomorrow 

Liebe Grüße
Andreas

> Am 05.08.2016 um 11:19 schrieb Vincent <notifications@github.com>:
> 
> It is not normal at all.
> Can you follow this http://alfred-spotify-mini-player.com/articles/support/ in order to send me the TGZ file
> 
> Vincent
>

**Comment by vdesabou** [comment]
Closing as no feedback, re-open if needed
