### ISSUE TITLE
Unable to Authenticate

### ISSUE THREAD

**Issue by kaofelix** [vdesabou/alfred-spotify-mini-player#143]
I'm getting: 

INVALID_CLIENT: Invalid redirect URI

when trying to authenticate with Spotify Mini Player. I have version 6.4 listed in Alfred window and I'm using Alfred 3. I updated it from packal, if this makes any difference.

Cheers!

**Comment by vdesabou** [comment]
Hi,

You probably did not click on the SAVE button in your [Application page](https://developer.spotify.com/my-applications)

Make sure to follow carefully the steps from Setup http://alfred-spotify-mini-player.com/setup/

**Comment by kaofelix** [comment]
You're right, sorry. Didn't pay enough attention to the instructions. Thank you!
