### ISSUE TITLE
Launching playlist when Spotify app is not opened

### ISSUE THREAD

**Issue by altern8tif** [vdesabou/alfred-spotify-mini-player#147]
Launching a playlist through the Alfred workflow when Spotify is closed only causes Spotify to open without even opening the playlist.

An additional invocation of the workflow to launch the playlist is necessary for it to _actually_ launch (and play) the playlist.

Is this the intended workflow or is this a bug?

**Comment by vdesabou** [comment]
Yes you are right, it's a bug. As of now, I've never managed to find a good fix for this. I'll think about it

**Comment by altern8tif** [comment]
@vdesabou thanks for the quick reply.  Would love to dig into the code to see if I can fix it, but unfortunately I don't have much bandwidth to do this now.

Perhaps in a couple of month's time (if it hasn't been fixed by then).

**Comment by vdesabou** [comment]
Can you try this version https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v-6.6-beta ?

**Comment by altern8tif** [comment]
It works! ⚡️ 

Maybe make it `sleep(5)` instead?  Although I'm not sure if that's long enough on slower computers.

**Comment by vdesabou** [comment]
Thanks for the feedback.
Yes I better be safe and keep 6 sec. In my Case (MacBook Pro 2013), this is the time it takes before Spotify becomes fully started.

Leaving opened until 6.6 is released
