### ISSUE TITLE
unable to initialize with mopidy

### ISSUE THREAD

**Issue by joewongvt** [vdesabou/alfred-spotify-mini-player#154]
In setting up a new computer with this workflow, I had to authenticate with Spotify for the sole purpose of initializing this workflow, only to immediately go into settings to enable mopidy.  Would it be possible to opt-out of Spotify authentication and only use mopidy?  I would be ok with reduced functionality as a result of skipping authentication.

**Comment by vdesabou** [comment]
The workflow uses [Spotify Web API](https://developer.spotify.com/web-api/) to create the library, search online, etc.. It is absolutely needed, and the authentication is done in order to access this API.

Just to make sure, you're not saying that you had to install Spotify Desktop client, right ?

**Comment by joewongvt** [comment]
I'm primarily interested in playback controls for mopidy  - while the other features are nice, I don't use much of the library/search capabilities because I also use non-Spotify streaming services like Google Music.

With that said, without Spotify Desktop installed, I was running into authentication errors along the lines of "could not connect/resolve/?? client" when validating my application secret.  In response, I reset my Spotify app credentials, installed Spotify Desktop, and reinitialized the workflow - and everything worked fine.  That's not conclusive proof that the Spotify Desktop client is required, as I could very well have done something else wrong in the configuration.

I sync my Alfred preferences across machines, so perhaps that had something to do with it?

**Comment by vdesabou** [comment]
> I'm primarily interested in playback controls for mopidy - while the other features are nice, I don't use much of the library/search capabilities because I also use non-Spotify streaming services like Google Music.

I see, but I don't plan to create a "Mopidy only" playback workflow (even though it should not be really complex). So the Spotify API authentication will remain as it is.

>With that said, without Spotify Desktop installed, I was running into authentication errors along the lines of "could not connect/resolve/?? client" when validating my application secret. In response, I reset my Spotify app credentials, installed Spotify Desktop, and reinitialized the workflow - and everything worked fine. That's not conclusive proof that the Spotify Desktop client is required, as I could very well have done something else wrong in the configuration.

No I don't see why Spotify Desktop would be needed for that. Must have been a user error during authentication as it is now working as I understand it.

>I sync my Alfred preferences across machines, so perhaps that had something to do with it?

No it should not be a problem

**Comment by vdesabou** [comment]
Closing (unless you need more help?)
