### ISSUE TITLE
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused

### ISSUE THREAD

**Issue by anismilali** [vdesabou/alfred-spotify-mini-player#155]
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 8065: Connection refused

**Comment by vdesabou** [comment]
can you please describe your issue and provide a TGZ file as described here http://alfred-spotify-mini-player.com/articles/support/
