### ISSUE TITLE
Add Sharing feature using Mac OS X Sharing

### ISSUE THREAD

**Issue by blackxored** [vdesabou/alfred-spotify-mini-player#158]
Unless I'm missing something obvious, it would be nice to have a share option similar to what Apple Music / Workflow provides on iOS.

**Comment by vdesabou** [comment]
Can you provide example?

--
Vincent

**Comment by blackxored** [comment]
I'm talking about the Share Song option that's on the desktop and mobile
versions of the Spotify client.

—
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by vdesabou** [comment]
No there is no such thing and I don't plan to add it for now, but I will think about a way to make the workflow 'pluggable' with other workflows, in order to ease this.

I've added in next release a way to copy the current track by doing CMD-C on current track:

![screenshot 2017-01-02 a 15 08 17](https://cloud.githubusercontent.com/assets/4061923/21590700/66a9b1f4-d0fe-11e6-9c18-2493d52a0d16.jpg)

It will put in clipboard ```#NowPlaying Cancre ultime by Cabadzi```

**Comment by blackxored** [comment]
Got it. I think that's good enough, only missing is the URL. I was looking
into the Apple Script interface but Share isn't exposed. If you've the
track ID perhaps it could be done. It's extra work, that much I agree.

—
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by vdesabou** [comment]
I went ahead and added the feature:

You have the option to share in Current Track menu:

![screenshot 2017-01-03 a 16 37 14](https://cloud.githubusercontent.com/assets/4061923/21612812/e851afd4-d1d2-11e6-9670-1a68f5d53429.jpg)

Or you can use command ```share```

![screenshot 2017-01-03 a 16 37 56](https://cloud.githubusercontent.com/assets/4061923/21612844/0444cc44-d1d3-11e6-9da0-b2ad767b56e4.jpg)

Then it launch Mac OS X Sharing  window:

![screenshot 2017-01-03 a 16 38 37](https://cloud.githubusercontent.com/assets/4061923/21612872/1d33bd96-d1d3-11e6-95dd-594c20a06531.jpg)

Note that URL is here, along with an artwork.

You can switch from twitter to Facebook by changing workflow variable ```sharing_service```:

![screenshot 2017-01-03 a 16 39 42](https://cloud.githubusercontent.com/assets/4061923/21612910/42ba54d0-d1d3-11e6-8831-8f402cc7fa97.jpg)

**Comment by blackxored** [comment]
This is awesome, man!
I just tested in the beta version, works beautifully. I just modified it a bit to include the ♫ sign, and remove the artwork since that effectively denies the twitter card functionality, which IMHO looks nicer. Besides I don't want all my photo feed flooded by song pics :D 
Only wish I could bind a direct hotkey to it as opposed to having to go through the Current Track hotkey + Cmd 9 option, but hey.

**Comment by vdesabou** [comment]
Good point, i will remove the artwork!
Where do you want the music 🎶 sign?
For hotkey, you can set your own, see http://alfred-spotify-mini-player.com/articles/hotkeys/
The share command is at the bottom of the workflow

Vincent

**Comment by blackxored** [comment]
Here's how mine looks now (the Unicode seems to mess a bit on how the URL part looks, but looks fine on Twitter):

![](https://www.dropbox.com/s/ly6l41zau57b9c3/Screenshot%202017-01-03%2021.48.29.png?dl=1)

About the hotkey, you're right I totally missed it (I had bound "Current Track" instead). Sweet.
Now I've one hotkey setup, yay. This, coupled with a few IFTTT recipes I've got is all I need, thanks.

**Comment by vdesabou** [comment]
Can you please test the new beta https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v6.7-beta3

Now sharing service is configurable via settings:

![screenshot 2017-01-04 a 10 44 47](https://cloud.githubusercontent.com/assets/4061923/21638237/d5a3232a-d26a-11e6-8e4b-d67068a3aee5.jpg)


And the text is configurable via variables:

![screenshot 2017-01-04 a 10 42 08](https://cloud.githubusercontent.com/assets/4061923/21638248/dea0a826-d26a-11e6-9f0e-149c255d3ab0.jpg)

It gives:

![screenshot 2017-01-04 a 10 45 30](https://cloud.githubusercontent.com/assets/4061923/21638269/f1dab86e-d26a-11e6-856e-45aca12dc43e.jpg)

**Comment by vdesabou** [comment]
http://alfred-spotify-mini-player.com/blog/Version-7.0/
