### ISSUE TITLE
Control radio stations and daily mix

### ISSUE THREAD

**Issue by alexanderjeurissen** [vdesabou/alfred-spotify-mini-player#166]
I'm a heavy user of the daily mix section that Spotify introduced a while back.
I really like spotify-mini-player but I was hoping it had a feature to `favorite` and `remove` tracks in the daily mix section.

I'm aware that there are options to `remove` and `add` the current playing song to the music library but the `favorite` and `remove` actions in the Daily mix section are more powerful as they also influence future curation of those daily mixes.

I was wondering if these actions are made available in the API and if so if you plan on adding those.

**Comment by vdesabou** [comment]
Yes, I'm a huge fan of daily mix section as well, and you can be sure I'll add it when it would be technically possible.

Unfortunately, it is not currently as the [Spotify Web API](https://developer.spotify.com/web-api/) does not allow to get these personalized playlists.

There is an open [issue](https://github.com/spotify/web-api/issues/324) about this, but nothing has been done on Spotify side yet.

**Comment by vdesabou** [comment]
Closing for now, until Spotify Web API is updated to support this.
