### ISSUE TITLE
No notification

### ISSUE THREAD

**Issue by denispasin** [vdesabou/alfred-spotify-mini-player#167]
Hey ! Maybe I missed something in the config but I don't have any "now playing" notification.

spotify-mini-player isn't present in notification center either.

**Comment by vdesabou** [comment]
Can you send me a ZIP file by email as explained here http://alfred-spotify-mini-player.com/articles/support/

**Comment by denispasin** [comment]
Done

**Comment by vdesabou** [comment]
you get error:

`./src/spotify_mini_player_notifications.ksh[154]: StartAppleScript: line 35: 70711: Terminated`

Can you open "Script Editor" application and copy/paste the following:

```
try
	tell application "Spotify"
		
		set current_track_url to null
		set old_player_state to null
		
		repeat until application "Spotify" is not running
			set track_url to spotify url of current track
			
			if the player state is stopped then
				set player_state to "stopped"
				try
					if current track is not missing value then set player_state to "paused"
				end try
			else if the player state is paused then
				set player_state to "paused"
			else
				set player_state to "playing"
			end if
			
			if track_url ≠ current_track_url then
				set current_track_url to spotify url of current track
				
				tell application "Alfred 3"
					run trigger "display_current_track_notification" in workflow "com.vdesabou.spotify.mini.player" with argument track_url
				end tell
			end if
			
			if player_state ≠ old_player_state and player_state is "playing" then
				tell application "Alfred 3"
					run trigger "display_current_track_notification" in workflow "com.vdesabou.spotify.mini.player" with argument player_state
				end tell
			end if
			
			set old_player_state to player_state
			delay 3
		end repeat
	end tell
on error error_message
	return
end try
```

And then click on Play button:


![screenshot 2017-01-27 at 16 24 38](https://cloud.githubusercontent.com/assets/4061923/22376151/2740f6d6-e4ad-11e6-8564-baf690373c32.jpg)


Normally you should see no error and `Running`in output.

**Comment by denispasin** [comment]
That's exactly what I have (sorry for the delay)

**Comment by vdesabou** [comment]
> That's exactly what I have (sorry for the delay)

Ok so it should work then..

Can you try to disable in Settings `Now Playing`notifications:

![screenshot 2017-01-28 at 11 32 40](https://cloud.githubusercontent.com/assets/4061923/22395972/8bb87b02-e54d-11e6-894c-2fb7c86fd151.jpg)

And then Enable again.

If this still does not work, send me another email with ZIP file

**Comment by denispasin** [comment]
Hi again,

Sorry for the delay. I tried again today (it's on my work computer) still not working. It works perfectly on my own computer though...

I'm sending you a new zip.

**Comment by vdesabou** [comment]
Type spot_mini_debug and choose Browse to Alfred workflow folder:

![screenshot 2017-01-30 at 19 47 04](https://cloud.githubusercontent.com/assets/4061923/22589875/e0309502-ea0c-11e6-887e-0d7d315e2d00.jpg)


Then in finder, go to App/<color> directory:

![unnamed](https://cloud.githubusercontent.com/assets/4061923/22589879/e3a2dea2-ea0c-11e6-94d3-dc8f8e54ca6f.jpg)


Then try to double click on Spotify Mini Player, it should open quickly the app, and not show an error message.

**Comment by denispasin** [comment]
Gosh ! It worked ! (right-click + open app. Asking if I'm sure that I want to open it since it's from an unknown source).

**Comment by denispasin** [comment]
Thanks a lot !
