### ISSUE TITLE
Local track issue with AppleScript

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#172]
The following works:

```
tell application "Spotify"
	play track "spotify:local:::My+Recording:98" in context "spotify:user:vdesabou:playlist:4lkQcsSBtIjMb7UYUaap0I"	
end tell
```

But this doesn't work anymore:

```
tell application "Spotify"
	play track "spotify:local:::My+Recording:98"	
end tell
```

Another Spotify issue?

**Comment by garyking** [comment]
Hi, was this issue ever fixed? Is it possible to play local Spotify tracks via AppleScript?

**Comment by vdesabou** [comment]
@garyking Yes it seems it is fixed now. The example above now works with latest Spotify Desktop app
