### ISSUE TITLE
Add a setting to put albums at the top of search lists

### ISSUE THREAD

**Issue by derkork** [vdesabou/alfred-spotify-mini-player#173]
I'm rarely listening to single tracks, rather I listen to full albums all the time. However when I do a search for an album name, the workflow usually lists all the tracks from the album first and the album below them. Most of the time the album is on the second page (if it has more than 9 tracks) so I cannot use  shortcut to access it but I have to scroll through all these tracks. It would be nice if there was a setting to put albums at the top of the search results.

**Comment by vdesabou** [comment]
Yes, good idea, I'll include this

**Comment by derkork** [comment]
Thanks a lot :)

**Comment by vdesabou** [comment]
Can you test with this [BETA release](https://transfer.sh/26WuW/spotifyminiplayer-beta.alfredworkflow) ?

There is now an option in Settings to change order results:

![screenshot 2017-03-03 at 17 15 21](https://cloud.githubusercontent.com/assets/4061923/23558774/1060d3fc-0035-11e7-9a45-9cd79953cb26.jpg)


Then you can select the order you want:

![screenshot 2017-03-03 at 17 16 05](https://cloud.githubusercontent.com/assets/4061923/23558783/1ffd2ee6-0035-11e7-83ad-2af84517b879.jpg)


Let me know if this is what you had in mind

Thanks for the 🍺 BTW !

**Comment by derkork** [comment]
Works great here, thanks a lot  :)
