### ISSUE TITLE
Search with non-english characters

### ISSUE THREAD

**Issue by rargelaguet** [vdesabou/alfred-spotify-mini-player#174]
I often listen to music in non-english languages such as spanish, french or catalan, where there are some letters which contain accents such as "La Raíz". Most people when typing for fast searches just ignore them and type "la raiz" but I noticed that in mini-player I have to type the "í" explicitly otherwise it reports no hit. Is it possible to fix this?

**Comment by vdesabou** [comment]
I think I already tried to do this in the past, but that's very tricky. I'll try to have another look, but I can't promise I will manage to workaround that

**Comment by vdesabou** [comment]
I'm sorry but I will have to close this issue because I use SqlLite to store library and this is very difficult to find a way to do that. Unless someone wants to work on it, I will accept PR.
