### ISSUE TITLE
Volume Down hotkey

### ISSUE THREAD

**Issue by tsigo** [vdesabou/alfred-spotify-mini-player#175]
I noticed today there's a hotkey entry for "Volume Up", but not one for "Volume Down", so I'm hoping that can be added.

In the long run, I think the ideal design would be to make most of the commands have External actions, and then I could create a separate workflow with just hotkeys pointing to external actions from this workflow.

Thanks for this comprehensive workflow, @vdesabou

**Comment by vdesabou** [comment]
Thanks for reporting this. I've fixed it.

I've opened Add external trigger for every command #176 for tracking your proposed enhancement
