### ISSUE TITLE
I can't find an action to instantly add a currently playing song to my Alfred playlist

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#177]
I remember there was such action but I can't find it now.

Thank you for any help.

**Comment by vdesabou** [comment]
Maybe this? `add_current_track_to_alfred_playlist_or_your_music`

![screenshot 2017-03-07 at 10 02 23](https://cloud.githubusercontent.com/assets/4061923/23649034/37deabbc-031d-11e7-93c6-93cb067a9570.jpg)

Note that you can rename all commands by using Alfred workflow variables, see http://alfred-spotify-mini-player.com/articles/customization/
