### ISSUE TITLE
Installing the workflow?

### ISSUE THREAD

**Issue by tommykiser** [vdesabou/alfred-spotify-mini-player#180]
I feel like I'm missing something in the installation process. I setup the Application in Spotify, then I download the repo from github and unzip it. Is there a step here to register the workflow with Alfred? I tried to see if Alfred suddenly knew the spot_mini keyword, but it doesn't. It does however come up with "Spotify Mini Player", but selecting that in Alfred doesn't seem to do anything.

Thanks for your help, looking forward to trying this thing. :)

Cheers,
-Tommy

**Comment by tommykiser** [comment]
Nevermind, figured it out. I was downloading the GitHub repo, rather than the workflow. It was sort of easy to miss the download button on your homepage, oddly enough. I'd recommend adding a step of "Download and install the workflow," and a download link for the workflow installer, on your setup page (http://alfred-spotify-mini-player.com/setup/) to make it idiot-proof (coming from a certified idiot).

Cheers,
-Tommy

**Comment by vdesabou** [comment]
Ok it's now done :)
