### ISSUE TITLE
Adding track to playlist notifies track added to incorrect playlist

### ISSUE THREAD

**Issue by leegenes** [vdesabou/alfred-spotify-mini-player#182]
Hey there,
Been loving on this workflow for a while, and still going! Thanks.

When I view current track, select Add Track {track name} to..., and select a playlist, the notification says the track was added to the wrong playlist.

In this particular case:
- Listening to track from Your Daily Mix
- Adding track to Liked From Radio
- Notified track was added to Discover Weekly
- Track added to Liked From Radio

Poked around the source a bit to see if I could find anything. Not yet [don't know PHP], but I'm hot on the trail. Will update, or submit PR if I find that it's something super simple.

Thanks again!

**Comment by vdesabou** [comment]
I can't reproduce your issue. Is it only happening for this use case ?

Is it 100% reproducible on your side?

**Comment by leegenes** [comment]
Must have a been a session problem. Happened consistently throughout a day [~5-7 times]. After reboot and relaunching Alfred and Spotify, I can't reproduce either.

Closing for now. Will reopen if reborn and persistent.
Sorry about that!
