### ISSUE TITLE
Add option to reduce number of notifications

### ISSUE THREAD

**Issue by forrestchang** [vdesabou/alfred-spotify-mini-player#183]
There is no need to show how much time it takes to downloads the album cover. Just keep notifications simple! Too much notifications make me feel bothered!

**Comment by vdesabou** [comment]
So in version 7.1, I will add a variable `reduce_notifications` which is set to 1 by default:

![screenshot 2017-03-24 at 12 12 27](https://cloud.githubusercontent.com/assets/4061923/24291961/79708368-108b-11e7-8d29-ea67e1a82967.jpg)


With reduce_notifications=0, we have:

![screenshot 2017-03-24 at 12 14 09](https://cloud.githubusercontent.com/assets/4061923/24291974/83694490-108b-11e7-806d-2102f548491f.jpg)


With reduce_notifications=1, we only have:

![screenshot 2017-03-24 at 12 14 14](https://cloud.githubusercontent.com/assets/4061923/24291983/8ecd656e-108b-11e7-9e3d-aa03dcdb10bb.jpg)

Would that make you less bothered ?? 😄

**Comment by forrestchang** [comment]
@vdesabou Thanks!
