### ISSUE TITLE
Newsletter for Updates of the Workflow

### ISSUE THREAD

**Issue by spieglio** [vdesabou/alfred-spotify-mini-player#189]
I just discovered this workflow. I'll try and see how it works in the coming weeks.

One thing I noticed: is there a newsletter of some sort to know when there will be an update? That'd be super helpful (or does the workflow self update)?

Thanks for your work, Vincent.

All the best for future development,
Chris

**Comment by vdesabou** [comment]
Hi !

So there is a [blog](http://alfred-spotify-mini-player.com/blog/) so you can
There is also a [RSS feed ](http://alfred-spotify-mini-player.com/atom.xml)
You can follow on [twitter](https://twitter.com/TheMiniPlayer)
And you also get notified when there is an update when using the workflow, see http://alfred-spotify-mini-player.com/articles/workflow-update/

**Comment by spieglio** [comment]
Thanks for pointing these out. Just that I don't use a RSS Feed any more, and don't check Twitter (Email is kinda the only place I really check regularly and read everything - on twitter things get lost).

But the "Check for Updates" in the tool sounds like a good solution. Thanks :)
