### ISSUE TITLE
add an option to completely remove Notifications

### ISSUE THREAD

**Issue by neoromantique** [vdesabou/alfred-spotify-mini-player#191]
Currently, as it is, SMP has a tendency to clutter up the notification drawer. I believe either making the notification 'non-sticky' or adding an option to remove them altogether would solve the issue.

**Comment by vdesabou** [comment]
Notifications are using standard OSX notifications, so you can configure them in Preferences->Notifications (see  http://alfred-spotify-mini-player.com/articles/now-playing/):

![screenshot 2017-07-24 at 09 18 39](https://user-images.githubusercontent.com/4061923/28512230-49ea6cf0-7051-11e7-8c6b-2417c99c57c6.jpg)
