### ISSUE TITLE
Installation failure on 10.13

### ISSUE THREAD

**Issue by ragnarkon** [vdesabou/alfred-spotify-mini-player#192]
Saw a few people on Twitter talk about PHP issues during installation on 10.13, but evidently none of them opened an issue.

Well... just installed 10.13 and I too am getting the PHP installation issue.  Upon trying to authenticate to Spotify, it errors stating that it requires PHP 5.4.0 or later.

Ran the following, returns 7.1.7:

```
ragnarkon@mac:~ $ php -r 'print phpversion();'
7.1.7
```

Being relatively new to Alfred and almost zero experience with PHP, not sure where to start troubleshooting this on my own.  But I'm certainly willing to help grab as much information as needed.

**Comment by vdesabou** [comment]
First of all, thanks for opening an issue.

I've fixed the problem, can you download and install this BETA: https://transfer.sh/15eEgY/spotifyminiplayer-beta.alfredworkflow

Keep me posted

**Comment by ragnarkon** [comment]
@vdesabou Awesome.

d5af45a appears to have fixed it.

I had to reset the mini player settings and re-auth.  But beyond that... was seemless.

**Comment by vdesabou** [comment]
>I had to reset the mini player settings and re-auth

What was the reason for that ? I try to understand why upgrading to High Sierra would break settings

**Comment by ragnarkon** [comment]
I'm not sure.

Upgraded the workflow, then tried to re-authenticate.  The PHP error went away, but a browser window never opened.  Restarted Alfred and tried again.  Didn't work. Cleared Safari history/cookies and tried again... still didn't work.

It was only after I reset the Mini Player settings that it worked.

Not a huge deal for me because this was a fresh install of 10.13, with a fresh install of Alfrred.  So there wasn't any settings that I lost.  But still strange.

**Comment by vdesabou** [comment]
Version 7.3 is now available http://alfred-spotify-mini-player.com/blog/Version-7.3/
