### ISSUE TITLE
Add settings to open lyrics directly in the default browser

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#193]
I find fetching of lyrics to Alfred too slow and would love to just set a hotkey so that if I activate it, it will just open the lyrics in the browser. 

Essentially picking the first option here without actually going there and pressing enter : 

![2017-07-27 at 21 04](https://user-images.githubusercontent.com/6391776/28687590-30b234b4-730f-11e7-8fd1-bd9bffe62bc4.png)

**Comment by vdesabou** [comment]
Good idea, I've added a Setting to choose to display lyrics directly in the default browser:


![screenshot 2017-07-28 at 16 48 46](https://user-images.githubusercontent.com/4061923/28722618-a78fccea-73b4-11e7-8171-e73094f2874c.jpg)

Try it by installing:
https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v7.3-beta

**Comment by nikitavoloboev** [comment]
That is lovely. One thing though that stops me from installing new updates is that I set so many custom external triggers that any update I do wipes them away and it's quite painful to get them back. :( 

I guess there is no solution to it though and I have to do it.

**Comment by vdesabou** [comment]
What kind of external trigger is missing, because I've added a lot in https://github.com/vdesabou/alfred-spotify-mini-player/issues/176 ?

**Comment by nikitavoloboev** [comment]
Oh that is awesome. [Here](https://transfer.sh/GsxIe/spotify-mini-player.alfredworkflow) is my modified workflow with all the custom triggers. You are right, there is a lot of them there and thanks for that. 

I am not actually sure which ones I made of my own. Will download the update and compare and tell you. :)

**Comment by vdesabou** [comment]
Let me know if there are some missing, it would be a shame to avoid updates just because of that 😄

**Comment by nikitavoloboev** [comment]
Finally got a chance to install the update. :)

I have few questions though. This trigger : 


![2017-07-29 at 20 14](https://user-images.githubusercontent.com/6391776/28747236-7df19da0-749a-11e7-9ef0-1c7216c330ff.png)

Still does not open lyrics in the browser. Or I am doing something wrong.


If you can add these external triggers, it would be amazing.

1. Opening Currently song playing

Currently I create external trigger and pass in `✧Current Track▹` to it.

2. Adding current song playing to my Alfred playlist 

In old update, I had this : 

![2017-07-29 at 21 17](https://user-images.githubusercontent.com/6391776/28747594-5f289014-74a3-11e7-927d-674f5f1dbeff.png)

Can't find it anywhere in the new update. :( 

Also it would be amazing to add Soundcloud, to web search. 

Aside from this, this is amazing update and amazing workflow. If this were added, updating would be seamless for me. 💛

**Comment by nikitavoloboev** [comment]
Also another option, to 'view' currently playing playlist would be amazing. So I can see songs that are going to come next and what songs are inside the playlist that is being played right now whether it is radio playlist or my own.

**Comment by nikitavoloboev** [comment]
Also, this : 

![2017-07-29 at 21 26](https://user-images.githubusercontent.com/6391776/28747653-9cce44b2-74a4-11e7-9106-5e2823a82a4e.png)

Does not work. It simply brings me to twitter, youtube home page. 

This one works : 

![2017-07-29 at 21 26](https://user-images.githubusercontent.com/6391776/28747659-a93a1014-74a4-11e7-8b28-c1325c9a0e0e.png)

But its a bit slower to boot up. :(

**Comment by vdesabou** [comment]
>Still does not open lyrics in the browser. Or I am doing something wrong.

You need to activate the option in Settings menu.
![screenshot 2017-07-28 at 16 48 46](https://user-images.githubusercontent.com/4061923/28766900-e89466c8-75d1-11e7-84fc-e97f1e264435.jpg)



>If you can add these external triggers, it would be amazing.

>Opening Currently song playing
>Currently I create external trigger and pass in ✧Current Track▹ to it.

Ok I will

>Adding current song playing to my Alfred playlist
>Can't find it anywhere in the new update. :(

I don't understand, It is definitely there, see:

![screenshot 2017-07-31 at 09 21 00](https://user-images.githubusercontent.com/4061923/28767017-6bc2a870-75d2-11e7-8a77-8c27f69120ee.jpg)

**Comment by vdesabou** [comment]
>Also another option, to 'view' currently playing playlist would be amazing. So I can see songs that are going to come next and what songs are inside the playlist that is being played right now whether it is radio playlist or my own.

Isn't it the [Play Queue](http://alfred-spotify-mini-player.com/articles/play-queue/) feature ?

**Comment by vdesabou** [comment]
>Does not work. It simply brings me to twitter, youtube home page.

This is because it is not supposed to be used, this is used by workflow for internal stuff. I've added some comments:

![screenshot 2017-07-31 at 09 35 59](https://user-images.githubusercontent.com/4061923/28767393-cc88fd2a-75d3-11e7-9308-2a576de908d6.jpg)

>But its a bit slower to boot up. :(

It just needs to call AppleScript to get current track, which takes a couple of seconds

**Comment by vdesabou** [comment]
>Also it would be amazing to add Soundcloud, to web search.

Ok, I've opened Add Soundcloud to web search #196 to track this

**Comment by nikitavoloboev** [comment]
> You need to activate the option in Settings menu.

This works amazingly well. Thank you.

> I don't understand, It is definitely there, see:

Oh yes, my bad didn't see it. 

> Isn't it the Play Queue feature ?

Oh yes, it is. There is no external trigger for it though I think. :)

**Comment by vdesabou** [comment]
>Oh yes, it is. There is no external trigger for it though I think. :)

It's coming with Add missing external triggers #195 😄 

Out of curiosity, how do you use so many external triggers ? I barely use one just to refresh library automatically..

**Comment by nikitavoloboev** [comment]
[Karabiner](https://github.com/tekezo/Karabiner). I have a [very very long config](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L2253) for it. Really changes how you use your mac although sadly Karabiner broke on new versions of macOS, still waiting for [Karabiner Elements](https://github.com/tekezo/Karabiner-Elements) to catch up. :)

**Comment by vdesabou** [comment]
Version 7.3 is now available http://alfred-spotify-mini-player.com/blog/Version-7.3/

**Comment by sunny0105** [comment]
using the latest version 7.3 but struggling with lyrics..does not matter what songs i play..it is always no lyrics found..any suggestions?
