### ISSUE TITLE
How to instantly see my Alfred playlist?

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#194]
There is an external trigger to show this : 

![2017-07-27 at 21 29](https://user-images.githubusercontent.com/6391776/28688590-a5c357ee-7312-11e7-8a31-16c3081f409b.png)

But I would love to cut this step and simply go to my alfred playlist straight away since I don't plan to change or clean my playlist any time soon. :)

**Comment by vdesabou** [comment]
Hi !

Can you try what I've in beta v7.3, download here https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v7.3-beta

**Comment by nikitavoloboev** [comment]
This works. Thank you. :)

**Comment by vdesabou** [comment]
leaving open until 7.3 is released

**Comment by vdesabou** [comment]
Version 7.3 is now available http://alfred-spotify-mini-player.com/blog/Version-7.3/
