### ISSUE TITLE
Online playlist search

### ISSUE THREAD

**Issue by setegonz** [vdesabou/alfred-spotify-mini-player#198]
Always showing "there is no result for this search" when trying to look fo playlists.
![new issue vdesabou-alfred-spotify-mini-player opera today at 3 36 44 pm](https://user-images.githubusercontent.com/11341688/28982134-11f70f8c-792b-11e7-96ae-29a0087c819f.png)

**Comment by vdesabou** [comment]
This should be fixed with beta 7.3 https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v7.3-beta

**Comment by vdesabou** [comment]
Version 7.3 is now available http://alfred-spotify-mini-player.com/blog/Version-7.3/
