### ISSUE TITLE
Can't find external trigger to show current playing track as notification

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#200]
Can't really find this action anywhere in the workflow. Perhaps I have missed it.

Would be awesome to add it if I did miss it. 

Thank you.

**Comment by vdesabou** [comment]
Here it is 😄 

![screenshot 2017-08-19 at 11 43 34](https://user-images.githubusercontent.com/4061923/29485538-b19bf472-84d3-11e7-9c21-01469e70e6b2.jpg)

**Comment by nikitavoloboev** [comment]
Oh, didn't see it. 🙂 

Thank you.
