### ISSUE TITLE
Playing a song from workflow clears the queue

### ISSUE THREAD

**Issue by JakuJ** [vdesabou/alfred-spotify-mini-player#205]
Whenever I search and play a song from "My
 music" it plays it, but switches the scope to 'artist', so that when the
 song finished playing, the next one in "My music" doesn't play (the queue
 is cleared). How do I work around this?

**Comment by vdesabou** [comment]
Are you talking about the [Play Queue](http://alfred-spotify-mini-player.com/articles/play-queue/) here?

I don't understand your problem, can you describe it more and provide examples please

**Comment by JakuJ** [comment]
Actually, I don't even have this "play queue" option in my main menu
<img width="554" alt="zrzut ekranu 2017-08-30 o 20 55 04" src="https://user-images.githubusercontent.com/23246747/29889844-e30266ea-8dc5-11e7-9270-130f2baccdea.png">
What I mean is: when you play a song from "My music" in Spotify app, after the song finishes Spotify play the next one. If you instead: 1) Have any song from "My music" currently playing 2) Search for and play any other song that exists in your "My music" library via spot_mini -> song name -> return 3) It plays the requested song, but when you go back to the app you see that it's not showing "My music" anymore, but album screen. When the song finishes playing, it doesn't go to the next one in "My music" nor the next one in the album.

**Comment by vdesabou** [comment]
Ah I see, thanks for the details.

Unfortunately, nothing can be done as there is no Spotify API to play "My Music" (see https://github.com/vdesabou/alfred-spotify-mini-player/issues/95), so I can't do anything about it I'm afraid.

If Spotify change their API, I'll definitely do something about it
