### ISSUE TITLE
Add reddit search

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#206]
It would be awesome to add reddit search to the web search of current song action. 

Thank you.

**Comment by vdesabou** [comment]
I've implemented to search for current artist:

![screenshot 2017-09-01 at 15 17 30](https://user-images.githubusercontent.com/4061923/29971519-bea97018-8f28-11e7-8c1d-1500ccb7785f.jpg)

Is is what you have in mind?

Then the open URL is just:

![screenshot 2017-09-01 at 15 18 35](https://user-images.githubusercontent.com/4061923/29971544-df6f82ec-8f28-11e7-944e-b7d5eaf50cb6.jpg)

**Comment by nikitavoloboev** [comment]
Yeah, although I wish it would be youtube, then reddit, then soundcloud, then twitter, then the rest as far as ordering goes. Not sure if Alfred learns from usage here. But that would be perfect for me. 

Thank you so much.

**Comment by nikitavoloboev** [comment]
And yeah the reddit URL looks great.

**Comment by vdesabou** [comment]
>Yeah, although I wish it would be youtube, then reddit, then soundcloud, then twitter, then the rest as far as ordering goes. Not sure if Alfred learns from usage here. But that would be perfect for me.

Yes it does ! 😄 

![screenshot 2017-09-01 at 16 47 50](https://user-images.githubusercontent.com/4061923/29975061-5f172bc4-8f35-11e7-81ae-49dfaffdf5ac.jpg)
