### ISSUE TITLE
SONOS speakers not showing up in Spotify Connect

### ISSUE THREAD

**Issue by jacoblo** [vdesabou/alfred-spotify-mini-player#207]
Spotify Connect not working for all speakers.

Works fine and can switch between MacBook and iPhone. Does however not list my other speakers (Sonos) that work fine in Spotify.

Running latest version of Spotify clients, Sonos is up to date and Mac OS X 10.12.6.

![screen shot 2017-09-08 at 10 57 22](https://user-images.githubusercontent.com/18484639/30204162-b3a086aa-9484-11e7-9dd5-4d4b8ae75f5d.png)
![screen shot 2017-09-08 at 10 57 12](https://user-images.githubusercontent.com/18484639/30204161-b39ae4f2-9484-11e7-8e87-c21562cbd9ce.png)

**Comment by vdesabou** [comment]
I'm afraid it's not working right now for Sonos devices, see https://github.com/spotify/web-api/issues/525

Nothing more I can do on my side 😢

**Comment by BasvanH** [comment]
Will this functionality be added in the future? Most needed!

**Comment by vdesabou** [comment]
> Will this functionality be added in the future? Most needed!

No idea..It's not dependant on me, it depends on SONOS/SPOTIFY

**Comment by sennl** [comment]
Is ther anything ongoing inside spotify to make it possible to discover sonos devices?
