### ISSUE TITLE
Can't find set Alfred Playlist

### ISSUE THREAD

**Issue by eferrervaughn** [vdesabou/alfred-spotify-mini-player#208]
Hello,

Just want to say your workflow is amazing. There are two things I am trying to do that I can't seem to figure out:

1. How do I set the Alfred Playlist? I don't see it in Settings or anywhere in the workflow?
2. I want to set up an Alfred Query that plays a specific playlist in shuffle mode. Then I want to call that script from another workflow. (I am trying to set up my ideal work env with one alfred query)

Thanks

**Comment by vdesabou** [comment]
> How do I set the Alfred Playlist? I don't see it in Settings or anywhere in the workflow?

Are you sure `menu_display_alfred_playlist` is set to 1:

![screenshot 2017-09-20 at 22 30 56](https://user-images.githubusercontent.com/4061923/30666098-876dddde-9e53-11e7-8749-a5cbd5e28027.jpg)

**Comment by eferrervaughn** [comment]
found it thanks!
