### ISSUE TITLE
Problems with search on russian language

### ISSUE THREAD

**Issue by Nikscorp** [vdesabou/alfred-spotify-mini-player#210]
![screen shot 2017-10-28 at 00 45 08](https://user-images.githubusercontent.com/18235332/32126478-8d8a32ec-bb79-11e7-9dea-ead344d98f37.png)

![screen shot 2017-10-28 at 00 45 18](https://user-images.githubusercontent.com/18235332/32126477-8d6de768-bb79-11e7-967c-f75b9d88a677.png)

![screen shot 2017-10-28 at 00 45 39](https://user-images.githubusercontent.com/18235332/32126474-8d502ed0-bb79-11e7-90a1-d40deac159b3.png)

So, local search fails with 3+ letters, and works fine with 2 letters in word.
Online search fails always

**Comment by vdesabou** [comment]
Can you provide the link of the playlist and copy/paste here the name you're looking for ?

I'm trying with random Russian songs and Russian characters but cannot reproduce the issue so far,  I only reproduce with Search Online.

**Comment by vdesabou** [comment]
So I've fixed the issue with Search Online, please try this BETA https://transfer.sh/ZqNlN/spotifyminiplayer-beta.alfredworkflow


Please provide the Spotify link for the track you're looking for, I can't find it

**Comment by Nikscorp** [comment]
Checked the online search – it works fine now. 

 

Recheked the local search, it works fine too, BUT it’s case sensitive.

 

To reproduce – 

try to add this album - https://open.spotify.com/album/0NQrZVFWSALt16mEk2djsn

then try to find any song in this album, typing spot_mini <artist>, where the artist is

 
Пошлая Молли (first letter uppercase)
пошлая молли (same letter lowercase)
 

Thanks a lot for so fast fix!

 

-- 

Best regards,

Voynov Nikita.

**Comment by vdesabou** [comment]
@Nikscorp What I see is that when I type 'Пош', it works:

![screenshot 2017-10-31 at 11 15 13](https://user-images.githubusercontent.com/4061923/32220232-46f77000-be31-11e7-8913-f886b417c8c1.jpg)


But not when I type 'пош'.


This is actually exactly the same problem as [here](https://github.com/ccgus/fmdb/issues/460#issuecomment-171989796)

Adding ICU support is not something trivial apparently and I'm not sure if that's even possible, so I'm afraid it will remain like this. Unless someone can help with this..

**Comment by vdesabou** [comment]
Actually, I found a solution [here](https://blog.amartynov.ru/php-sqlite-case-insensitive-like-utf8/)

Can you please try this [beta](https://transfer.sh/Fn2rd/spotifyminiplayer-beta.alfredworkflow)

**Comment by Nikscorp** [comment]
Works fine, thank you!

**Comment by vdesabou** [comment]
Leaving opened until 7.5 is released
