### ISSUE TITLE
Add more searchable results

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#213]
Nothing matches : 

![2017-11-07 at 22 39](https://user-images.githubusercontent.com/6391776/32519266-768c0642-c40c-11e7-9146-d18568422baf.png)

**Comment by nikitavoloboev** [comment]
And here : 

![2017-11-07 at 22 47](https://user-images.githubusercontent.com/6391776/32519648-b7eccf58-c40d-11e7-88ce-50a4fa478f2a.png)

**Comment by nikitavoloboev** [comment]
Also there is a bug in `show_connect` trigger, it arguments `Browse`. On the latest version.

**Comment by vdesabou** [comment]
Please try this beta that should fix everything https://transfer.sh/Ue4q9/spotifyminiplayer-beta.alfredworkflow
Let me know if that's better

**Comment by nikitavoloboev** [comment]
It doesn't open for me. 😞

**Comment by nikitavoloboev** [comment]
It downloads the workflow with .txt prepended. I remove .txt extension but loading the workflow does nothing.

**Comment by vdesabou** [comment]
strange.

try here https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v7.6-beta

**Comment by nikitavoloboev** [comment]
This worked. Thank you. 🎊

**Comment by nikitavoloboev** [comment]
There are few more fields that are not searchable that I think would be useful to search over. Searching categories : 

![2017-11-08 at 00 10](https://user-images.githubusercontent.com/6391776/32522860-44d15a00-c419-11e7-9d26-ae4f525e3ae6.png)

And searching playlists in these categories : 

![2017-11-08 at 00 11](https://user-images.githubusercontent.com/6391776/32522887-5f0fe6fc-c419-11e7-8b7f-7cb36e4dbafa.png)

**Comment by nikitavoloboev** [comment]
Here is one more (Play Queue) 🙂 : 

![2017-11-10 at 17 39](https://user-images.githubusercontent.com/6391776/32668495-1659361c-c63e-11e7-971c-4bd538bb687f.png)
