### ISSUE TITLE
Add ability to search for users and view their playlists

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#223]
In `✧Search Online▹` menu:

It would be nice if you could search for other users and on pressing `enter`, view all their public playlists.

I really hope Spotify provides API for it. Thank you.

**Comment by vdesabou** [comment]
Unfortunately, I don't think it is possible. The [Search endpoint](https://beta.developer.spotify.com/documentation/web-api/reference/search/search/) only allows to search for artists, albums, tracks or playlists, but not for user profiles.

And even though we could search for user profile, the information we can [get](https://beta.developer.spotify.com/documentation/web-api/reference/users-profile/get-users-profile/)  from a user profile does not contain their public playlist.
