### ISSUE TITLE
Current track: Cannot get current album

### ISSUE THREAD

**Issue by netromdk** [vdesabou/alfred-spotify-mini-player#226]
Hi! First of all, I really like this project. Thanks a lot. It's a bliss to use from Alfred. 👏 

When I do `spot_mini Current Track▹` it currently shows the information inside Alfred, but I get a notification with the error "Cannot get current album":
![cannot_get_current_album](https://user-images.githubusercontent.com/5989057/35512605-a48e29fa-0500-11e8-83a1-27fb65c20561.png)

The album of the current song and the artwork is displayed in Alfred btw.

I'm not really sure where your extra log info etc. is located but please tell me if necessary.

**Comment by vdesabou** [comment]
Is this happening with every album? If not can you provide an example of album for which it happens.

**Comment by netromdk** [comment]
It happens no matter what track/album it is.

**Comment by netromdk** [comment]
It doesn't write anything to the "action.log" or "spotify_mini_player_web_server.log" btw.

**Comment by vdesabou** [comment]
That's a bad bug introduced in latest release.. 😢 

You can try this BETA https://transfer.sh/fGgk0/spotifyminiplayer-beta.alfredworkflow

**Comment by netromdk** [comment]
Thanks for fixing it for future builds. I don't mind it so much so I'll just wait for next stable update. Thanks! :)
