### ISSUE TITLE
Back action

### ISSUE THREAD

**Issue by netromdk** [vdesabou/alfred-spotify-mini-player#227]
I would like to request the feature of being able to go back no matter what level of the mini player you are in. In some cases, it is easy to go back by just deleting a few words, but when going deeper into playlists and albums, the search string becomes quite long.

Either a specific shortcut or an item at the end of the list to go back, would be useful. It could perhaps be turned on/off via settings.

**Comment by vdesabou** [comment]
> This? http://alfred-spotify-mini-player.com/articles/back-button/
-- 
Vincent de Saboulin

**Comment by netromdk** [comment]
Ah! That is perfect. Thanks!
