### ISSUE TITLE
Search Online with album does not display correct artist names for compilation

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#228]
From a user:

For some reason it thinks all tracks on this album are by Keeno until I start playing them. It’s a compilation starring lots of different artists (Keeno being one of them) for clarification.

<img width="593" alt="screen_20180201_234644" src="https://user-images.githubusercontent.com/4061923/35732662-9d0d608e-081a-11e8-935f-9e540dc041e0.png">

**Comment by disrupted** [comment]
https://github.com/vdesabou/alfred-spotify-mini-player/commit/09333a01a9eabd72dd5a4ab66eb3b45b82f3472a fixed the issue.
