### ISSUE TITLE
Feature Request: Thumbs Up or Down a Song being Played by a Radio Station

### ISSUE THREAD

**Issue by jasondm007** [vdesabou/alfred-spotify-mini-player#229]
It would be great if the workflow allowed people to "thumbs up" or "thumbs down" a song that is currently being played by a Radio station. This would save people a ton of time. Thanks & Love the Workflow!!

![screen shot 2018-02-05 at 11 32 28 am](https://user-images.githubusercontent.com/14279767/35824740-af631ddc-0a68-11e8-9c53-a081a212f6e0.jpg)

**Comment by vdesabou** [comment]
Unfortunately, this is technically impossible, see Thumb up Currently Playing Song #201
