### ISSUE TITLE
Add create playlist option

### ISSUE THREAD

**Issue by leegenes** [vdesabou/alfred-spotify-mini-player#235]
Would be nice to have the option to create a playlist.
Use: 
* sometimes hear a song that makes me realize it would be great to have a playlist based on that that isn't generated by Spotify
* Current Track > Add to Playlist > Create playlist [at bottom or top of options] 
  - creates playlists and adds current selection as first song/s in playlist

Not great with php, but if this is something you'd consider, I don't mind trying to add it in for you.

**Comment by vdesabou** [comment]
I think it is already there:

![screenshot 2018-02-17 at 17 38 07](https://user-images.githubusercontent.com/4061923/36343203-700847ca-1409-11e8-982c-9ea3bab27f64.jpg)

![screenshot 2018-02-17 at 17 38 16](https://user-images.githubusercontent.com/4061923/36343204-72d7514e-1409-11e8-9bea-a8744f84a707.jpg)


![screenshot 2018-02-17 at 17 38 25](https://user-images.githubusercontent.com/4061923/36343206-756dea9e-1409-11e8-9965-a384817f056c.jpg)


![screenshot 2018-02-17 at 17 38 38](https://user-images.githubusercontent.com/4061923/36343207-77f3a6fa-1409-11e8-9f3f-4fe23e44c9c2.jpg)

**Comment by vdesabou** [comment]
Closing...
