### ISSUE TITLE
Unable to browse playlists

### ISSUE THREAD

**Issue by anuragarora** [vdesabou/alfred-spotify-mini-player#238]
I go to search online> Search for playlists only>type search query >press enter on a result

When I press enter on a result nothing happens the Alfred window just closes. I have tried to reset settings and searching forums but nothing has worked so far to give me a hint what is wrong here.

Also, I am not able to browse playlists at all. Even in browse functionality > categories when I reach the playlist stage and press enter, the playlist doesnt open to show items....

**Comment by vdesabou** [comment]
Thanks for reporting this. It's fixed in version 7.10 which is now out !
