### ISSUE TITLE
Problem with online playlist with emoji in its name

### ISSUE THREAD

**Issue by setegonz** [vdesabou/alfred-spotify-mini-player#240]
I'm still having problems to play a playlist that I don't have in my library.

**Comment by vdesabou** [comment]
Are you using version 7.10?

Please follow steps in http://alfred-spotify-mini-player.com/articles/support/ to send me debug ZIP file

**Comment by setegonz** [comment]
I sent you the file. Thanks!

**Comment by vdesabou** [comment]
Nothing in the logs..

Can you explain in details (with screenshots if needed) what you're doing, and what you get?

**Comment by setegonz** [comment]
I'm trying to play spot_mini Online Playlist▹spotify:user:nahueexequiel:playlist:7hvZRtqPO5Pc1kjAbknkOs∙Trap Latino LO ULTIMO🔥▹ and this is what I'm getting:
![c674d755-7c65-4231-9215-38649b2a05e0](https://user-images.githubusercontent.com/11341688/36743257-982243e8-1bc8-11e8-85d3-1af8324c9fc5.png)

**Comment by vdesabou** [comment]
Can you try this BETA https://transfer.sh/hLV4w/spotifyminiplayer-beta.alfredworkflow

It should fix the problem

**Comment by setegonz** [comment]
Works perfectly!
