### ISSUE TITLE
Search for X in Spotify doesn't work when X is a non-latin

### ISSUE THREAD

**Issue by vinceau** [vdesabou/alfred-spotify-mini-player#245]
When a search fails to return any results 3 options are presented:
1. No results found (non-actionable)
2. Search for X in Spotify
3. Search for X online

When option 2 is selected and X is non-latin (I've tested Korean, Japanese, and Chinese but I imagine this list is non-exhaustive), no results are found instead "Recent Searches" is shown.

**Comment by vdesabou** [comment]
Hi,

Can you try to install and test with this [beta](https://transfer.sh/SqkMN/spotifyminiplayer-beta.alfredworkflow)

**Comment by vinceau** [comment]
Japanese (Hiragana, Katakana, Kanji) and Chinese both seem to be working now in the beta. However, Korean is still broken but instead of showing "Recent Searches" it says "No results found for X" even though when you manually search for X in the search bar, you get results.

**Comment by vdesabou** [comment]
Can you copy/paste a Korean artist/song here so that I can reproduce ?

**Comment by vinceau** [comment]
You can try with: "아이유" a Korean artist, and "사랑해요" a common song name.

**Comment by vdesabou** [comment]
Sorry for late reply. I think it should be fixed with this beta now : https://transfer.sh/Uzbcu/spotifyminiplayer-beta.alfredworkflow

Let me know

**Comment by vinceau** [comment]
Yup, that fixes it! Thanks a lot!
