### ISSUE TITLE
feature request: check if song in playlist/my music

### ISSUE THREAD

**Issue by mickaelperrin** [vdesabou/alfred-spotify-mini-player#247]
Hi,

Thanks for your awesome workflow.

Your work is maybe more awesome than you think 😆 As it provides a lot of apple script entries, it can be used inside the awesome Better Touch Tool project.

I would like to create an apple script to add/remove songs to a favorite list but currently, there is no helper to check if a song belongs to a specific playlist.

You have written the code which does this check in the management of add/remove songs to playlist, that would be awesome to refactor it and provide an apple script interface.

Thanks

👍

**Comment by vdesabou** [comment]
Thanks !

I do not fully understand what you need. It would be good if you provide an example
Did you see the "add_current_track_to" command (it can be called with AppleScript)? It should open Alfred and propose to add current track in one of your playlists

**Comment by mickaelperrin** [comment]
Forget about it, I dived into the code and it needs some important changes. I extracted some piece of your libraries to get it working as an external independant thing.
