### ISSUE TITLE
Ability to like/dislike recommended/discover weekly tracks

### ISSUE THREAD

**Issue by jdeck398** [vdesabou/alfred-spotify-mini-player#248]
Hey Vincent, any chance liking/disliking a track (like when listening to discover weekly or recommended tracks) is coming to the spotify mini player? Thanks!

**Comment by vdesabou** [comment]
Hi,

Unfortunately, there is no API for that, see https://github.com/spotify/web-api/issues/710
If Spotify decides to add it in the future, I'll add it for sure !

**Comment by jdeck398** [comment]
Ah too bad. Appreciate the follow up!
