### ISSUE TITLE
refresh_token must be supplied

### ISSUE THREAD

**Issue by allenmanning** [vdesabou/alfred-spotify-mini-player#249]
After selecting a playlist spotify starts up, but an exception is thrown afterwards.

`refresh_token must be supplied`

**Comment by vdesabou** [comment]
Please send me an email with zip file as described here
http://alfred-spotify-mini-player.com/articles/support/
-- 
Vincent de Saboulin

**Comment by vdesabou** [comment]
Hello,

So your settings.json file is corrupted (missing a lot of information).
I suggest you use « spot_mini_reset_settings »  command:

It will delete the file and recreate a default one. Then next time you open the workflow, you’ll need to do authentication process again, but you will not need to re-create your library.

That should fix your problem.

Keep me posted
Cheers

**Comment by vdesabou** [comment]
It fixed the issue.
