### ISSUE TITLE
"This site can’t be reached" http://localhost:15298/callback.php

### ISSUE THREAD

**Issue by 0xdevalias** [vdesabou/alfred-spotify-mini-player#254]
Following the [setup instructions](http://alfred-spotify-mini-player.com/setup/), I correctly set up the application, add the client id/secret, and get to the redirect from Spotify oauth.

At this point I end up on a "This site can’t be reached" screen. No output in the logs, etc.

```
⇒  which php
/usr/bin/php

⇒  php --version
PHP 7.1.16 (cli) (built: Mar 31 2018 02:59:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

It definitely appears to support the `-S` flag, as I saw mentioned in another issue thread here:

```
⇒  php -S localhost:15298
PHP 7.1.16 Development Server started at Fri Sep  7 14:05:54 2018
Listening on http://localhost:15298
Document root is REDACTED
Press Ctrl-C to quit.
```

So my guess is it's just not being started for whatever reason? Any thoughts?

**Comment by vdesabou** [comment]
Can you please follow steps [here](http://alfred-spotify-mini-player.com/articles/support/) to send me the ZIP file (using **spot_mini_debug** command) by email.

It will contain the logs for the PHP server, hopefully that will help

**Comment by 0xdevalias** [comment]
Will send through the debug email, but not much of interest in the log:

```
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

**Comment by vdesabou** [comment]
Nothing useful in logs indeed..

The usual suspects are:

- Problem with extensions:

Warning: If you have troubles with authentication using Chrome, make sure you disable Wappalyzer extension if you use it, or use Safari as default browser for the time of authentication process.

- If you have this option enabled :

![setup6](https://user-images.githubusercontent.com/4061923/45253904-b177e800-b36e-11e8-9803-02ac40551d32.jpg)

Try to disable it during the time of authentication

**Comment by 0xdevalias** [comment]
Disabled Wappalyzer, worked straight away. Have also rebooted since the first issue (and didn't confirm before disbling the extension). So I expect one of the two probably resolved this.

Might be worth adding the wappalyzer/etc suggestions above to the 'issues' FAQ if not already there?

Thanks

**Comment by vdesabou** [comment]
Ok thanks for the feedback. It was already mentioned in setup but I've added some notes in http://alfred-spotify-mini-player.com/known-issues/
