### ISSUE TITLE
Add ability to save currently playing song 'share link' to clipboard

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#255]
I often like to share songs I listen to on Twitter or send to friends. I would love to have an action I can bind to external trigger which when ran will put a share link of currently playing song to my clipboard.

Like this one:

https://open.spotify.com/track/60st6t4q5jvd7nKBgoVlgm?si=m5bjZ0lxSi2ytnYSDbCpJA

Thank you.

**Comment by vdesabou** [comment]
Yes I can add that..

Currently, you can CMD-C on Current track, on first item:

![screenshot 2018-09-07 at 16 16 31](https://user-images.githubusercontent.com/4061923/45224135-7f587e80-b2b9-11e8-9040-a33caf4f1b39.jpg)

And it will put in the clipboard:

#NowPlaying Be With Me by Patrice https://open.spotify.com/track/5L1t1L1aLXWE4GElZZC4eJ

I'll add an external trigger for you

**Comment by nikitavoloboev** [comment]
I just need the URL though. Because Twitter already expands title and artist name. Thank you. 🙂

**Comment by vdesabou** [comment]
Can you try this [beta](https://transfer.sh/MGJCX/spotifyminiplayer-beta.alfredworkflow) ?

I've added an external trigger _copy_current_track_url_to_clipboard_ 

![screenshot 2018-09-11 at 11 33 40](https://user-images.githubusercontent.com/4061923/45351463-8b448900-b5b6-11e8-8e4d-a01156499ad9.jpg)

Let me know if that works for you

**Comment by nikitavoloboev** [comment]
Works perfectly for me. Thank you.

**Comment by vdesabou** [comment]
Ok cool. 
I'm leaving it open until I release 7.16
