### ISSUE TITLE
Can not connect http://localhost:15298

### ISSUE THREAD

**Issue by duxiaodou** [vdesabou/alfred-spotify-mini-player#258]
When I authenticate, the web browser open a new tab, but can not visit

macOS 10.13.6
PHP 7.1.16 (cli) (built: Mar 31 2018 02:59:59) ( NTS )

**Comment by vdesabou** [comment]
Did you see these notes on the [setup](http://alfred-spotify-mini-player.com/setup/) page:

![screenshot 2018-09-14 at 10 31 35](https://user-images.githubusercontent.com/4061923/45539249-6f84f100-b809-11e8-8216-7bf01b2f1bd1.jpg)

Male that's your issue ?

**Comment by duxiaodou** [comment]
I am not using any proxy

**Comment by vdesabou** [comment]
ok..
What do you see exactly? Do you see the page where you need to login with Spotify and give access to the workflow?
What about your browser? Is it Chrome or Safari? What extensions are installed?
Also use the spot_mini_debug keyword input and use _Send an email to the author option_. This will generate an email with all information needed for troubleshooting.

**Comment by vdesabou** [comment]
It’s so nice of you to close the issue without any explanation, no thank you, nothing..
First time I see this in years of supporting this workflow
