### ISSUE TITLE
Use file.io instead of transfer.sh as it is closing

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#262]

**Comment by vdesabou** [comment]
See alternatives here https://github.com/dutchcoders/transfer.sh/issues/116

**Comment by clemisch** [comment]
Sadly file.io is slow :( Caps at 1 MB/s upload for me

**Comment by vdesabou** [comment]
I've moved back to transfer.sh anyway as it is not closing :)

**Comment by clemisch** [comment]
For me it has been unreliable for the last weeks, not working more often than not (from Germany).
