### ISSUE TITLE
How to stop notifications showing for currently playing songs?

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#263]
These ones

![2018-11-04 at 16 44](https://user-images.githubusercontent.com/6391776/47966286-f9ef1180-e050-11e8-918c-40ca1517c178.png)

**Comment by vdesabou** [comment]
Have a look here
http://alfred-spotify-mini-player.com/articles/now-playing/
-- 
Vincent de Saboulin

**Comment by nikitavoloboev** [comment]
thanks
