### ISSUE TITLE
Feature request: repeat one 

### ISSUE THREAD

**Issue by fedterzi** [vdesabou/alfred-spotify-mini-player#264]
Hi @vdesabou,

Thanks for the awesome workflow. 

Would it be possible to add support for "repeat one" (repeating the same song over and over again)?

Thanks

**Comment by vdesabou** [comment]
Hi !

Yes it is possible but only when using Spotify Connect, see details [here](https://github.com/vdesabou/alfred-spotify-mini-player/issues/122#issuecomment-395384902)
