### ISSUE TITLE
alfred-spotify-mini-player across multiple logins - library not building

### ISSUE THREAD

**Issue by johnathanz** [vdesabou/alfred-spotify-mini-player#266]
First of all, great workflow.

I have 2 separate logins on my Mac. The workflow worked the first time with login no. 1. But I can't get past the following dialog when setting up spotify-mini on login no. 2.

![screen shot 2018-11-13 at 7 31 57 am](https://user-images.githubusercontent.com/1593039/48373594-5c61a500-e716-11e8-8865-0c54622da11c.png)

Authentication succeeds, but it never proceeds to build the library.

I tried setting up a separate application on Spotify for login #2, but spotify-mini always goes to the same Application (guessing it's the callback URL used??)

Has anyone done this before?

**Comment by vdesabou** [comment]
Hello,

By login, I'm assuming you're talking about OSX user accounts, right ? Not Spotify accounts ?

I'm using completely separate directories for each OSX user account so that should not be an issue.

You're saying that Authentication succeeds, so when you invoke the workflow again, you should see a message like "Create Library", right ? What happens when you execute it ?

Also, please provide a DEBUG zip file by executing ```spot_mini_debug``` command, as explained here http://alfred-spotify-mini-player.com/articles/support/

That will help to see what's happening

**Comment by johnathanz** [comment]
Login as in Mac login yes.

For Login no. 1 yes. I get "Create Library", it then goes to download playlist, album art etc.

For Login no 2. After successive Authentication, there are no "Create Library" message on successive invocation. It's always the same screen that I posted ☝️ 

Debug zip 👇 

[spot_mini_debug.zip](https://github.com/vdesabou/alfred-spotify-mini-player/files/2575798/spot_mini_debug.zip)

Thanks!

**Comment by vdesabou** [comment]
I can see in logs:

```
[Tue Nov 13 00:20:14 2018] Failed to listen on 127.0.0.1:15298 (reason: Address already in use)
```

It might be the other account still using that port, but normally it should not happen

You can try to reboot your computer, to free the TCP port.
If you can't, then try to find which process is using that port:

Example:

```
netstat -an | grep 15298
```

**Comment by vdesabou** [comment]
Also, I can see in logs:

```
Warning: copy(/tmp/tmp): failed to open stream: Permission denied in /Users/johnathan/Dropbox/MySettings/Alfred_v3_settings/Alfred.alfredpreferences/workflows/user.workflow.20B45231-31A4-4012-BB89-330F022F4488/src/functions.php on line 4740
```

This is not related to your problem but you will have an issue with notifications as the workflow can't write in /tmp/tmp
This is most probably because it is used by your other login. I'll create another issue and fix it in next release

**Comment by vdesabou** [comment]
Ok thanks for the feedback, much appreciated.

For your notification issue (see #267), please download and install this BETA https://file.io/YIGbzD
That should fix the notifications not showing up artworks

**Comment by vdesabou** [comment]
Yes, use this link instead
