### ISSUE TITLE
Disable notification not available

### ISSUE THREAD

**Issue by johnathanz** [vdesabou/alfred-spotify-mini-player#268]
I'm trying to disable the "Now Playing" notification. Good documentation on http://alfred-spotify-mini-player.com/articles/now-playing/

Unfortunately I can't find this in settings: 
![screen shot 2018-11-14 at 11 59 11 am](https://user-images.githubusercontent.com/1593039/48452799-cb1d2c00-e804-11e8-9a63-e2bc983b5f49.png)

Nor is "Spotify Mini player" listed under Mac Notification settings:
![image](https://user-images.githubusercontent.com/1593039/48452851-061f5f80-e805-11e8-8208-c23fe2f049a5.png)

Any idea what I'm doing wrong?

**Comment by vdesabou** [comment]
I think you just need to scroll down in the menu, it's after "Select the output":

![screenshot 2018-11-14 at 09 40 06](https://user-images.githubusercontent.com/4061923/48470304-58568580-e7f1-11e8-9e38-7d29778c2791.jpg)

**Comment by vdesabou** [comment]
For second problem, you can try to do this:

Call spot_mini_debug and choose "Browse to Alfred Workflow folder"

![screenshot 2018-11-14 at 09 46 57](https://user-images.githubusercontent.com/4061923/48470771-9bfdbf00-e7f2-11e8-83e7-b97312eb917c.jpg)

Then in Finder, go to App/Green/ and then double click Spotify Mini Player app. It should just open desktop application, but it might force the app to be in Notifications settings

Do you see "alerter" in settings?

![screenshot 2018-11-14 at 09 51 26](https://user-images.githubusercontent.com/4061923/48470864-eb43ef80-e7f2-11e8-8adb-7347d0f52ee3.jpg)
