### ISSUE TITLE
Non connexion to SPOTIFY, tried 2 times

### ISSUE THREAD

**Issue by antoinecodquebert** [vdesabou/alfred-spotify-mini-player#274]
<img width="1086" alt="capture d ecran 2019-02-26 a 17 59 21" src="https://user-images.githubusercontent.com/48026937/53431453-dd585a00-39f0-11e9-82e8-55e23fa823dd.png">

**Comment by vdesabou** [comment]
Are you sure you clicked save button as explained [here](http://alfred-spotify-mini-player.com/setup/)

> Warning: Make sure you’ve clicked Save button once you set the Redirect URI

**Comment by vdesabou** [comment]
I assume it was the issue, hence I'm closing the ticket
