### ISSUE TITLE
Authentication not working due to wrong php version

### ISSUE THREAD

**Issue by sander-p** [vdesabou/alfred-spotify-mini-player#275]
I'm trying to authenticate with Spotify, but this results in the error message "PHP 5.4.0 or later is required for authentication."

This is on a brand new Mac mini, running 10.14.3. The default php version is of course much higher: 7.1.23, so I'm guessing something else is going on. Any clues?

**Comment by vdesabou** [comment]
what's the workflow version you're using ? Is that 7.19 ?

This is supposed to be fixed since a long time, see Installation failure on 10.13 #192

**Comment by sander-p** [comment]
Oops... I'm still on 7.0, it turns out. Sorry! I should have thought of that myself. I'll upgrade straightaway.

**Comment by sander-p** [comment]
That solved it, of course. Thanks for the very quick response!
