### ISSUE TITLE
Add a way to search current song instantly on Reddit/YouTube from external trigger

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#277]
Reddit and YouTube are the only two services I use to search currently playing song on the web. Currently I do it through this window:

![2019-03-15 at 14 09](https://user-images.githubusercontent.com/6391776/54433381-00427800-472c-11e9-80fe-879dd4b18d74.png)

But it takes about 2-3 seconds for it to appear and then I have to pick the result.

I would love if I could have a way to bind a search of current song to Reddit and YouTube as external trigger so that search is done instantly.  Perhaps this is possible to do already?

And if not, I would love to have it added. 🧡

**Comment by vdesabou** [comment]
This will be available in 7.20:

![ScreenShot 2019-03-20 at 08 54 23](https://user-images.githubusercontent.com/4061923/54668289-d5bb3b00-4aee-11e9-8307-e00787dc86b2.jpg)
