### ISSUE TITLE
404 when adding to non-Alfred playlist

### ISSUE THREAD

**Issue by leegenes** [vdesabou/alfred-spotify-mini-player#278]
Adding a track to a playlist that is not my Alfred Playlist causes a 404. Tried to send email report with bug report .zip, but don't have a default email application setup - as an aside, might be good to offer a modifier to copy the mailto link for those who use a browser as their default mail client - can get the debug file, and send. Will go look for those.

Failure case:
1. spot-mini to get current track
2. select add to playlist
3. select playlist
4. get desktop notification with 404 message "Invalid playlist id", redirected to sending email in Alfred

OS: 10.14.3
no workflow update available

edit: selecting the "Alfred Playlist," but from the list of all playlists also fails, while choosing the Alfred Playlist option is working as expected

**Comment by vdesabou** [comment]
Actually, when you generate the ZIP file, you should have after the text of the email in your clipboard 
For this kind of issue, I'd need this ZIP file to troubleshoot, can you send me the email to alfred.spotify.mini.player AT gmail DOT com with the text in clipboard ?

Thanks

**Comment by vdesabou** [comment]
You are using a very old version (7.7) of the workflow. Please download latest one 7.20 and recreate your library.
Spotify has changed playlist uri, I believe your problem is caused by that

Keep me posted please

**Comment by leegenes** [comment]
I'll give that a try. I just grabbed an old machine I very rarely use, and that was on an even older version. Updating from the workflow offered an update to 7.2, but nothing later than that.

**Comment by leegenes** [comment]
Ignore me. That said 7.20, not 7.2. Not sure why the update wasn't being suggested in the workflow for me on that machine, but I was just able to get it updated. Thanks.
