### ISSUE TITLE
Authentication Error 

### ISSUE THREAD

**Issue by tiredoak** [vdesabou/alfred-spotify-mini-player#280]
I followed the tutorial and:
1. Pasted the Client Secret
2. Pasted the client ID
3. Selected authenticate with Spotify
4. Authenticated and was redirected to an error message

`There was an error during the authentication (exception SpotifyWebAPI\SpotifyWebAPIException: Server error. at SpotifyWebAPI.Request.parseBody(Request.php:39) at SpotifyWebAPI.Request.send(Request.php:235) at SpotifyWebAPI.Request.api(Request.php:114) at SpotifyWebAPI.SpotifyWebAPI.me(SpotifyWebAPI.php:1338) at (main)(callback.php:30))`

URL: http://localhost:15298/callback.php?code=AQChl5ZpVnk68U8mGG-WbV05W80Jei6L9bfugqXiFt_LdSlsPsIjR6I9cDsBhY3pI9WXGm1TFtHVZzDKmFX-EbmSV3ZUoHeq_V_5hCzsbQgtcJE3t76qFPENKGe4lSUdpj8Ck9RXkSk67wL6Clon7v-_k6H8CiXmbbCKpsOsZappENZYBBCfbAiIJjXfmLmRMu5xpiAJIRQM7m7PrPsH87T9xqf9P-Ci63l9NzumpmzI2UZJZFR8e2eT4iTnmLOv6IqWfKyP8WOmiBWB2vKt4VrX97Jz0aWPkXhGL66ZCDjFDIwKAv5yoy-_EjChuRt3JnBoLm41m_EXzlgWgJKTVYK4pomClioMj5H8z_EACd5t_ZDJRI4YY_oja9JxOlK0iyRethyAUTPLrP0-sYrdsj0LNYfPWvg9Th5YQj_9Cub28Kahh_pzSdronbRtt9Ur9X1k3nZiD5SiyXtb64kz039QlQ52qWoAL7GGc5bdJWyfBt2NG_wyG5q7Tx2VaXExESrIGMRzN4ACAgFVBJlP3DvofH-hGQDdN4pefXUAHgOov_d-H31rhSDSsOInzcp5-UoGfdk24-EhNyGV0hFycU6uUta4sxZOZ43f2q-9YR3GHLBxVCos5EokTPetdIXyzpkK_lvuvh6TrBxs0u6J

**Comment by vdesabou** [comment]
Seems like a temp issue on Spotify server side. What happens if you retry ?

**Comment by vdesabou** [comment]
any feedback ?

**Comment by tiredoak** [comment]
Sorry! That solved it, thank you :)
