### ISSUE TITLE
Automatically run refresh_library once a day or based on custom schedule

### ISSUE THREAD

**Issue by kaiky25** [vdesabou/alfred-spotify-mini-player#281]
The title says it all. What do you guys think about it?

**Comment by vdesabou** [comment]
You can do it using crontab

This is how I'm using it:

```0 */6 * * * osascript -e 'tell application "Alfred 3" to run trigger "refresh_library" in workflow "com.vdesabou.spotify.mini.player" with argument "test"'```

article on how to use it http://benr75.com/pages/using_crontab_mac_os_x_unix_linux

**Comment by kaiky25** [comment]
Thank you vdesabou!

I though about using crontab but was looking for something more "integrated" to Alfred's environment, maybe a settings option. I guess Alfred workflows are not that extensive? Anyhow, will add that scheduled task.

**Comment by vdesabou** [comment]
No there is nothing in Alfred to do that, but that’s why they provided external triggers like that, in order to be able to execute workflows from outside, like with crontab for example
