### ISSUE TITLE
Shortcut / Hotkey for searching in Spotify

### ISSUE THREAD

**Issue by QuinnTorres** [vdesabou/alfred-spotify-mini-player#282]
Since there is no ability to queue a song, the second best option would be to open a search for a song in Spotify and then queue it there. However, it seems like the only way to "Search for ... in Spotify" is to select the option in the list of search results.

Is there a hotkey to immediately search for a query in Spotify instead of showing results and the option to search online, or a keyword to enter beforehand, or an easy way to edit the workflow to do so?

**Comment by vdesabou** [comment]
I've added this:

![Screenshot 2019-06-04 at 09 24 17](https://user-images.githubusercontent.com/4061923/58859705-b7ef8200-86aa-11e9-87e0-747a45d92fa4.png)

It will display the current track in Spotify Desktop (even if you use Spotify Connect)

Is that what you were looking for ?

Here is a link to the beta if you want to try: https://transfer.sh/12QusW/spotifyminiplayer-beta.alfredworkflow
