### ISSUE TITLE
Spotify setup failing

### ISSUE THREAD

**Issue by outdoorslover** [vdesabou/alfred-spotify-mini-player#286]
Hi there,

I'm sure that I'm just a dumb ass, but I can't get the mini-player setup to work as it's documented. Per the instructions, I invoke using 'spot_mini', and scrolled down to 'Your Application Client ID is Missing', press enter and paste the client ID (as copied from Spotify's dashboard). When I re-invoke Alfred 4 and enter 'spot_mini', I don't see an option to 'Authenticate with Spotify'. What am I doing wrong? I try the Reset, but that didn't do anything either.

<img width="577" alt="Screen Shot 2019-05-30 at 4 08 54 PM" src="https://user-images.githubusercontent.com/51216353/58671835-e52de000-82f8-11e9-82ea-e2f1dac03ba3.png">
<img width="579" alt="Screen Shot 2019-05-30 at 4 10 31 PM" src="https://user-images.githubusercontent.com/51216353/58671836-e52de000-82f8-11e9-9e5e-e3e166710c0c.png">
<img width="585" alt="Screen Shot 2019-05-30 at 4 38 51 PM" src="https://user-images.githubusercontent.com/51216353/58671991-9a609800-82f9-11e9-99eb-607b1090a804.png">

Thanks!

**Comment by vdesabou** [comment]
Here is a link to an "Alfred 4 only" version: https://transfer.sh/TLlch/spotifyminiplayer-beta.alfredworkflow

Let me know if you still get issues

**Comment by vdesabou** [comment]
Duplicate #284
