### ISSUE TITLE
Illegal scope after trying to authorize

### ISSUE THREAD

**Issue by ramirez** [vdesabou/alfred-spotify-mini-player#287]
Using Alfred 3.0, after following the authorization tutorial, I always end up with a browser window with "Illegal scope" on it.

**Comment by vdesabou** [comment]
Yes apparently this is a Spotify issue, see
https://github.com/spotify/web-api/issues/1262

Nothing I can do on my side I’m afraid.
Having said that I tried this morning and it worked for me.
Maybe an intermittent issue ?

> --
Vincent de Saboulin

**Comment by MSBoone5** [comment]
In order to workaround this, I had to remove the `user-top-read` scope from the url. This scope allows you to read the 'Top Artists' and 'Top Picks' for your account. I'm not sure how this will effect usability, but we'll see. 🤷‍♂

**Comment by vdesabou** [comment]
@MSBoone5 it should break « only » this feature : http://alfred-spotify-mini-player.com/articles/your-tops/

**Comment by jlsepulveda** [comment]
> In order to workaround this, I had to remove the `user-top-read` scope from the url. This scope allows you to read the 'Top Artists' and 'Top Picks' for your account. I'm not sure how this will effect usability, but we'll see. 🤷‍♂ (This is with Alfred 4)

It worked for me, Thanks !!!

**Comment by bfile49** [comment]
In order to workaround this, I had to remove the user-top-read scope from the url.

**Comment by lumilikha** [comment]
> In order to workaround this, I had to remove the `user-top-read` scope from the url. This scope allows you to read the 'Top Artists' and 'Top Picks' for your account. I'm not sure how this will effect usability, but we'll see. 🤷‍♂ (This is with Alfred 4)

Hi! Where can this url be found? How do I edit?

**Comment by vdesabou** [comment]
@lumilikha In the URL when you are on this page:

![Screenshot 2019-06-08 at 08 44 06](https://user-images.githubusercontent.com/4061923/59143280-aa4b3c80-89c9-11e9-802f-74616df3cc33.png)

To all, you can maybe comment on the GitHub issue https://github.com/spotify/web-api/issues/1262 in order to have Spotify fixing the problem

**Comment by Stevenchaosz** [comment]
Where can this url be found?

**Comment by vdesabou** [comment]
@Stevenchaosz I've just explained it in my previous comment, to get on the page, see http://alfred-spotify-mini-player.com/setup/

**Comment by Stevenchaosz** [comment]
I am sorry. But all I see during the authentication is the page with "Illegal scope." Is it somewhere I missed in the setup process?

**Comment by vdesabou** [comment]
For those impacted by this issue (and until Spotify fixes the problem), download and install this [version](https://transfer.sh/iEjNf/spotifyminiplayer-beta.alfredworkflow)

Note: the "Your Top" feature will not work with this version

**Comment by bumpux** [comment]
Solved the illegal scope issue for me w/ Alfred 4.

**Comment by axelperschmann** [comment]
Is the bug fixed version still downloadable somewhere?
Thanks!

**Comment by vdesabou** [comment]
> > For those impacted by this issue (and until Spotify fixes the problem), download and install this [version](https://transfer.sh/iEjNf/spotifyminiplayer-beta.alfredworkflow)
> > Note: the "Your Top" feature will not work with this version
> 
> Is the bug fixed version still downloadable somewhere?
> Thanks!

I've updated the link, it should work now

**Comment by typemoe** [comment]
> > In order to workaround this, I had to remove the `user-top-read` scope from the url. This scope allows you to read the 'Top Artists' and 'Top Picks' for your account. I'm not sure how this will effect usability, but we'll see. 🤷‍♂ (This is with Alfred 4)
> 
> Hi! Where can this url be found? How do I edit?

Quick dirty & easy way to fix:
1. Goto Alfred preference -> workflows
2. Right-click on this workflow, then select "open in finder". 
3. Right in this folder, you should see index.php. Comment out the line containing 'user-top-read' and you're good to go.

**Comment by vdesabou** [comment]
Apparently for those impacted, you can also try to remove your App in [Spotify dev website](https://developer.spotify.com/my-applications) and create a new one. Then you can call `spot_mini_reset_settings`to do the auth process again with your new App credentials.

**Comment by vdesabou** [comment]
This is now fixed on Spotify side, see last [comment](https://github.com/spotify/web-api/issues/1262#issuecomment-511206677)
