### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by actualmonkey** [vdesabou/alfred-spotify-mini-player#288]
Hello. Everything was working fine and now it is just not. It has stopped creating in the midst of creating the library. It will not play or stop playing. It seems to no longer be interacting with Spotify app. I tried to reset settings and re-installing, but this does not help.. What should I try next...

**Comment by actualmonkey** [comment]
I also tried to "kill update library" but this did not work either....

**Comment by vdesabou** [comment]
Are you using Alfred 4?

**Comment by actualmonkey** [comment]
YES! Did that screw me!

**Comment by vdesabou** [comment]
There is a release available for those who have upgraded to Alfred 4, see #284 for the link
