### ISSUE TITLE
Spotify Playlists

### ISSUE THREAD

**Issue by raidiant** [vdesabou/alfred-spotify-mini-player#29]
When updating my library it adds all the songs, albums and artists but the playlists that are not published won't get added. The playlist from users other than myself are.

I believe I had no problems till 5.0

**Comment by raidiant** [comment]
I'm having the same issue again, every time my playlists update it won't go past my first 27 playlists, re-creating the library will go past 27 playlists. I've taken the liberty to already generate a debug.tgz file ;) https://www.dropbox.com/s/s67ql1qo7k05t7q/spot_mini_debug.tgz?dl=0

**Comment by vdesabou** [comment]
>I'm having the same issue again, every time my playlists update it won't go past my first 27 playlists, re-creating the library will go past 27 playlists. I've taken the liberty to already generate a debug.tgz file ;) https://www.dropbox.com/s/s67ql1qo7k05t7q/spot_mini_debug.tgz?dl=0

Good initiative :)
So yes, there are problems in version 5.2, and you're having one of them..
But the good news is that I've been working hard on the next version (6.0) which will be released very very soon (before end of the week if all is ok)

Using version 6.0, I had no problem creating your library:

![tmp](https://cloud.githubusercontent.com/assets/4061923/5899098/3d439142-a557-11e4-8c8e-8b509659358d.png)

So I suggest you wait for version 6.0, if you want to have a look at new features, you can see it here http://alfred-spotify-mini-player.com

**Comment by raidiant** [comment]
Ah nice one! Looking forward to it :)
