### ISSUE TITLE
GitHub "Release" version 8 download is version 7.20

### ISSUE THREAD

**Issue by justrhysism** [vdesabou/alfred-spotify-mini-player#292]
Just installed v8.0 (thank you!); however noticed that the version listed in Alfred's preferences lists v7.20.

Pretty minor... but I found myself uninstall and reinstalling several times because of this.

**Comment by vdesabou** [comment]
That's weird, I see this:

![Screenshot 2019-06-07 at 13 10 59](https://user-images.githubusercontent.com/4061923/59100247-c09fbc80-8925-11e9-97f6-7238660b3d61.png)

**Comment by justrhysism** [comment]
@vdesabou when I download the version from the Releases page, inspecting the package at `~/packal/package.xml` it still has the version at `7.20`.

Also downloading this version, I don't appear to be getting the fixes for Alfred 4; so my only conclusion is the version from the releases page isn't actually version 8.

**Comment by justrhysism** [comment]
Aha, downloaded the version from the website (via the download button) and I now have the correct version.

I'll change the title of this issue.

**Comment by vdesabou** [comment]
@justrhysism Thanks for reporting this. This is now fixed
