### ISSUE TITLE
copy_current_track_url_to_clipboard stopped working

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#295]
Workflow ver. 8.0
Alfred ver. 4.0.2

The action doesn't actually do anything now.

**Comment by vdesabou** [comment]
that's weird, it is still working for me.
I'm using the function described [here](https://stackoverflow.com/questions/29181038/how-to-copy-string-to-system-clipboard-with-php-which-runs-as-client-side)

Did you try a reboot by any chance ?

**Comment by nikitavoloboev** [comment]
Ok I fixed it. I just called it indirectly with KM macro:

![2019-06-29 at 16 31](https://user-images.githubusercontent.com/6391776/60386334-6957bc80-9a8b-11e9-86c2-bc6c109613ea.png)

And needed to change Alfred 3 to Alfred 4
