### ISSUE TITLE
Workflow Incompatible with Alfred v3

### ISSUE THREAD

**Issue by jannismain** [vdesabou/alfred-spotify-mini-player#297]
Alfred: v3.8.2 [963]
Spotify Mini Player: Updated to v8.1

![image](https://user-images.githubusercontent.com/14290527/60431538-5286a680-9c00-11e9-99f0-ddc9036f4e81.png)

Will you stop supporting v3 or is this a bug?

**Comment by vdesabou** [comment]
Yes this is a bug, I'll upload a new release shortly.

But I'm not planning to maintain backward compatibility with Alfred 3. I did it to let time for Alfred 3 users to migrate to Alfred 4, but maintaining compatibility is too much work, plus I cannot use all the great benefits from Alfred 4.

**Comment by vdesabou** [comment]
Can you try to re-download from http://alfred-spotify-mini-player.com, it should work now

**Comment by jannismain** [comment]
I can confirm that the new v8.1 is working with Alfred3. Thanks!

I'm sad to hear that, since I didn't plan on upgrading to Alfred v4 as of yet.. Your workflow might be the reason why I have to in the long run, if I want to enjoy the latest version, however :-)
