### ISSUE TITLE
Is there a way to play a specific song from external trigger?

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#298]
I want to create a macro that will play a specific song I like:

spotify:track:0iX4Pca5ZuBZDaipPRf4xX

It would be awesome if there was an action where I give it a URL of song and it will start playing it (ideally on repeat). I know `on repeat` part is not available via applescript. But at least on iOS, the Open URL to play a song will start playing the song and will repeat it (even though its not on repeat)

I would love to have the same on mac. Thank you.

**Comment by nikitavoloboev** [comment]
The URL can be this too as Spotify gives both URL and URI. The trigger should just take that in and play the song and only that song.

https://open.spotify.com/track/7agPIlFzTpgKnqyxUVt7aM?si=0pyV9xHSQCymzydrZZcZYQ

**Comment by vdesabou** [comment]
I've updated the play external trigger to accept Spotify URI or URLs:

<img width="972" alt="Screenshot 2019-07-08 at 14 54 21" src="https://user-images.githubusercontent.com/4061923/60845278-9f362880-a190-11e9-8361-8b724884e971.png">

Please try to install this beta https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v-8.2-beta

**Comment by nikitavoloboev** [comment]
Perfect, thanks

**Comment by nikitavoloboev** [comment]
Is it possible to extend this trigger to accept playlists?

So I can pass in `spotify:playlist:0ERn0U4qZIKC8Dy7RrMMsn` and it will play the playlist instead of a song.

Otherwise I don't mind a new external trigger. Or perhaps it's already possible to do?

**Comment by vdesabou** [comment]
@nikitavoloboev I've added the possibility to play any track, album, playlist and artist using the same 'play' external trigger in latest beta available [here](https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v-8.2-beta)
You can use Spotify URIs or full Spotify URLs

**Comment by nikitavoloboev** [comment]
Thank you.
