### ISSUE TITLE
Now Playing notifications settings not working fine

### ISSUE THREAD

**Issue by Kiszaner** [vdesabou/alfred-spotify-mini-player#299]
After installing version 8.1.1 with imported settings from previous version, I keep with issues 1st and 3rd I commented in https://github.com/vdesabou/alfred-spotify-mini-player/issues/276#issuecomment-504488056

First time using the updated version seemed to work for 1st issue, but after changing the Now Playing setting on Alfred the issue reappeared.

**Comment by vdesabou** [comment]
Yes I've reproduced some weird things as well. Can you install this beta https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v-8.2-beta and then make sure to disable now playing notifications and re-enable it after. Let me know if that helps
Thanks for the feedback
