### ISSUE TITLE
Creating Library Issue

### ISSUE THREAD

**Issue by Dantheman0** [vdesabou/alfred-spotify-mini-player#302]
My music library won't finish being created. It is stuck at 570 / 572 tracks, and I could not find any solutions to this problem elsewhere.

**Comment by vdesabou** [comment]
Use the `spot_mini_debug` keyword input and use `Send an email to the author `option. This will generate an email with all information needed for troubleshooting.

**Comment by vdesabou** [comment]
You can also use `spot_mini_kill`command to stop the library update and eventually restart it after

**Comment by vdesabou** [comment]
Any feedback ? If not I'll close the issue in a few days. Thanks

**Comment by Dantheman0** [comment]
Thank you for help. Your’e solution worked to fix the library creation issue for Spotify Mini Player. I apologize for not responding in a prompt manner.

Thanks again,
Daniel Gonzalez
