### ISSUE TITLE
macOS Catalina 10.15 cannot auth

### ISSUE THREAD

**Issue by partymike** [vdesabou/alfred-spotify-mini-player#303]
using 8.3

when I type "spot_mini" into alfred v4.0.4, I can see the option to enter the application ID's but if I click nothing happens...I can select the other 2 options to open Spotify details etc and these are fine...almost as if something is blocked from running?

**Comment by vdesabou** [comment]
You need to paste the application Id, check the GIF in Create the library section in http://alfred-spotify-mini-player.com/setup/

**Comment by partymike** [comment]
sorry yes but when I do this I get an error "alerter" can\t be opened because apple cannot check it for malicious software - this software needs to be updated.

so not sure if this is expected behaviour?

**Comment by vdesabou** [comment]
I don't have Catalina installed yet. I assume this is preventing notifications to be displayed, but I'm not sure it would impact the auth process.

Are you able to set Client Id and Client Password ?
Are you able to create the library?

If not, please send a debug zip file as explained here http://alfred-spotify-mini-player.com/articles/support/

**Comment by partymike** [comment]
seem more like a warning, all functions seems to be ok so I'll close this :-)
