### ISSUE TITLE
Catalina refuses to run `alerter`

### ISSUE THREAD

**Issue by silviabotros** [vdesabou/alfred-spotify-mini-player#304]
Catalina is not running the `alerter` script since it is packaged as a binary it cannot read and scan for malware. This means that everytime the Spotify track changes, instead of a notification of the new track, I get an error message.

**Comment by acsands13** [comment]
Had this issue too... While waiting for Catalina updates, there are two steps to fix it in the meantime:

**Enable Alerter**
Enable the `alerter` script by: finding the script in Finder > right click > Open > accept that it can't be opened with "Open" > close Terminal

You can find the script in Finder by: (1) right clicking on the Spotify Mini Player workflow in Alfred and clicking "Open in Finder", (2) clicking "Show in Finder" when the `alerter` security dialog pops up again, or (3) the script is most likely in `~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.{SOME_ID}/alerter`. 

More info [here](https://www.fireebok.com/resource/how-to-fix-that-app-can-not-open-on-macos-catalina.html).

**Enable Spotify Mini Player**
Right click on `App/green/Spotify Mini Player` from the workflow folder > click Open > again Open. Next time you get a notification, Catalina will ask if you want to allow Spotify Mini Player to show notifications. You can also force this to happen by disabling Up Next notifications from spot_mini and then reenabling them.

Hope that helps!

**Comment by vjeantet** [comment]
Salut !

alerter binary now updated for catalina.

**Comment by vdesabou** [comment]
8.5 will with back back to alerter
