### ISSUE TITLE
VERY slow to respond when Spotify requires HTTP Proxy

### ISSUE THREAD

**Issue by tallpsmith** [vdesabou/alfred-spotify-mini-player#306]
I have been using Spotify Mini player successfully for a long time, and love it.  Recently our corporate network setup has required using an HTTP proxy, and Spotify now needs to be configured to use it to work within our boundaries.

Spotify mini-player does actually, _eventually_ response to Alfred command (Pause/Play/Next track), however, it takes about 20-30 seconds. It's as if it's attempting to connect via one path that doesn't work, and then falls back to another that does work.  

The latency is quite annoying though, so wondering if there's anything that can be done.  If there are specific logs being written somewhere I can share, let me know and I'll post them.

**Comment by vdesabou** [comment]
Have you enabled "Use Mac OS http proxy settings for scripts" option in Alfred preferences ?

There's not much I can do on my side, but I can have a look at your logs if you send me the debug ZIP as explained here http://alfred-spotify-mini-player.com/articles/support/

**Comment by tallpsmith** [comment]
I've tried toggling that on off, and playing with the prefix settings but nothing seems to change. Everything works, just with a very long latency (and smells like a classic 30-second Socket timeout error, before a fallback).

I'll follow the support link and you can have a look there.

**Comment by vdesabou** [comment]
Copy/Pasting investigation from email:

If I understand correctly from this post https://www.alfredforum.com/topic/286-alfred-doesnt-use-proxy/?do=findComment&comment=60433 PHP does not really handle http_proxy environment variable (that should be used when clicking in Alfred preferences)

You can try to tweak workflows.php by adding some curl options, as explained here: https://stackoverflow.com/a/11468654

Not sure what was the outcome though...

**Comment by rafaelpirolla** [comment]
Adding these options on workflows.php line 510, 511 did the trick to support proxy:
```
$defaults = array( // Create a list of default curl options
                CURLOPT_RETURNTRANSFER => true, // Returns the result as a string
                CURLOPT_URL => $url, // Sets the url to request
                CURLOPT_FRESH_CONNECT => true,
                CURLOPT_PROXY => "localhost",
                CURLOPT_PROXYPORT => "3128",
            );
```
