### ISSUE TITLE
Mac OS Catalina Blocking the Setup - Any workarounds

### ISSUE THREAD

**Issue by PadmasterGeneral** [vdesabou/alfred-spotify-mini-player#307]
<img width="1606" alt="Screenshot 2019-10-24 at 11 58 50" src="https://user-images.githubusercontent.com/10830080/67479405-e409a080-f655-11e9-8aad-0bcb3dbabdfc.png">

**Comment by vdesabou** [comment]
see https://github.com/vdesabou/alfred-spotify-mini-player/issues/304#issuecomment-540843554
