### ISSUE TITLE
How to play playlist from a link

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#308]
I may have asked this but can't find it in closed issues.

There is a `play` external command that takes in a song to play like `spotify:track:7buuX5RshJBQuNz3T3grHa`.

Is it possible to have a similar command but for playlists? ie I want to supply it a link like `spotify:playlist:4AVzuW0i3Wz8J7cxBG84Uy` or `https://open.spotify.com/playlist/4AVzuW0i3Wz8J7cxBG84Uy?si=LuQwy4NXQliJoLX__BJDOw` and it would start playing the playlist ideally in shuffle mode (although I know that's not possible due to Spotify API).

Thank you.

**Comment by vdesabou** [comment]
That's already available normally, see https://github.com/vdesabou/alfred-spotify-mini-player/issues/298#issuecomment-515771184

Regarding shuffling, as you said it is not possible to start a playlist in shuffle mode, but nothing prevents you to call shuffle command just before starting the playlist:

![Screenshot 2019-10-29 at 13 48 40](https://user-images.githubusercontent.com/4061923/67768470-dd629b00-fa52-11e9-83a2-92238f7461ae.png)

**Comment by nikitavoloboev** [comment]
I get error:

![2019-10-29 at 13 56](https://user-images.githubusercontent.com/6391776/67768956-e30cb080-fa53-11e9-8cd3-a88af09b531e.png)

I pass in `spotify:playlist:4AVzuW0i3Wz8J7cxBG84Uy` to `play` command.

**Comment by vdesabou** [comment]
It should be working with version 8.3, I've just tested it

**Comment by nikitavoloboev** [comment]
![2019-10-29 at 13 59](https://user-images.githubusercontent.com/6391776/67769190-4696de00-fa54-11e9-9b1e-030b397312b2.png)

Got this.

Will manually get latest release from website

**Comment by nikitavoloboev** [comment]
Confirm 8.3 works. Thanks. :)
