### ISSUE TITLE
Spotify Mini Player not showing up in Notifications panel so can't turn off notifications

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#309]
I can't find the workflow in Notifications panel:

![2019-10-29 at 14 03](https://user-images.githubusercontent.com/6391776/67769556-f8cea580-fa54-11e9-9e3c-021a1e6557e8.png)

Thus I can't turn of notifications from the workflow. Is there a way to make it appear in the panel somehow?

**Comment by vdesabou** [comment]
Can you try to double click on Spotify Mini Player.app as explained there https://github.com/vdesabou/alfred-spotify-mini-player/issues/224#issuecomment-357928852

**Comment by nikitavoloboev** [comment]
Sweet. That worked.
