### ISSUE TITLE
Feature request: Add option to replay current song

### ISSUE THREAD

**Issue by tabchas** [vdesabou/alfred-spotify-mini-player#313]
Currently the "Previous Track" command goes to the previous song in your playlist. 

On Spotify, the "Previous Track" button by default goes to the beginning of the song when you click it first, and if you click it again it goes to the previous song in your playlist.

Having a seperate command to "Replay Current Song" would be great! Currently I run the "Previous Track" command and then run "Next Track" which puts me back at the start position of the current song.

**Comment by vdesabou** [comment]
This will be available in 8.4:

* You can change behaviour of `Previous Track`, by modifying variable `previous_track_for_real`:-

  * 1 for going to previous track
  * 0 for going back to beginning of the track

**Comment by tabchas** [comment]
Thanks! - although I think it would be useful to have the two commands broken out - ex: one will be `Previous Track` and the other is `Replay Track`. That way you can quickly choose between the two.

Is this possible with the configuration you proposed?

The problem is if you select **0 for going to beginning of the track**, to get to the previous track would require two consecutive `Previous Track` commands.
