### ISSUE TITLE
Failure to authenticate on invalid callback

### ISSUE THREAD

**Issue by kylemh** [vdesabou/alfred-spotify-mini-player#315]
Not sure what else to share here... I had this working on my personal laptop and trying to integrate on my work laptop using a new app on the Spotify API dashboard.

> There was an error during the authentication (exception 
> SpotifyWebAPI\SpotifyWebAPIAuthException: Invalid client at 
> SpotifyWebAPI.Request.parseBody(Request.php:49) at 
> SpotifyWebAPI.Request.send(Request.php:242) at 
> SpotifyWebAPI.Request.account(Request.php:99) at 
> SpotifyWebAPI.Session.requestAccessToken(Session.php:217) at (main)(callback.php:24))

**Comment by vdesabou** [comment]
`Invalid client` error means you have a problem with the application you created here https://developer.spotify.com/my-applications

I suggest you call « spot_mini_reset_settings » then copy client id and client secret from your Spotify Application here (https://developer.spotify.com/my-applications)  
Make sure to click ‘Save’ button once you set the Redirect URI

Then authentication should work

Keep me posted

**Comment by kylemh** [comment]
Yeah, that's what I did!

Installed the workflow for the first time, copied the key, pasted the key into the Alfred box on prompt, followed the auth prompt, clicked the happy path button and then had the above occur 😢

**Comment by vdesabou** [comment]
99.99% of the time, it's a user error, can you reset the config by invoking spot_mini_reset_settings and try again.

If this is still not working, use spot_mini_debug and send me an email
