### ISSUE TITLE
can't access liked songs or suppress notifications

### ISSUE THREAD

**Issue by shaunsauve** [vdesabou/alfred-spotify-mini-player#318]
Notification of currently playing song isn't suppressed when reduce_notifications=1 (not sure this is the intention). 

Can't seem to access the 'Liked Songs' playlist in spotify.

Impressive work but annoying notifications are a deal-breaker for me, will try again in a few versions :)

**Comment by vdesabou** [comment]
Everything is explained here : http://alfred-spotify-mini-player.com/articles/now-playing/

![image](https://user-images.githubusercontent.com/4061923/70122476-fd4c3680-1670-11ea-9764-567e9f327ecb.png)


For liked songs: http://alfred-spotify-mini-player.com/known-issues/

![image](https://user-images.githubusercontent.com/4061923/70122544-2076e600-1671-11ea-9d13-8660f7785a43.png)

**Comment by shaunsauve** [comment]
👍
