### ISSUE TITLE
Feature Request: Allow searching for multiple types of results at once

### ISSUE THREAD

**Issue by rtbarnes** [vdesabou/alfred-spotify-mini-player#319]
Currently, searching online requires either searching for only one type of result ("Search for  tracks only", "Search for artists only", etc.) or indicating the order that you'd like to see these categories in (playlist->album->track->artist, album->artist->track->playlist, etc.). This is kind of unintuitive, and not how Spotify works in its client. 

As far as I can tell, [Spotify's search API](https://developer.spotify.com/documentation/web-api/reference/search/search/) allows for queries that span multiples types (see the `type` parameter). Would it be possible to have an option to search across multiple (or just all) types, and simply display those results in order, as returned by Spotify's search?

**Comment by vdesabou** [comment]
Everything should already be possible:

When you type here, it will search for everything:

<img width="880" alt="Screenshot 2019-12-26 at 17 31 24" src="https://user-images.githubusercontent.com/4061923/71482945-9c45f780-2805-11ea-8982-c417e7413dc0.png">


<img width="691" alt="Screenshot 2019-12-26 at 17 33 28" src="https://user-images.githubusercontent.com/4061923/71482998-da431b80-2805-11ea-9b53-e1461310801e.png">


And you can change search result order by using `Change search order results`:

<img width="683" alt="Screenshot 2019-12-26 at 17 32 36" src="https://user-images.githubusercontent.com/4061923/71482976-bbdd2000-2805-11ea-804d-1463b5895fbb.png">
