### ISSUE TITLE
Share Current Track not working

### ISSUE THREAD

**Issue by PeterKey** [vdesabou/alfred-spotify-mini-player#320]
Share current track is not working for me currently. Nothing happens. Where is the share dialog usually supposed to open?
I had an error first, that terminal-share wasn't allowed to start at first but by right-click+open I granted it the permission. 

I am currently on Catalina and Alfred 4.

**Comment by vdesabou** [comment]
Apparently, Apple removed Facebook (and other social media accounts) from macOS Mojave (10.14), so [terminal-share](https://github.com/mattt/terminal-share) is no more working. The only I can do is to remove option when using Mojave and later versions.

**Comment by vdesabou** [comment]
https://alfred-spotify-mini-player.com/blog/Version-9.0/
