### ISSUE TITLE
playlist_uri assigned value <TRACK>

### ISSUE THREAD

**Issue by stkiller** [vdesabou/alfred-spotify-mini-player#322]
Hello there!

Thanks a lot for all your work!
The line below causes the following error when I try invoking “Add current track to....” from Alfred : “Cannot get playlist name song playlist uri <TRACK>”. Commenting it resolves the error. Is this expected behavior?

Thanks!

 https://github.com/vdesabou/alfred-spotify-mini-player/blob/c70c8c432f21d744fa32bab04b9cbf04e25564a9/spotify-mini-player/src/action.php#L1207

**Comment by vdesabou** [comment]
Thanks for reporting this! this should be fixed using this beta : https://transfer.sh/J58EG/spotifyminiplayer-beta.alfredworkflow
