### ISSUE TITLE
How to auto hide current song notification?

### ISSUE THREAD

**Issue by toancaro** [vdesabou/alfred-spotify-mini-player#324]
I must click the Close button to hide it. Is there anyway to hide automatically?
![image](https://user-images.githubusercontent.com/3683223/73431255-8f6f7300-4372-11ea-8d44-4a49c1b16b0e.png)

**Comment by vdesabou** [comment]
It's because you're using "alert" instead of "banner" in the Mac OS notifications preferences for Spotify Mini Player, more info [here](http://alfred-spotify-mini-player.com/articles/now-playing/)
