### ISSUE TITLE
How do i clear client id

### ISSUE THREAD

**Issue by doronkatz** [vdesabou/alfred-spotify-mini-player#327]
I need to clear the client id and enter a new one but cant find where to

**Comment by vdesabou** [comment]
I suggest you use « spot_mini_reset_settings »  command:

It will delete the settings file and recreate a default one. Then next time you open the workflow, you’ll need to do authentication process again, but you will not need to re-create your library.

**Comment by doronkatz** [comment]
Got it thanks was looking for that

This email and any attachments are confidential and may be subject to copyright, legal or some other professional privilege.
They are intended solely for the attention and use of the named addressee(s). They may only be copied, distributed or
disclosed with the consent of the copyright owner. If you have received this email by mistake or by breach of the confidentiality
clause, please notify the sender immediately by return email and delete or destroy all copies of the email. Any confidentiality,
privilege or copyright is not waived or lost because this email has been sent to you by mistake.
