### ISSUE TITLE
Search Online external trigger missing

### ISSUE THREAD

**Issue by skibitsky** [vdesabou/alfred-spotify-mini-player#329]
Hi,

There is no external trigger for [Search Online](http://alfred-spotify-mini-player.com/articles/search-online/) action.

**Comment by vdesabou** [comment]
What about this:

<img width="821" alt="Screenshot 2020-04-04 at 14 42 31" src="https://user-images.githubusercontent.com/4061923/78450955-a25c3780-7682-11ea-8c0b-899be2a748b7.png">

**Comment by skibitsky** [comment]
Oh! I can’t imagine how I didn’t notice it. Thank you!
