### ISSUE TITLE
Current track notifications don't disappear

### ISSUE THREAD

**Issue by samlcharreyron** [vdesabou/alfred-spotify-mini-player#331]
Since updating to version 8.4, the current track notifications at the top right no longer disappear and cloud up the desktop. See the image below

![image](https://user-images.githubusercontent.com/451016/77900695-b537cc00-727e-11ea-8202-a4e81ee30d22.png)

**Comment by samlcharreyron** [comment]
Figured it out. The notification settings in the System Preferences needs to be set to banners instead of alerts.

![image](https://user-images.githubusercontent.com/451016/77901186-79513680-727f-11ea-815a-6b02206eb1f3.png)

**Comment by vdesabou** [comment]
See https://github.com/vdesabou/alfred-spotify-mini-player/issues/324
