### ISSUE TITLE
No artwork when using OS notifications (v8.4)

### ISSUE THREAD

**Issue by mamabox** [vdesabou/alfred-spotify-mini-player#332]
Hey there,

Sorry if this isn't a real issue but there is no artwork for songs even though I am using the [OS notifications](http://alfred-spotify-mini-player.com/articles/now-playing/):
![image](https://user-images.githubusercontent.com/19555715/78379616-f3145780-75d2-11ea-9889-3e41e05b3dd2.png)

I am running v8.4 on mac OS Catalina (10.15.3)

Thanks!

**Comment by vdesabou** [comment]
This should be fixed in version 8.5
