### ISSUE TITLE
Feature request: Liking songs

### ISSUE THREAD

**Issue by mamabox** [vdesabou/alfred-spotify-mini-player#333]
Hey there,

Would you please consider adding the option to like songs from the mini-player?

Thanks!

**Comment by vdesabou** [comment]
Unfortunately, the Spotify API doesn't allow this, see for example https://github.com/spotify/web-api/issues/710

**Comment by vdesabou** [comment]
Sorry @mamabox , I was confused. Liking songs is already supported by the workflow, it is when you add a song in "Your Music", and you can control it as explained here http://alfred-spotify-mini-player.com/articles/alfred-playlist/

In next version 9.0, I've made a lot of improvements for "Your Music", so stay tuned !
