### ISSUE TITLE
Deprecate mopidy

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#340]
Mopidy-Spotify is dependent on pyspotify, a wrapper for Spotify's libspotify C library. libspotify was deprecated in 2015 with no replacement. It is unmaintained, functionally limited, and also now unavailable from the Spotify developer site. Where possible we are moving to use Spotify's Web API instead. However, native playback is still only possible using libspotify and there is no official way for us to provide some Spotify features.
Limitations and/or bugs in libspotify currently result in missing/broken Mopidy-Spotify support for the following:
•	Saving items to My Music (#108) - possible via web API
•	Podcasts (#201) - unavailable
•	Radio (#9) - unavailable
•	Spotify Connect (#14) - unavailable

Besides Mopidy is now in version 3 which has a lot of breaking changes.

I will remove documentation and settings but leave the code in place for those still using it

**Comment by vdesabou** [comment]
https://alfred-spotify-mini-player.com/blog/Version-9.0/

**Comment by chrismessina** [comment]
> https://alfred-spotify-mini-player.com/blog/Version-9.0/

Has the blog moved?

**Comment by vdesabou** [comment]
Yes I've removed the blog. All the information from the blog (release notes) should be there https://github.com/vdesabou/alfred-spotify-mini-player/releases
