### ISSUE TITLE
Add ability to create a `Similar Playlist` from the playlist being played

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#343]
Basically I press a hotkey and it runs this action:

![CleanShot 2020-04-22 at 19 32 43@2x](https://user-images.githubusercontent.com/6391776/80014057-1181ba80-84d0-11ea-82a7-0476999f1e19.png)

Creates the playlist and starts playing it. Similar to the song_radio or artist_radio that exists already.

**Comment by vdesabou** [comment]
Hi @nikitavoloboev, 

Yes that should be feasible using https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/

I'll try to include it in a next version

**Comment by vdesabou** [comment]
Available in version 9.0 see https://alfred-spotify-mini-player.com/blog/Version-9.0/
