### ISSUE TITLE
Feature Request: copy current playlist link to clipboard

### ISSUE THREAD

**Issue by zqso** [vdesabou/alfred-spotify-mini-player#369]
Hi,
I would like to copy the current playlist link to clipboard globally so that I could quickly share the playlist in a quick way.
It's similar to this workflow action: copy_current_track_url_to_clipboard.

I went through the current workflow v9.11 and did not find it. 
Would you please create one, or maybe the function has been existing in the current version, please remind me. :)

Thank you so much.

**Comment by vdesabou** [comment]
I'm afraid this is not technically possible as I can get the current track playing, but I've no reliable way to know which playlist is being played.
