### ISSUE TITLE
🔊 Set volume actions

### ISSUE THREAD

**Issue by Bjaux** [vdesabou/alfred-spotify-mini-player#371]
Hey, 

I'm using spotify a lot with chromecast audio & co. Since i haven't found a way to control google home directly via alfred, I now use your player to control the music via spotify connect.

Now I'd love to have more granular volume control. Maybe a variable that sets the step size of "volume up" and "volume down" or even custom "volume up by x" or "set volume to x". This would be absolutely awesome, thanks for your great work!

Kind Regards,
Björn

**Comment by Bjaux** [comment]
Oh, I found the "Volume Step" Option!

Still would love an option to directly set the absolute volume to X, but this already works great, thank you very much!

**Comment by vdesabou** [comment]
![Screenshot 2020-10-16 at 11 56 26](https://user-images.githubusercontent.com/4061923/96244648-a4df0880-0fa6-11eb-9fe0-1e64b6745e5d.png)

Example:

```
tell application id "com.runningwithcrayons.Alfred" to run trigger "set_volume" in workflow "com.vdesabou.spotify.mini.player" with argument "78"
```

![Screenshot 2020-10-16 at 11 57 28](https://user-images.githubusercontent.com/4061923/96244774-cc35d580-0fa6-11eb-9d81-234c9cc01492.png)


![Screenshot 2020-10-16 at 11 57 07](https://user-images.githubusercontent.com/4061923/96244730-be805000-0fa6-11eb-846a-78d20091a136.png)

![Screenshot 2020-10-16 at 11 57 52](https://user-images.githubusercontent.com/4061923/96244808-d8219780-0fa6-11eb-9faa-aa70979fa5da.png)
