### ISSUE TITLE
Add to Queue

### ISSUE THREAD

**Issue by Bjaux** [vdesabou/alfred-spotify-mini-player#372]
Hey,

sorry for the spam, I searched all the places i know about being customizable:

Is there an Option to add a Track to the current Queue as "next"? So neither at the end of the queue, nor by replacing and aborting the current track, but just as the very next item.

**Comment by vdesabou** [comment]
This is described in [modifiers page](https://alfred-spotify-mini-player.com/articles/modifier-keys/):

```
Select a track with ⌘+⌥ (cmd+alt key) to add track to queue (Spotify Connect users only)
```

**Comment by Bjaux** [comment]
Currently I get the Error that it's only available with spotify connect, even though I'm streaming to my chromecast audio right now. Might be a problem with spotify device discovery not working on desktop versions right now, I can't start playing on the chromecast from my macbook either, but still control everything when the casting was initiated from my phone. 

Anyway - I haven't found any option to BuyYouACoffeeTM or something similar, is there any way to support your work here? :)

**Comment by vdesabou** [comment]
You should be able to select Spotify Connect in settings menu as explained here https://alfred-spotify-mini-player.com/articles/spotify-connect/
In a future version, I'll make it default for premium users https://github.com/vdesabou/alfred-spotify-mini-player/issues/368 as it is the best way to enjoy the workflow.

Then it should work, if not let me know

> Anyway - I haven't found any option to BuyYouACoffeeTM or something similar, is there any way to support your work here? :)

There is a "buy me a beer" button on https://alfred-spotify-mini-player.com home page. Much appreciated ;)
