### ISSUE TITLE
A way to add song to queue

### ISSUE THREAD

**Issue by fipo42** [vdesabou/alfred-spotify-mini-player#373]
Hi, is there any possibility to implement "add this song to queue" in the future? might be triggered with action modifier when we try to press enter after search for a track (just a suggestion)

Thank you for your work for this cool workflow!

**Comment by vdesabou** [comment]
This is already possible, see https://github.com/vdesabou/alfred-spotify-mini-player/issues/372#issuecomment-643946827

**Comment by fipo42** [comment]
Ah i see, sorry for not reading through it first...
Thank you!
