### ISSUE TITLE
Handle non english characters

### ISSUE THREAD

**Issue by Belco90** [vdesabou/alfred-spotify-mini-player#374]
Hi there!

I have a suggestion for improving the search. Diacritical marks are causing different search results, check these examples:
![CleanShot 2020-06-26 at 13 17 49](https://user-images.githubusercontent.com/2677072/85851692-764ae100-b7af-11ea-9815-672f02d1a119.png)
![CleanShot 2020-06-26 at 13 17 55](https://user-images.githubusercontent.com/2677072/85851698-7814a480-b7af-11ea-8495-dafa0285384d.png)

(you can check how these 2 searches end in the same results in Spotify itself).

This could be solved by deburring the search input. I'm not sure if PHP has a built-in method for this, but the idea would be to use something similar to [lodash.deburr method](https://lodash.com/docs/4.17.15#deburr)

**Comment by vdesabou** [comment]
Good idea! I found this https://github.com/lodash-php/lodash-php/blob/master/src/String/deburr.php
I will try to use it.

**Comment by vdesabou** [comment]
This is a breaking change, so users have to re-create their library:

<img width="696" alt="Screenshot 2020-07-11 at 10 21 47" src="https://user-images.githubusercontent.com/4061923/87219987-6ced7700-c360-11ea-9651-15124a57d3c5.png">

**Comment by vdesabou** [comment]
@Belco90 This is coming in version 9.12 ! 🥳

Example:
<img width="691" alt="Screenshot 2020-07-11 at 10 26 31" src="https://user-images.githubusercontent.com/4061923/87220057-06b52400-c361-11ea-81de-dc7113735791.png">

**Comment by Belco90** [comment]
Amazing, thanks!
