### ISSUE TITLE
Does automatic Library refresh drain battery / tax CPU?

### ISSUE THREAD

**Issue by Baggydawg** [vdesabou/alfred-spotify-mini-player#375]
Hi there,

I was wondering if I set automatic library refresh on, whether this would drain my battery more easily.

Also, whether there would be any difference in the frequency of refresh, such as 1hr vs 12hr.

**Comment by vdesabou** [comment]
Not sure what's the impact on battery is, when I refresh my library for example I get:


![Screenshot 2020-06-26 at 19 03 21](https://user-images.githubusercontent.com/4061923/85882546-bf1a8e00-b7df-11ea-87a4-7d06bbeb1dfc.png)


![Screenshot 2020-06-26 at 19 02 11](https://user-images.githubusercontent.com/4061923/85882472-9eeacf00-b7df-11ea-8e0e-cbbe3c75c977.png)
![Screenshot 2020-06-26 at 19 02 15](https://user-images.githubusercontent.com/4061923/85882477-a14d2900-b7df-11ea-9efd-c61448468dd6.png)
![Screenshot 2020-06-26 at 19 02 26](https://user-images.githubusercontent.com/4061923/85882481-a3af8300-b7df-11ea-82cf-c4bbb5a612d4.png)

I refresh every one hour, but battery is not a concerned for me as my Mac is plugged almost 100% of the time

**Comment by Baggydawg** [comment]
ok awesome, thanks for the quick response!!
