### ISSUE TITLE
Database error: HY000 no...column: yourmusic_albums

### ISSUE THREAD

**Issue by anna-osipova** [vdesabou/alfred-spotify-mini-player#377]
When I select Your Music it shows 9 albums even though I have a lot more.
Your Music -> Abums shows some albums. When I try to search I get this error.
I've tried recreating the library.

Steps to reproduce:
1. Your Music
2. Albums
3. Try to search

![screencast 2020-07-07 11-15-40](https://user-images.githubusercontent.com/3600471/86745928-5d5ded80-c043-11ea-885c-230b2e819462.gif)

**Comment by vdesabou** [comment]
First make sure to update version to latest 9.11
Then select "re-create library" as it is suggested in the error window

**Comment by anna-osipova** [comment]
@vdesabou I've got 9.11. I installed the workflow today for the first time. Have recreated the library several times, also added/removed some albums in Spotify in between.

**Comment by vdesabou** [comment]
I see, I can reproduce the issue.I'll be working on a fix for 9.12
Thanks for reporting
