### ISSUE TITLE
Add remove_current_track_from_alfred_playlist_or_your_music trigger 

### ISSUE THREAD

**Issue by mbac** [vdesabou/alfred-spotify-mini-player#384]
Hi,

This isn’t much of an issue… Rather, it’s me asking for a bit of support. I’m trying to run AppleScript from a touchbar button (BetterTouchTool) to star/like/add to library Spotify’s current track.

It seems to me the most straightforward approach is:
```
tell application “Alfred 4”
    run trigger “add_current_track_to” in workflow “com.vdesabou.spotify.mini.player”
end tell
```

However, this just takes you to the Mini Player “choose” dialog where you send a song to a playlist or to your library.

What argument should I use when triggering `add_current_track_to` in order to send the track straight to “Liked Songs”?

Thanks!

**Comment by vdesabou** [comment]
I think your best option is to use `add_current_track_to_alfred_playlist_or_your_music` and update settings to control _Your Music_ as explained in this [article](https://alfred-spotify-mini-player.com/articles/alfred-playlist/)

**Comment by mbac** [comment]
Hi,

Would it be possible to have a symmetrical `remove_current_track_from_alfred_playlist_or_your_music` trigger, using the same default as the `add_to`

The current `remove` trigger is like the first `add_to` and it brings up the Alfred window…

Thanks again for your great work…
