### ISSUE TITLE
Error[index.php]: cannot set PDO settings

### ISSUE THREAD

**Issue by albertobissacco** [vdesabou/alfred-spotify-mini-player#39]
I followed all instructions (created an app, set Client_ID and Secret_ID, set the right redirect url) but at the last step, when i try to Authenticate it gave me this error:  "Error[index.php]: cannot set PDO settings"
![screen shot 2015-01-22 at 16 57 48](https://cloud.githubusercontent.com/assets/189348/5859171/93b61cf4-a258-11e4-84c0-c6a5f1cdd9ec.png)

**Comment by vdesabou** [comment]
Hi, 

That's strange because normally settings shall be set when you invoke the workflow in the two first steps..
Can you follow instructions from here http://alfred-spotify-mini-player.com/articles/support/ (create TGZ file and send it to email on my profile) ?

**Comment by vdesabou** [comment]
Version 6.0 is now live. It will fix this issue. Get it here http://alfred-spotify-mini-player.com
