### ISSUE TITLE
Pasting Client Id doesn't do anything

### ISSUE THREAD

**Issue by Mattyfaz** [vdesabou/alfred-spotify-mini-player#396]
When pasting the Client Id and pressing Enter nothing seems to happen, it just closes and then when opening it again I am prompted to add my Client Id. I never make it to any point where it requests Client secret.

GIF below of the behavior:
![ezgif-4-4da362233758](https://user-images.githubusercontent.com/10377148/92189864-0fc6fb00-eea3-11ea-8d1f-6380c32da7c3.gif)

Workflow was downloaded/added to Alfred from the Spotify Mini Player website ~1 hr ago.
Have tried restarting Alfred, the Macbook Pro, etc. and nothing seems to change the behavior.

**Comment by vdesabou** [comment]
Just to make sure, you do type enter when you set the client id, right ?
Can you please send me a debug email bu following those steps https://alfred-spotify-mini-player.com/articles/support/

**Comment by Mattyfaz** [comment]
> Just to make sure, you do type enter when you set the client id, right ?

To clarify - you mean press the _enter_ key on my keyboard? Yes I do that.

> Can you please send me a debug email bu following those steps https://alfred-spotify-mini-player.com/articles/support/

This has made me realise that it is not something wrong with pressing the enter key, when I type anything else into Alfred (e.g. _Chrome__) and hit enter it works. But when doing anything with spot_mini nothing happens at all when I press enter, just closes.

**Comment by vdesabou** [comment]
Please send me the debug email so that I can verify the logs--
Vincent de Saboulin

**Comment by Mattyfaz** [comment]
Updating to the latest version of spot_mini has fixed the issue.
