### ISSUE TITLE
Customise emojis used in the workflow

### ISSUE THREAD

**Issue by barzkim** [vdesabou/alfred-spotify-mini-player#401]
Hi there! Love the workflow so far! I was wondering if it was possible to remove the emojis completely or replace them with my own?

![mini player screen](https://user-images.githubusercontent.com/51450856/93692947-782ef280-fac7-11ea-8823-1cded7e94755.jpg)

**Comment by vdesabou** [comment]
Right now it is not possible to remove or change it( unless you edit the
code of course), but that’s actually something I had in mind. I will add
that in a next release !--
Vincent de Saboulin

**Comment by barzkim** [comment]
I see, that would be awesome to have in a future update! :) 

You are awesome!
