### ISSUE TITLE
Authenticate to Spotify

### ISSUE THREAD

**Issue by Kazz47** [vdesabou/alfred-spotify-mini-player#405]
The Authenticate to Spotify step is loading a page with the `INVALID_CLIENT: Invalid redirect URI`. This is after entering my application ID and secret.

**Comment by vdesabou** [comment]
You probably did not click on the **SAVE** button in your Application page

Make sure to follow carefully the steps from Setup http://alfred-spotify-mini-player.com/setup/

**Comment by vdesabou** [comment]
Closing assuming it fixed the problem
