### ISSUE TITLE
How to make hotkey to "Add current song to Your Music (Liked Songs)"

### ISSUE THREAD

**Issue by jwmann** [vdesabou/alfred-spotify-mini-player#406]
I'm in the workflow, I see the hotkey for `com.vdesabou.miniplayer.addcurrenttrack` but I'm not sure how to tell it to automatically select "Your Music".

Right now it just sets it to my default "Alfred Playlist" which isn't my Liked Songs.

**Comment by vdesabou** [comment]
You can do that by selecting "Control Your Music" (see [article](https://alfred-spotify-mini-player.com/articles/alfred-playlist/)) :
<img width="743" alt="Screenshot 2020-10-03 at 08 38 21" src="https://user-images.githubusercontent.com/4061923/94985110-e3f76d80-0553-11eb-9ede-f069cfa83d9b.png">

Then you can use the `add_current_track_to_alfred_playlist_or_your_music` hotkey/command

**Comment by jwmann** [comment]
Beautiful, thank you very much!
