### ISSUE TITLE
Add ability to modify "current playing track" notification

### ISSUE THREAD

**Issue by jwmann** [vdesabou/alfred-spotify-mini-player#408]
It would be super useful to be able to modify some of what that notification showed.

In this example:
![Screenshot on 2020-10-04 at 16-50-36](https://user-images.githubusercontent.com/436270/95026773-c7495b80-0661-11eb-842e-828ce713e4f3.png)

I have no interest in how many "stars" this track has. (I'm assuming this is popularity)
I also don't really care about the album but I can live with that.

I'm much more interested whether this is a song I've already "Liked" it or not, for discovering new music.
Instead of popularity, I would replace it with a unicode heart.

An empty heart for a song not "Liked" yet: ♡ (https://www.compart.com/en/unicode/U+2661)
And a full one for one that is already "Liked": ♥ (https://www.compart.com/en/unicode/U+2665)

Please let me know your thoughts! ♥

**Comment by vdesabou** [comment]
This is already possible, [see](https://alfred-spotify-mini-player.com/articles/customization/): 

![Screenshot 2020-10-05 at 09 08 45](https://user-images.githubusercontent.com/4061923/95049718-9a8d5680-06ea-11eb-8714-d691541c86b6.png)

I like your idea to add if a song is liked or not, I'll create a separate issue to track this !

**Comment by jwmann** [comment]
Beautiful! Thank you so much ❤️
