### ISSUE TITLE
Authentication not working?

### ISSUE THREAD

**Issue by mikl** [vdesabou/alfred-spotify-mini-player#41]
I've tried to set this workflow up on two different machines now, but with little luck. After entering the requested Client ID and Client Secret, I select authenticate, and my browser opens this URL:

`https://accounts.spotify.com/en/login?continue=https:%2F%2Faccounts.spotify.com%2Fen%2Fauthorize%3Fclient_id%3Dlalalalalla%26redirect_uri%3Dhttp:%252F%252Flocalhost:15298%252Fcallback.php%26response_type%3Dcode%26scope%3Duser-library-read%2520user-read-email%2520user-read-private%2520user-library-modify%2520user-follow-modify%2520user-follow-read%2520playlist-read-private%2520playlist-modify-public%2520playlist-modify-private%26show_dialog%3Dtrue%26state%3D`

This is a login form, but when I try to fill it out and submit, nothing seems to happen. If I look in the developer tools, there's a POST request to log in (that suceeds), and then a GET request to load JSON from this URL:

`https://accounts.spotify.com/en/authorize?client_id=lalalalalla&redirect_uri=http:%2F%2Flocalhost:15298%2Fcallback.php&response_type=code&scope=user-library-read%20user-read-email%20user-read-private%20user-library-modify%20user-follow-modify%20user-follow-read%20playlist-read-private%20playlist-modify-public%20playlist-modify-private&show_dialog=true&state=`

That, however, fails, and gets a “400 Bad Request” response, with the body “INVALID_CLIENT: Invalid redirect URI”. It seems Spotify does not like your attempt to redirect to localhost.

I've tried with multiple browsers, but the result seems to be the same, here's how it looks in Firefox:

![screen shot 2015-01-28 at 17 11 20](https://cloud.githubusercontent.com/assets/10263/5941579/372f3088-a712-11e4-85b0-7e4069ed3cab.png)
![screen shot 2015-01-28 at 17 11 26](https://cloud.githubusercontent.com/assets/10263/5941578/372ee56a-a712-11e4-9ee2-b6d3962e0611.png)

**Comment by vdesabou** [comment]
Hi,

Are you sure you clicked Save Button as explained in red here http://alfred-spotify-mini-player.com/setup/ ?

**Comment by vdesabou** [comment]
Looking at the URL, I see client ID set to lalalalalla
Where is it coming from?

**Comment by mikl** [comment]
My apologies, it was because I'd not set the return URL properly, sorry for the confusion.

(and the I replaced my actual client ID with `lalalalalla` just for obfuscation)

**Comment by vdesabou** [comment]
>My apologies, it was because I'd not set the return URL properly, sorry for the confusion.

Ok fine. Now you can enjoy the workflow then!

>(and the I replaced my actual client ID with lalalalalla just for obfuscation)

Yes I figured :smile:
