### ISSUE TITLE
Liked song notification variable not being injected [v10]

### ISSUE THREAD

**Issue by jwmann** [vdesabou/alfred-spotify-mini-player#413]
Perhaps I'm doing it incorrectly but it seems like it's "working" but not actually injecting the unicode.

![Markup 2020-10-16 at 08 22 47](https://user-images.githubusercontent.com/436270/96257692-cfba6400-0f88-11eb-8f62-217fe0db6fb2.png)

![Screenshot on 2020-10-16 at 08-20-04](https://user-images.githubusercontent.com/436270/96257582-9bdf3e80-0f88-11eb-927a-5b9ac4894481.png)

**Comment by vdesabou** [comment]
Thanks for reporting, I've fixed it in 10.1
