### ISSUE TITLE
Error mesaaege

### ISSUE THREAD

**Issue by thezeeali** [vdesabou/alfred-spotify-mini-player#414]
I am not able to istall alfred spotify mini player. getting this error: 

![Screen Shot 2020-10-17 at 5 38 28 PM](https://user-images.githubusercontent.com/67805952/96354031-d12a8000-109f-11eb-8594-08fc5b5189ea.png)

**Comment by vdesabou** [comment]
Are you using latest version 10.1? The download date seems quite old..
I added some logic to better handle this normally

Otherwise, Check this link https://github.com/vdesabou/alfred-spotify-mini-player/issues/304#issuecomment-540843554

**Comment by vdesabou** [comment]
I don’t use alerter anymore so please update to latest version and the problem should be fixed
