### ISSUE TITLE
Customized playlist emoji not working

### ISSUE THREAD

**Issue by tachymetre** [vdesabou/alfred-spotify-mini-player#415]
I updated the workflow to the latest version 10.1 and tried to remove the `playlist` emoji. Somehow I still see it after saving the settings. Not 100% sure if this is the correct settings for it. I removed other emojis like `album` or `artist` and those are working fine.

![Screen Shot 2020-10-18 at 3 58 28 PM](https://user-images.githubusercontent.com/10254328/96386560-e10e9680-1169-11eb-95bb-39d138e5dbb5.jpg)

Also I did not see the settings for `rating` emoji that is mentioned in the release notes.

**Comment by vdesabou** [comment]
Thanks for reporting, it will be fixed in next release !
