### ISSUE TITLE
Setting a hotkey to 'like' currently playing song?

### ISSUE THREAD

**Issue by BluesyMarlin** [vdesabou/alfred-spotify-mini-player#418]
Is it possible to set a keyboard shortcut so that I can add a currently playing song to my 'liked songs' playlist? I am able to add a currently playing song to a particular playlist with a hotkey, but can't work out how to like a currently playing song. Thank you for the wonderful app.

**Comment by vdesabou** [comment]
Please check my answer in https://github.com/vdesabou/alfred-spotify-mini-player/issues/406
That should do what you want !

**Comment by BluesyMarlin** [comment]
Thank you, that worked great - apologies for not seeing this earlier!
