### ISSUE TITLE
Fuzzy Search: permission issue popup with embedded fzf

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#419]
Reported by a user by email:

```
The embedded fzf cannot be opened from the Alfred workflow. I’m running macOS Catalina v10.15.7 and with fuzzy search enabled the workflow is interrupted constantly by permissions popups. There isn’t an option to enable it. Normally when this occurs you ctrl-click the application to open it anyway.
```

**Comment by Stex** [comment]
What works until the fix is released is opening the workflow in Finder and "open" the `fzf` exectutable from its context menu to mark it as safe.

**Comment by JuliusCosmoRomeo** [comment]
Thanks for your solution @Stex
It took me a while to figure out how to "open" the workflow. Turns out I had to Open with > Archiveprogram and then right-click fzf to run it using Terminal. Just in case anyone has a similar problem.

**Comment by Stex** [comment]
> It took me a while to figure out how to "open" the workflow.

@JuliusCosmoRomeo I'm not sure why you had to extract the workflow (which is indeed an archive), Alfred does so automatically when installing the workflow.

After installation, you can access the corresponding folder with the following steps:

1. Open the Alfred preferences
2. Go to "Workflows"
3. Right-Click the workflow
4. Choose "Open in Finder"

![](https://user-images.githubusercontent.com/27221/109876270-e03a5500-7c71-11eb-9317-f1845051d31a.png)
