### ISSUE TITLE
Unable to create the library

### ISSUE THREAD

**Issue by AgtLucas** [vdesabou/alfred-spotify-mini-player#42]
Hi!

I'm trying to create the library, but I'm getting this error: `spot_mini_debug Web API Exception: No ’error’ provided in response body`

Any ideas?

Tks!

**Comment by jon-heller** [comment]
Also receive the same error! This was in my debug.log:
````
DEBUG: The file /Users/hellerj/Library/Application Support/Alfred 2/Workflow Data/com.vdesabou.spotify.mini.player/library.db is not present
The file /Users/hellerj/Library/Application Support/Alfred 2/Workflow Data/com.vdesabou.spotify.mini.player/history.json is not present
The file /Users/hellerj/Library/Application Support/Alfred 2/Workflow Data/com.vdesabou.spotify.mini.player/playqueue.json is not present
Darwin wagyu.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
10.10.1
hw.memsize: 17179869184
````

**Comment by kennonb** [comment]
Running into the same thing too.

**Comment by vdesabou** [comment]
I'm currently investigating this. This has been reported as well by other users.
This error is happening when there is a network issue during update. Is it happening all the times for you ?

**Comment by AgtLucas** [comment]
Yep, all the time. :/

**Comment by vdesabou** [comment]
ok. Are you behind some kind of proxy/firewall and reliable network ?

**Comment by AgtLucas** [comment]
Proxy/Firewall, nops, but my connection is a little slow, though.

**Comment by jon-heller** [comment]
I tested this at two other locations (coffee shop and office) and received the same error there as well

**Comment by vdesabou** [comment]
I have made a beta version where I retry 6 times every 5 seconds if you get error from Spotify server.
Would you be able to test it? Here is the link https://cloudup.com/ccEMbojFOHY

Once installed, Follow steps here http://alfred-spotify-mini-player.com/articles/support/ and choose 'Browse to App Support Folder', then in Finder, delete "library.db" file.

No need to reset settings.


Let me know if this helps or not, if not please send TGZ file

**Comment by kennonb** [comment]
I'm getting a new error now.. "no such table: artists". I sent the debug TGZ via email.

**Comment by vdesabou** [comment]
>I'm getting a new error now.. "no such table: artists". I sent the debug TGZ via email.

Oh, I forgot to tell you to delete both library.db and fetch_artworks.db before re-creating the library.
Can you try that?

**Comment by AgtLucas** [comment]
@vdesabou No joy yet :( 

`There is a problem, the initialization phase last more than 5 minutes`

**Comment by vdesabou** [comment]
>There is a problem, the initialization phase last more than 5 minutes

Can you send by email the TGZ?

**Comment by AgtLucas** [comment]
@vdesabou Done!

**Comment by vdesabou** [comment]
@AgtLucas Thanks. So you had 12 retries, so around 1 additional minute.I've tested with your library, the initialization phase took about 4 minutes on my side, but without any retry. So in your case you had the issue.

In my case it is working, see:

![tmp](https://cloud.githubusercontent.com/assets/4061923/5967741/8c010a6a-a810-11e4-854f-c5f5719d376e.png)

I've increased max init phase from 5 to 30 minutes. Can you try again with this version https://cloudup.com/cX17qMRFHHd

**Comment by vdesabou** [comment]
I've released 6.0.1 version, can everybody (re-)download and install from here http://alfred-spotify-mini-player.com 

Important: follow instructions from [here](http://alfred-spotify-mini-player.com/release-notes/#v6.0.1) after installing the workflow.

Please let me know if library creation is now working properly

**Comment by AgtLucas** [comment]
@vdesabou I think now will work!

![screen shot 2015-01-29 at 9 18 38 pm](https://cloud.githubusercontent.com/assets/1909761/5968246/7fadbc40-a7fc-11e4-9054-70908498606e.png)

:+1:

**Comment by jon-heller** [comment]
Fixed here as well, thank you!

**Comment by kennonb** [comment]
Library seems to be properly indexing. :+1: Thanks @vdesabou!

**Comment by vdesabou** [comment]
Great news thanks all for your help on troubleshooting this!

**Comment by AgtLucas** [comment]
@vdesabou Merci!
