### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by andordavoti** [vdesabou/alfred-spotify-mini-player#420]
After entering my client ID, client secret then when I try to authenticate Spotify I get: INVALID_CLIENT: Invalid redirect URI.

**Comment by vdesabou** [comment]
Check closed tickets like this one for example https://github.com/vdesabou/alfred-spotify-mini-player/issues/405

**Comment by andordavoti** [comment]
Was the redirect URI I didn't set, my bad😅
