### ISSUE TITLE
Disabling Artworks doesnt stop the "Download Artworks.." process

### ISSUE THREAD

**Issue by udit99** [vdesabou/alfred-spotify-mini-player#424]
Steps to recreate: 
1. Settings -> Disable Artworks
2. Retrigger search (1st result still shows the Download Artworks process)

Unsure if this is by design or if its a bug

**Comment by vdesabou** [comment]
Thanks for reporting, it will be fixed in `10.4` version. The issue will be closed when 10.4 is released.
