### ISSUE TITLE
Can play command also play episodes?

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#426]
I want to play this episode. Not sure why it's an episode and not a song (probably due to length)

https://open.spotify.com/episode/4ZjiY5692n0Nev7q38tMvB?si=p8HOpgU0RHONDQC6B0rlEg

If I right click on it, I can get it's Spotify URI which I often use to start playing things instantly from Alfred.

This URI is for this Rain episode: `spotify:episode:4ZjiY5692n0Nev7q38tMvB`.

However it doesn't work.

`[14:52:56.147] Spotify Mini Player[External] Passing output 'spotify:episode:4ZjiY5692n0Nev7q38tMvB' to Run Script`

Get this in console but nothing happens. Can this be supported?

Thanks.

**Comment by vdesabou** [comment]
@nikitavoloboev it will be fixed in 10.4
