### ISSUE TITLE
Unable to "Authenticate to Spotify" in Spotify Mini Player

### ISSUE THREAD

**Issue by wgd05260** [vdesabou/alfred-spotify-mini-player#43]
When I select the "Authenticate to Spotify" after I launch Spotify Mini Player in Alfred my browser displays this message: INVALID_CLIENT: Invalid redirect URI

Please help me. Many thanks!

**Comment by wgd05260** [comment]
Hi! I already solved my issue. Silly of me I forgot to add the Redirect URL when creating my Spotify app. :D

**Comment by vdesabou** [comment]
Ok good !
