### ISSUE TITLE
Incorrect screenshots for creating new Spotify app 

### ISSUE THREAD

**Issue by chrismessina** [vdesabou/alfred-spotify-mini-player#435]
The [setup instructions](https://alfred-spotify-mini-player.com/setup/#download-and-install-the-workflow) are more complex than they need to be as it appears that Spotify has greatly simplified app creation.

After the "Create an app" screenshot, all you need is this:

![image](https://user-images.githubusercontent.com/22610/103143569-762f8d80-46cd-11eb-8fb1-061533cbdf68.png)

**Comment by vdesabou** [comment]
This is now fixed https://alfred-spotify-mini-player.com/setup/
@chrismessina Thanks for reporting the issue !
