### ISSUE TITLE
Confusing process for configuring client ID and secret

### ISSUE THREAD

**Issue by chrismessina** [vdesabou/alfred-spotify-mini-player#436]
I was quite confused as to how to set the client ID and secret. I found the [GIF in the docs](https://alfred-spotify-mini-player.com/setup/#create-the-library) too fast to read. (I would recommend separating each of these steps with their own screenshot)

I specifically found the instructions in the `spot_mini` workflow confusing. The language didn't make it clear that I was supposed to paste my client ID and secret into the Workflow, but that may be because of how I have my theme configured (i.e. to hide result subtext).

It might be clearer to change the primary text, "Your Application Client ID is missing" and "Your Application Client Secret is missing!' to something more like "Paste your Application Client ID" and if the user enters an empty string, then bring them to the documentation page... 

Alternatively, it would be simpler if these variables could just be set in the Workflow's Environment Variables.

**Comment by harrisongoeldner** [comment]
I think perhaps making the variable's set in the environment variables would be more complex in the long run. Every time you reimport the workflow, those variables would get reset. Currently, the variables are stored in a file in Application Support. I do agree though for first time users, it takes a second or two to understand how to get the authentication working.

**Comment by chrismessina** [comment]
> Every time you reimport the workflow, those variables would get reset

Actually, that's not how importing works. Your settings persist after importing the workflow, so if you set the environment variables once, they'll remain set (to the best of my knowledge).

**Comment by vdesabou** [comment]
> The language didn't make it clear that I was supposed to paste my client ID and secret into the Workflow, but that may be because of how I have my theme configured (i.e. to hide result subtext).

That is actually the case as subtext is `Get it from your Spotify Application and copy/paste it here`

> It might be clearer to change the primary text, "Your Application Client ID is missing" and "Your Application Client Secret is missing!' to something more like "Paste your Application Client ID" and if the user enters an empty string, then bring them to the documentation page...

Thanks for the suggestion, I'll probably do that if I don't have time to rework entirely the setup process (I have in mind to "copy" what [Spotifious](https://github.com/citelao/Spotify-for-Alfred) is doing for setup, i.e with a browser redirection that explains the whole setup process directly).

**Comment by chrismessina** [comment]
> Thanks for the suggestion, I'll probably do that if I don't have time to rework entirely the setup process (I have in mind to "copy" what [Spotifious](https://github.com/citelao/Spotify-for-Alfred) is doing for setup, i.e with a browser redirection that explains the whole setup process directly).

Cool, yup. I found Spotificious's setup process pretty intuitive!

Also, I turn off subtext by default,so I don't know if it's wise to rely on that? Not sure what other people do — but that explains some of my confusion!

**Comment by vdesabou** [comment]
> Also, I turn off subtext by default,so I don't know if it's wise to rely on that? Not sure what other people do — but that explains some of my confusion!

In the workflow, there is a lot of useful info in subtexts.

> Cool, yup. I found Spotificious's setup process pretty intuitive!

This will be done as part of Brand new setup #445. I'm closing this one
