### ISSUE TITLE
🖼 Warn before automatically downloading/caching Spotify artwork

### ISSUE THREAD

**Issue by chrismessina** [vdesabou/alfred-spotify-mini-player#438]
It would be appreciated if:

a. there was a warning that downloading Spotify artwork could take days to process (and causes Alfred to be activated when I'm not using my computer)
b. there was a choice offered to enable/disable album artwork support
b. that there was more documentation on how long this process takes and how much storage it takes

This is kind of shocking to see (it's been running pretty continuously since I installed/setup the workflow!):

![CleanShot 2020-12-27 at 14 29 38@2x](https://user-images.githubusercontent.com/22610/103180981-786e2500-4850-11eb-8c95-ab52fa77d32f.png)

**Comment by vdesabou** [comment]
> a. there was a warning that downloading Spotify artwork could take days to
> process (and causes Alfred to be activated when I'm not using my computer)
>

Yes I can add a warning in here
https://alfred-spotify-mini-player.com/setup/
And directly in the message itself

>
> b. there was a choice offered to enable/disable album artwork support
>

It is already available, go to settings and the option is there



> b. that there was more documentation on how long this process takes and
> how much storage it takes
>

It takes a lot of time only when you create the library, after that it only
download ne artworks.
I will see if I can add the storage used somewhere in the workflow



This is kind of shocking to see (it's been running pretty continuously
> since I installed/setup the workflow!):
>

It starts a php process in the background yes, it does not prevent Alfred
to be used in the mean time
In my opinion, it is great to have artworks when you browse your library,
so I don’t plan to disable it by default.
As explained earlier it can be disabled in the settings, it will stop the
background download process and remove all downloaded artworks.
-- 
Vincent de Saboulin

**Comment by chrismessina** [comment]
I'm supportive of downloading and caching the album artwork, I just didn't feel like I was given sufficient notice about how long the process might take (of course it should take some time when I think about it, but I just don't recall being a notice _to_ think about it!).

Even if there was just a warning like:

```
**Download Album Artwork?**
This process may take several hours to complete and a significant amount of disk space.

[ Continue ] [Use without artwork]
```

And yes, it's also good that I can keep using Alfred even while the artwork is being downloaded.

**Comment by vdesabou** [comment]
Added in next version:

<img width="695" alt="Screenshot 2021-01-03 at 11 44 10" src="https://user-images.githubusercontent.com/4061923/103476800-0a2de300-4db9-11eb-888c-5942ca38285e.png">

**Comment by chrismessina** [comment]
@vdesabou note the typo:

![CleanShot 2021-01-03 at 15 52 56](https://user-images.githubusercontent.com/22610/103491844-cbf5eb00-4ddb-11eb-8875-4c2bc2597dd2.png)
