### ISSUE TITLE
Personal sorting of commands

### ISSUE THREAD

**Issue by khenriksson** [vdesabou/alfred-spotify-mini-player#452]
Recently I've been quite bothered with the order the commands pop-up, for example if I write "play" I'd much rather have "play" come before "playlist" and so on, as it's now the fourth command that pops up like this:
![image](https://user-images.githubusercontent.com/35761879/103761313-20d57380-501f-11eb-99c4-adb7c4442ae7.png)

Question: Is it possible to somehow change/sort the order personally?

**Comment by vdesabou** [comment]
Hi @khenriksson, normally Alfred should remember what you selected and present it to you in order, but the workflow contains a bug that prevents that. I'll include the fix in next release
