### ISSUE TITLE
Ugly error message when local client secret doesn't match reset Spotify client secret

### ISSUE THREAD

**Issue by chrismessina** [vdesabou/alfred-spotify-mini-player#454]
I reset my Client Secret and thought that I could just re-authenticate the workflow via Alfred. Turns out I was wrong.

After I granted authorization, I was redirected to the local server and shown this error message, but it should probably be given a max width, instead of extending off the page:

```
Error message: There was an error during the authentication (exception SpotifyWebAPI\SpotifyWebAPIAuthException: Invalid client secret at SpotifyWebAPI.Request.parseBody(Request.php:49) at SpotifyWebAPI.Request.send(Request.php:244) at SpotifyWebAPI.Request.account(Request.php:101) at SpotifyWebAPI.Session.requestAccessToken(Session.php:217) at (main)(callback.php:28))
```

Seen here in context:

![image](https://user-images.githubusercontent.com/22610/103937570-c4855900-50dd-11eb-8420-ad008d30da5a.png)

Additionally, the subtext in the message "Authenticate to Spotify" message is also strange: "Not Available"? It's not clear what that refers to:

![CleanShot 2021-01-07 at 11 45 27@2x](https://user-images.githubusercontent.com/22610/103937631-e252be00-50dd-11eb-8f4d-d451e1232b19.png)

I also made some tweaks to the text in these pages in #453.

**Comment by vdesabou** [comment]
> I reset my Client Secret and thought that I could just re-authenticate the workflow via Alfred. Turns out I was wrong.

I opened "Add option to enter new client secret #457" to make it easier

> After I granted authorization, I was redirected to the local server and shown this error message, but it should probably be given a max width, instead of extending off the page

Yes this page is very raw. I'm not an expert in HTML/CSS, feel free to do a PR if you want ;) 

> Additionally, the subtext in the message "Authenticate to Spotify" message is also strange: "Not Available"? It's not clear what that refers to:

This only shows up when you press a modifier key (cmd, alt, etc..) while the result is selected. See this article https://alfred-spotify-mini-player.com/articles/modifier-keys/ for how it is used by the workflow.

The "Not Available" message means there is no modifier action associated to this result. If you have better suggestions, let me know :D

**Comment by chrismessina** [comment]
> > After I granted authorization, I was redirected to the local server and shown this error message, but it should probably be given a max width, instead of extending off the page
> 
> Yes this page is very raw. I'm not an expert in HTML/CSS, feel free to do a PR if you want ;)

Ok!
 
> > Additionally, the subtext in the message "Authenticate to Spotify" message is also strange: "Not Available"? It's not clear what that refers to:
> 
> This only shows up when you press a modifier key (cmd, alt, etc..) while the result is selected. See this article https://alfred-spotify-mini-player.com/articles/modifier-keys/ for how it is used by the workflow.
> 
> The "Not Available" message means there is no modifier action associated to this result. If you have better suggestions, let me know :D

Can you leave it blank? I'm familiar w/ modifiers — but "Not Available" doesn't really seem appropriate. Typically when I hit a modifier key but there's no alternative action, nothing is shown.

**Comment by vdesabou** [comment]
Closing. No plan to fix this
