### ISSUE TITLE
Send Debug email doesn't create an email

### ISSUE THREAD

**Issue by GeoJunkie** [vdesabou/alfred-spotify-mini-player#462]
I received an error notice: `Web API Exception: 400 - Failed to get client`. It gave me the option to send the debug email, and while I got the information in my clipboard, my email app never opened and a new message was never created, even with the email app running.

I'm using Alfred 4.3 [1205] on MacOS Big Sur 11.1 (20C69)

**Comment by vdesabou** [comment]
Thanks I can reproduce the issue. I am using Big Sur as well.

**Comment by gimbo** [comment]
I'm getting this under Mojave 10.14.6 (18G7016), with the same version of Alfred (4.3 [1205]).

**Comment by vdesabou** [comment]
Thanks, yes it is a big that will be fixed in next release
