### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by mattiacolombomc** [vdesabou/alfred-spotify-mini-player#464]
Hello, as title, I get the following error:
`INVALID_CLIENT: Invalid redirect URI`
Can you help me? I tried to do the setup multiple times, but I didn't get any success (I obviously reset the app via Alfred). I followed your instructions step by step.
Could you help me? Thanks in advance.

**Comment by vdesabou** [comment]
You probably did not click on the SAVE button in your Application page

Make sure to follow carefully the steps from Setup http://alfred-spotify-mini-player.com/setup/
