### ISSUE TITLE
Open Spotify on notification click

### ISSUE THREAD

**Issue by cgrs** [vdesabou/alfred-spotify-mini-player#465]
It'd be nice to get Spotify open when clicking the notification, just like [citruspi/Spotify-Notifications](https://github.com/citruspi/Spotify-Notifications) does.

**Comment by vdesabou** [comment]
This is currently the expected behaviour: when you click on a notification, it should open Spotify Desktop

![CleanShot 2021-01-19 at 18 06 03](https://user-images.githubusercontent.com/4061923/105068246-02d92b80-5a81-11eb-8057-5adc669d4313.jpg)

**Comment by cgrs** [comment]
It doesn't work for me, maybe it's something exclusive on Big Sur?
If you need any details:
macOS Catalina 10.15.7 (19H15)
Alfred 4.3 [1205]
Spotify Mini Player 10.6

**Comment by vdesabou** [comment]
Can you show me a screenshot of your notifications ? Does it show Spotify mini player icon ?

**Comment by cgrs** [comment]
Here you have:
![image](https://user-images.githubusercontent.com/5529103/105330412-88b8bc00-5bd2-11eb-968a-c8130f0b2546.png)

**Comment by vdesabou** [comment]
closing in favour of #583
