### ISSUE TITLE
Unable to add song to queue

### ISSUE THREAD

**Issue by jumban** [vdesabou/alfred-spotify-mini-player#471]
When adding any song to the play queue using opt+cmd modifier, nothing happens. Also unable to see "Play Queue" in the main window. I also have Spotify Connect enabled with a default device selected. Screenshots are attached below. Thanks! 

Using: v10.6

![image](https://user-images.githubusercontent.com/32335357/105955228-e789a400-60b0-11eb-8b54-1b8902aee7f8.png)
![image](https://user-images.githubusercontent.com/32335357/105955407-333c4d80-60b1-11eb-9d9d-7c50220b500c.png)

**Comment by jumban** [comment]
I believe my issue may be a duplicate of #433

**Comment by vdesabou** [comment]
Yes it is
