### ISSUE TITLE
Change user name

### ISSUE THREAD

**Issue by yuheem** [vdesabou/alfred-spotify-mini-player#475]
When spotify mini player is opened is there any way to change the name of the current user (Under Settings > Switch User)? Also is there a way to delete users which have beend added? I can't seem to find any options for these. Also would like to know the path of where the settings files are stored locally.

**Comment by vdesabou** [comment]
You can do this by going into the App Support folder

Choose this option:

![CleanShot 2021-02-27 at 08 49 38](https://user-images.githubusercontent.com/4061923/109381166-e8dd0500-78d8-11eb-8b22-84fe4c075e17.jpg)

Then in `users` directory, you can rename the folder to rename the user or delete it to remove user:

![CleanShot 2021-02-27 at 08 50 02](https://user-images.githubusercontent.com/4061923/109381182-001bf280-78d9-11eb-9f41-3218fbd9e64c.jpg)

**Comment by yuheem** [comment]
Thanks a lot!
