### ISSUE TITLE
Notifications have Terminal Notifier icon

### ISSUE THREAD

**Issue by babramczyk** [vdesabou/alfred-spotify-mini-player#477]
When a notification pops up it shows stars (out of 5) — what does that signify?

Also, is there future in which the notification has some kind of logo (like spotify, or the one for this particular workflow) as opposed to the Terminal Notifier default?

**Comment by tomcoakes** [comment]
In the documentation it's described as "track popularity" - https://alfred-spotify-mini-player.com/articles/now-playing/

**Comment by vdesabou** [comment]
Yes it is track popularity. You can disable it if you want.

For the terminal notifier icon, that should not happen normally, it is likely a permission problem, can you click on the option highlighted below to force Mac OS to open the right app used for notifications:

![CleanShot 2021-03-11 at 07 56 27@2x](https://user-images.githubusercontent.com/4061923/110747992-6e4ca780-823f-11eb-846b-6ce936c289a8.jpg)

**Comment by babramczyk** [comment]
Did that. It’s no longer terminal notifier, but the icon is still effed

![image](https://user-images.githubusercontent.com/16885191/110788139-deedc700-8233-11eb-9bf5-2e90e56ded2e.png)

**Comment by vdesabou** [comment]
@babramczyk I had the same behaviour after upgrading to Big Sur, but after a short while (probably after a reboot), it was working as before. Do you still have same issue?

**Comment by babramczyk** [comment]
@vdesabou I actually disabled notifications and started relying on this instead:

[citruspi/Spotify-Notifications: Bridging Spotify and macOS Notification Center](https://github.com/citruspi/Spotify-Notifications)

**Comment by vdesabou** [comment]
Cool. Closing the
