### ISSUE TITLE
Feature: Allow Allfred Playlist to use Shared Playlist

### ISSUE THREAD

**Issue by billyromano** [vdesabou/alfred-spotify-mini-player#478]
The Alfred Playlist setting allows you to set a quick default playlist to play, like a shortcut. The current functionality only allows private playlists to be selected which requires the user to create a custom playlist. 

I'd like to propose changing this to allow both private and public playlists to be selected which is similar to the browse playlist functionality already setup in this mini player. I use a lot of public/shared playlists for my music and my most used playlist is the "Discover Weekly" playlist that's auto generated by Spotify based on the music I listen to. It would be great to have this as a quick shortcut which saves a few steps in mini player experience.

**Comment by vdesabou** [comment]
You can already choose any private, public or collaborative playlist that you own as Alfred playlist. You must own the playlist.
"Discover Weekly" playlist is a specific playlist that is not manageable with Spotify Web API, so the workflow cannot use it.

Will have to close this ticket, unless this is not what you meant?
