### ISSUE TITLE
spot_mini_debug Web API Exception: No ’error’ provided in response body

### ISSUE THREAD

**Issue by mikeohara** [vdesabou/alfred-spotify-mini-player#48]
I get this error when it first starts generating the library it gets about 20 seconds in, ( fair sized library to create from Spotify, total about 10k tracks).

I've tried restarting Spotify, restarting Alfred, I've blown away the settings 5 times, I've even removed and readded the workflow a couple of times.

No changes. 

I am a spotify premium user
Yosemite 10.10.1
Alfred 2.6 (374)
Spotify Mini Player version 6.0

**Comment by vdesabou** [comment]
A lot of users are experiencing this issue as well, this is under investigation..I'll get back to you once I have more information

**Comment by mikeohara** [comment]
Good (well not really) news, at least I am not the only one!

Looking forward to the update.

**Comment by vdesabou** [comment]
I have made a beta version where I retry 6 times every 5 seconds if you get error from Spotify server.
Would you be able to test it? Here is the link https://cloudup.com/ccEMbojFOHY

Once installed, Follow steps here http://alfred-spotify-mini-player.com/articles/support/ and choose 'Browse to App Support Folder', then in Finder, delete "library.db" file.

No need to reset settings.


Let me know if this helps or not, if not please send TGZ file

**Comment by mikeohara** [comment]
So far, it successfully completed the library generation and has moved on
to artwork download. So far so go. will update further as it completes.

**Comment by vdesabou** [comment]
>So far, it successfully completed the library generation and has moved on
to artwork download. So far so go. will update further as it completes.

Great! I'm interested in getting the TGZ file even if it is working, to see how many retries happened

**Comment by mikeohara** [comment]
The artwork generation will take quite some time. It has been running since
I emailed, and is only 2000 into the 9600 or so. Here is the tgz regardless

**Comment by vdesabou** [comment]
>The artwork generation will take quite some time. It has been running since

Yes that's why I made the download in background, it does not prevent you to use the workflow, which is quite nice :smile: 

I did not receive the TGZ yet

**Comment by mikeohara** [comment]
https://www.dropbox.com/s/cw83pdxxk64aasc/spot_mini_debug.tgz?dl=0

**Comment by vdesabou** [comment]
Thanks.
Everything looks good, you had 6 retries during the creation of library, but now it is transparent to user..
I really don't know why I never got this error before, maybe because I'm based in Paris and Spotify servers are different..

Anyway thanks for the beta testing. I'll release 6.0.1, you will have to download it again and install it (no need to re-install anything after).

**Comment by mikeohara** [comment]
Thanks!

**Comment by vdesabou** [comment]
I've released 6.0.1 version, can you re-download and install from here http://alfred-spotify-mini-player.com

**Comment by mikeohara** [comment]
Issues resolved. Thanks!

**Comment by BenJP51** [comment]
Spot_Mini v7.0, Alfred v3.2.1, MacOS v10.12.3

Getting error too. Let me know if there is a way to update or fix this. Thanks.
