### ISSUE TITLE
Disable song change notifications.

### ISSUE THREAD

**Issue by drewswaycool** [vdesabou/alfred-spotify-mini-player#485]
My notification center gets flooded with "now playing" notifications.

**Comment by drewswaycool** [comment]
Found the option - pretty hidden feature. Maybe I just don't know how to Alfred.

**Comment by domabe** [comment]
@drewswaycool hey how did you manage to achieve this?

**Comment by vdesabou** [comment]
See https://alfred-spotify-mini-player.com/articles/now-playing/
