### ISSUE TITLE
Since I changed my password it does not work at all.

### ISSUE THREAD

**Issue by mistywidow** [vdesabou/alfred-spotify-mini-player#487]
Hello,
I have changed the spotify password because I got a concern that someone tried to login my spotify account.
Then this player stopped working correctly. 
It only displays "Reset Settings", "Spotify mini player", "kill update library", "Report an issue" and "Debug tools".
The everything does not work at all. 
Reset settings does nothing, seems stopping forever.
Report an issue says Code 255: Exited with error code but no message.
How can I reset it? Any tips to fix it?
Thank you.

**Comment by vdesabou** [comment]
Can you send me a debug email as explained there
https://alfred-spotify-mini-player.com/articles/support/

**Comment by vdesabou** [comment]
can you try to select this option:

![CleanShot 2021-03-25 at 08 56 57@2x](https://user-images.githubusercontent.com/4061923/112438350-17b79100-8d48-11eb-9a46-d9b29b466c21.jpg)

**Comment by vdesabou** [comment]
Closing. If you still need help, let’s continue by email when you send me the debug email

**Comment by mistywidow** [comment]
Hello,

Thank you for your response.
I cannot select the option that does not show up.


And even if I try select the debug tools it just stops and goes to "google search”.



2021年3月25日 16:57 +0900、Vincent de Saboulin ***@***.***> のメール:

**Comment by vdesabou** [comment]
Please try to install latest version. Settings are now in Alfred environment:
![CleanShot 2021-03-31 at 11 28 57](https://user-images.githubusercontent.com/4061923/113122881-55b72800-9214-11eb-9e7a-7e6c96564b03.jpg)

I think that will help tin your case

**Comment by mistywidow** [comment]
Thank you so much for your support.
Now everything is working great.
2021年3月31日 18:30 +0900、Vincent de Saboulin ***@***.***> のメール:
