### ISSUE TITLE
How could I save / remove the current song to the "Liked Songs" via Mini Player?

### ISSUE THREAD

**Issue by FleXoft** [vdesabou/alfred-spotify-mini-player#497]

**Comment by vdesabou** [comment]
Please have a look here https://github.com/vdesabou/alfred-spotify-mini-player/issues/406#issuecomment-703056481

And check #494

**Comment by FleXoft** [comment]
[#406 (comment)](https://github.com/vdesabou/alfred-spotify-mini-player/issues/406#issuecomment-703056481) helped. Thanks.
