### ISSUE TITLE
Invalid URL error

### ISSUE THREAD

**Issue by muellers-buero** [vdesabou/alfred-spotify-mini-player#498]
This error has been discussed before. The solution four years ago was that client ID and client secret were not saved. I assume that I have correctly saved the information.
<img width="468" alt="test" src="https://user-images.githubusercontent.com/49828687/115997278-e3532100-a5e2-11eb-8fcc-656915ca2c83.png">
However, when I now try to authenticate my application, the link it is trying to reach is
http://127.0.0.1:15298/setup.php,
and the error message I get obviously is
INVALID_CLIENT: Invalid redirect URI
Where is my fault?
Many thanks for your help!
Andreas

**Comment by vdesabou** [comment]
Check here for example https://github.com/vdesabou/alfred-spotify-mini-player/issues/464

**Comment by muellers-buero** [comment]
Checked. This is why I opened a new thread.

Sorry for bothering you.

Andreas

**Comment by vdesabou** [comment]
You don’t bother me at all 😊
There is only one reason to get this errror. If you didn’t set properly the redirect url or if you did not click save.
I have never seen a different reason in 7 years.
Can you triple check that you did it correctly ?

**Comment by vdesabou** [comment]
@muellers-buero Do you still get the issue ?

**Comment by muellers-buero** [comment]
Thank you very much for your enquiry!

IT IS RUNNING NOW!!!!

I have just (1 min ago) solved the last issue. This was that no changes were made when I used Alfred. My fault! I probably overlooked somewhere that your great workflow is only running together with the app, not with the browser.

Prior to this my wife and I repeated all necessary steps together. I think that at one step when creating the Spotify application you have to save some information. This is what I most likely did not do. So I had all the relevant information but this save step was missing.

Thank you very much for your help!

With best wishes

Andreas
