### ISSUE TITLE
Song Radio no longer works for me on new Spotify versions

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#499]
Just does nothing. Get this in debugger when activated:

```
[02:19:15.093] Spotify Mini Player[Keyword] Processing complete
[02:19:15.094] Spotify Mini Player[Keyword] Passing output '' to Run Script
```

This is the command:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/6391776/116798126-dce60d00-aaec-11eb-92af-9bc9ca1018eb.png">

Could it because of this?

<img width="693" alt="image" src="https://user-images.githubusercontent.com/6391776/116798129-e7080b80-aaec-11eb-87d1-9c330d8b43b9.png">

It started some time ago but never finished, not sure what's up there.

I am on version 10.8 of workflow.

**Comment by vdesabou** [comment]
Yes, that is probably the reason.
You can kill the library update by using spot_mini_kill.. command
If that happens again, send me a debug email.

Also 10.8 is quite old, you can upgrade to latest 10.15

**Comment by nikitavoloboev** [comment]
Updating and killing the update progress made radio work, thanks :)
