### ISSUE TITLE
Can't create library

### ISSUE THREAD

**Issue by hiltronrex** [vdesabou/alfred-spotify-mini-player#500]
Hey guys, 

I have tried to install the script but can not get passed create library. 

![image](https://user-images.githubusercontent.com/16205620/117742159-7927b680-b247-11eb-898b-3df8b6ac25ed.png)

I select it but nothing happens and i never see the progress like in the picture. 

What is your suggestion?

Thanks

**Comment by cynthiapereira** [comment]
I have almost the same problem. I can't even begin to create the library.

**Comment by vdesabou** [comment]
Can you share some screenshots of what you see?

**Comment by cynthiapereira** [comment]
Now it's working for me. I guess it is taking a while for the app created on Spotify retrieve data. 

This is what happened:
I clicked “create library...”, went through the dialogue box until “enable artwork...” appeared then, nothing. I could go back and forward in this process without any info appearing. After 30 minutes, I tried one more time and, after selecting “create library”, the “loading bar” appeared. I waited until finish loading and now it's running smooth.

**Comment by Ryan-Efendy** [comment]
@vdesabou I have a similar issue. In my Intel Macbook I was able to set it up, create library etc but in my M1 Macbook I'm stuck in create library.

<img width="423" alt="Screen Shot 2021-05-23 at 9 51 11 AM" src="https://user-images.githubusercontent.com/12979345/119269404-69e02b80-bbac-11eb-9443-6a90cfec459a.png">

<img width="416" alt="Screen Shot 2021-05-23 at 9 51 25 AM" src="https://user-images.githubusercontent.com/12979345/119269416-72386680-bbac-11eb-8422-6396c4840652.png">

<img width="418" alt="Screen Shot 2021-05-23 at 9 51 39 AM" src="https://user-images.githubusercontent.com/12979345/119269420-79f80b00-bbac-11eb-96be-a495c7ec55d6.png">

and then I'm back to the "create library" dialog.. and then "enable shows"...

**Comment by vdesabou** [comment]
For those having this issue, please send me an email as explained in https://alfred-spotify-mini-player.com/articles/support/

**Comment by vdesabou** [comment]
One user had this issue:


the security permissions prevented fzf from running.. 

had to manually open it for OSx to 'approve' it...:

select this:

![CleanShot 2021-06-16 at 14 59 12](https://user-images.githubusercontent.com/4061923/122223437-727a0800-ceb3-11eb-91ad-fcc283357dd5.jpg)

and then open fzf in Finder:

![image](https://user-images.githubusercontent.com/4061923/122223357-5fffce80-ceb3-11eb-8e9a-7f7e53f315c3.png)

**Comment by vdesabou** [comment]
I identified an issue if you select No to "enable Podcasts", in that case nothing happened. I'm pushing a fix in `10.16`
