### ISSUE TITLE
Cannot find a dialogue box that allows me to input my Client ID and Client Secret ID

### ISSUE THREAD

**Issue by davidtesler** [vdesabou/alfred-spotify-mini-player#503]
I am following all of the instructions - nowhere is there a box that opens up allowing me to input my Client ID and Client Secret ID

**Comment by vdesabou** [comment]
it should be there

![CleanShot 2021-05-27 at 18 09 41](https://user-images.githubusercontent.com/4061923/119860572-c037cc00-bf16-11eb-96ee-5a5ef4040c18.jpg)
