### ISSUE TITLE
Add a modifier action to remove navigated (not currently playing) track from a playlist

### ISSUE THREAD

**Issue by glortho** [vdesabou/alfred-spotify-mini-player#504]
It works like a charm with current track, but I'd like to be able to navigate to a particular track in mini player and then act on it to remove from a given playlist. Is this possible?

**Comment by vdesabou** [comment]
That is not possible right now but it should  be doable with modifiers keys. I just need time to work on it, and time is difficult to find at the moment 😌

**Comment by vdesabou** [comment]
That will be available in `10.17`

* Select a track with `⌘+fn` (cmd + function key) to remove the track from either _Your Music_, or any of your playlists

**Comment by glortho** [comment]
Awesome thank you! ✨
