### ISSUE TITLE
Stuck on "Refresh Library"

### ISSUE THREAD

**Issue by jumban** [vdesabou/alfred-spotify-mini-player#505]
The Alfred Spotify Mini Player is stuck on "Refresh Library in progress" as seen from the image below. Restarting the machine did not help, it still shows up that way. 

The option to recreate library is also missing in Settings (I am guessing because the refresh library is in progress?)

![image](https://user-images.githubusercontent.com/32335357/121984385-77608e00-cdc5-11eb-8119-0b682fc67b0f.png)

Any help will be greatly appreciated!

My Environment:
Alfred Spotify Mini Player: v10.8
MacOS: Catalina 10.15.7

**Comment by vdesabou** [comment]
Please do the following:

1. Execute `spot_mini_kill` in order to kill the library update
2. Update to talent version the workflow `10.15`
3. Refresh your library again

If you still get issues, send me a debug ZIP file as explained [here](https://alfred-spotify-mini-player.com/articles/support/)
