### ISSUE TITLE
Add "Fix permissions" command (for fzf, terminal-notifier and Spotify Mini Player app)

### ISSUE THREAD

**Issue by mohitgoyal707** [vdesabou/alfred-spotify-mini-player#506]
Hi,

![image](https://user-images.githubusercontent.com/5231466/123088302-31e63580-d443-11eb-9e26-ec6113451a1b.png)

I am getting this error. When I open the privacy preferences and click on "Allow anyways", it still doesn't work

**Comment by madchap** [comment]
The same. I am unfamiliar with how the app works, but I have `fzf` already installed on my system with brew. Maybe it could somehow reuse it?

**Comment by vdesabou** [comment]
fzf is only used if you use "Fuzzy search". Normally when you Enable the feature in Settings, it should remove the quarantine attribute, and prevent that message.

Can you try to disable and then re-enable Fuzzy search ?

**Comment by bradleycwojcik** [comment]
I was experiencing the same issue and was able to resolve it by enabling fuzzy search as you suggested above. Steps to repro:

1. Activate spot mini workflow with hotkey
2. Scroll through default results and select Settings (filtering for Settings by typing the letters results in the same error, of course)
3. Scroll down and select Enable Fuzzy Search

After this I no longer had issues. Thanks!

**Comment by vdesabou** [comment]
That’s really interesting. So for 2/, it’s only when you start typing that you got the issue?

Another solution to test if someone else has the issue is explained here: https://github.com/tilmanginzel/alfred-bluetooth-workflow/issues/9#issuecomment-691705659

**Comment by G-S-Paris** [comment]
is there any way we can get visibility into the contents of 'fzf'?

**Comment by G-S-Paris** [comment]
ah, nevermind, I think I found it. Commit #404 links the following:  https://formulae.brew.sh/formula/fzf

**Comment by vdesabou** [comment]
I'm going to add a fix permissions command, in an attempt to fix those permission issues:

![CleanShot 2021-07-27 at 09 51 15](https://user-images.githubusercontent.com/4061923/127117072-8f7388ca-b0b9-4e1c-a932-328a51d5b673.jpg)

![CleanShot 2021-07-27 at 09 51 50](https://user-images.githubusercontent.com/4061923/127117127-831685d1-982b-4bee-ad8e-0a53339ff64f.jpg)
