### ISSUE TITLE
Remapping of Media keys?

### ISSUE THREAD

**Issue by chrisgrieser** [vdesabou/alfred-spotify-mini-player#507]
Is it possible to remap the Media Keys (the ones on F7, F8, and F9) to control Spotify Mini Player? After a while I noticed that I could uninstall the Spotify Desktop app, as I used the Mini Player for basically everything already. 

However, the three media keys do not work with the Mini Player. I know it is possible to just manually assign a Hotkey Playpause/Next/Previous in the Workflow settings; but doing so uses up three keys while F7-F9 remain as dead keys.

For the Spotify desktop app, the [Media Key Forwarder](https://github.com/milgra/macmediakeyforwarder) did the job, so I assume that such a media key remapping would be possible for the Spotify Mini Player as well?

**Comment by vdesabou** [comment]
Hey @chrisgrieser !

This is completely out of scope of the workflow unfortunately. Doing a quick google search, maybe Karabiner can help ? https://www.alfredforum.com/topic/9190-remap-a-key/
