### ISSUE TITLE
Nothing happens while pasting client id

### ISSUE THREAD

**Issue by mnedoszytko** [vdesabou/alfred-spotify-mini-player#51]
Latest version of the workflow (6.021) try to paste the client id, enter, shiftenter, right arrow.., nothing happens, no debug info .Yosemite 10.10.1 alfred 2.6 (374)
![zrzut ekranu 2015-02-01 o 12 51 48](https://cloud.githubusercontent.com/assets/2605478/5991968/21c97d82-aa11-11e4-8825-16edd70fbb85.png)

**Comment by vdesabou** [comment]
Hi, can you copy paste everything you have in the Alfred windows ?

Vincent

**Comment by mnedoszytko** [comment]
do you mean the preferences? which tabs?

**Comment by vdesabou** [comment]
When you copy paste the client id in Alfred window.
Did you have a look at http://alfred-spotify-mini-player.com/setup/ ? The GIF is showing you how to do

Vincent

**Comment by mnedoszytko** [comment]
of course i did.
i set up my new app in spotify account, got my client id and secret id, then i open the workflow using either my shortcut (cmd+ctrl+tenter) or spot_mini in alfred and then see as on the first screenshot, i try to paste the client id, push enter, nothing happens




Sent with Unibox

**Comment by vdesabou** [comment]
Ok so once you pasted the client Id, can you select everything cmd-A and copy cmd-C and copy results here

Vincent

**Comment by mnedoszytko** [comment]
I pasted the client id, nothing happens, so if i cmd-a cmd-c on current focus i'll just paste you the client id , if you want the debug window, this is what we get. but still - pressing enter doesn't yield any action

![zrzut ekranu 2015-02-01 o 15 15 24](https://cloud.githubusercontent.com/assets/2605478/5992331/4d1a16c2-aa25-11e4-9761-bdfc9b78dff1.png)

**Comment by vdesabou** [comment]
Also are you using American keyboard or something other, that might be the cause of problem maybe..

Vincent

**Comment by mnedoszytko** [comment]
nope, this is a standard EU mac, with polish programmers input, no other alfred workflow has problem recognising the ‚return’ input. do you have some sort of triggering on pasting the client id, maybe there’s some network logic which stalls without any visual indication?




Sent with Unibox

**Comment by vdesabou** [comment]
When you have Your application Client ID is missing message, and the possibility to open web page, it means there is nothing entered in Alfred input field, example:

![tmp](https://cloud.githubusercontent.com/assets/4061923/5992939/1a8f345c-aa3f-11e4-893a-a434085be788.png)

Once you enter something, then it should change, here the length is not correct, hence the error message:

![tmp2](https://cloud.githubusercontent.com/assets/4061923/5992942/33ad12c4-aa3f-11e4-9d93-58450968e1ff.png)

So your case where you have some text entered but nothing happened is really strange to me....It does not make any sense

Can you try to enter just a few letters as in my example, to see if you get same error message or not?

**Comment by mnedoszytko** [comment]
nope. nothing happens. see screenshot below:


![zrzut ekranu 2015-02-01 o 18 27 08](https://cloud.githubusercontent.com/assets/2605478/5992964/fe6b4666-aa3f-11e4-9853-a1c655cd08ce.png)

**Comment by vdesabou** [comment]
At this point, I can't see anything wrong other than something wrong with Alfred..Can you try restart Alfred or even reboot your computer?

**Comment by mnedoszytko** [comment]
I did, honestly. I can try to reinstall alfred. I tried to backtrack this in your menu.php, but am not to keen on debugging workflows.

**Comment by vdesabou** [comment]
ok..
Can you install this DEBUG version https://cloudup.com/caYO6uXbGqZ
you should see, something like:

![tmp3](https://cloud.githubusercontent.com/assets/4061923/5993069/f3b21782-aa43-11e4-8bd1-d46684178a11.png)

Try to type a few letters and tell me what you see as DEBUG

**Comment by mnedoszytko** [comment]
ok, so mb_strlen is 0, could it be something with php parser. which one does it use?

![zrzut ekranu 2015-02-01 o 18 57 36](https://cloud.githubusercontent.com/assets/2605478/5993079/4b541e54-aa44-11e4-912a-554084757512.png)

**Comment by mnedoszytko** [comment]
ok, man I got some progress here, I changed my php parser so it points to 5.4.24 and suddenly mb_strlen started to work, shall we dig deeper?
![zrzut ekranu 2015-02-01 o 19 07 07](https://cloud.githubusercontent.com/assets/2605478/5993118/a8527bb8-aa45-11e4-8a95-9720e0906b46.png)

**Comment by vdesabou** [comment]
Ok can you try again with this one https://cloudup.com/cVGxffbOafz

**Comment by vdesabou** [comment]
>ok, man I got some progress here, I changed my php parser so it points to 5.4.24 and suddenly mb_strlen started to work, shall we dig deeper?

Ok so it seems to have fixed the problem then!
How do you exactly did that (change PHP parser) ?

**Comment by mnedoszytko** [comment]
I changed the path in my ~/.profile and restarted alfred.
now - funny thing is that any php version works. Maybe you should do some additional verification if multibyte string functions are supported on clients configuration ?

**Comment by mnedoszytko** [comment]
with this new download the result seems like this with the MAMP's 5.4.26. I'll look into some more, but for now I can't reproduce the problem anymore.
![zrzut ekranu 2015-02-01 o 19 21 25](https://cloud.githubusercontent.com/assets/2605478/5993189/b839bf4e-aa47-11e4-8017-1c1942b30b07.png)

**Comment by vdesabou** [comment]
>now - funny thing is that any php version works. Maybe you should do some additional verification if multibyte string functions are supported on clients configuration ?

I can have a look but don't know much in this area. If you know, you're more than welcome to do some pull request!

At the beginning, I'm doing:

```
$query = iconv('UTF-8-MAC', 'UTF-8', $query);
```
No sure if it can impacts something here
It was because of this discussion http://www.alfredforum.com/topic/1788-prevent-flash-of-no-result
