### ISSUE TITLE
Shuffle status is not remembered

### ISSUE THREAD

**Issue by chrisgrieser** [vdesabou/alfred-spotify-mini-player#512]
Not entirely sure when this occurs, but it seems the status of shuffle is regularly resetted to "deactivated". 
When I activate shuffle once more, after a while is deactivated again.

**Comment by vdesabou** [comment]
I'm going to close this one, there is nothing I can do about that, the workflow is just enabling/disabling the shuffle state using Spotify Web API (if you use Spotify Connect) or Applescript. Therefore if state disappears, it can only be a Spotify issue to report to them

Cheers
