### ISSUE TITLE
Nothing will work

### ISSUE THREAD

**Issue by StarryFoxx** [vdesabou/alfred-spotify-mini-player#513]
I've uninstalled Alfred, deleted any cache or trace of alfred. Whether I hotkey or type the spot_mini keyword, nothing will work. I'm not sure what's going on. I've followed all the steps and numerous others.

**Comment by laestrella26** [comment]
Same issue. I can't get to the part to launch the authentication process.

**Comment by vdesabou** [comment]
Please send me both a debug email as explained here https://alfred-spotify-mini-player.com/articles/support/

**Comment by laestrella26** [comment]
The action won't even run to generate the debug email. I think that's part
of the issue. It could be that the workflow isn't compatible with Monterey.
That's what I'm using.

**Comment by vdesabou** [comment]
oh yes it's not compatible with Monterey, see https://github.com/vdesabou/alfred-spotify-mini-player/issues/508
