### ISSUE TITLE
Is there any way to play a local song?

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#517]
If I have a local song like this one:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/6391776/127369436-b9db8562-23db-48a1-9431-32e3df7db144.png">

There is no way to get it's share link that I can find.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/6391776/127369494-0536beb7-e165-49ec-baf4-09832297a533.png">

Is there any way I can play a certain song locally from the workflow? Ideally so I can bind it to a hotkey. 

Thanks.

**Comment by vdesabou** [comment]
I think this is still best effort, as per my comment there https://github.com/vdesabou/alfred-spotify-mini-player/issues/222#issuecomment-355906764

**Comment by nikitavoloboev** [comment]
Ooops, for some reason searching for `local` didn't bring that issue up :D 

Going to try something else for now. Thanks again. ❤️

**Comment by nikitavoloboev** [comment]
For now it's this KM macro that manually automates mouse clicks for me:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/6391776/127372929-a0737f32-9223-4a30-8d72-878d11c7acb4.png">

**Comment by nikitavoloboev** [comment]
Actually nvm all that. Here is solution that truly works:

Create playlist and add the offline song to it.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/6391776/127381740-cc57b973-43e4-421b-8db8-58d034d9c238.png">

Then get the playlist URL and just play that from workflow.
