### ISSUE TITLE
Enhancement Suggestion

### ISSUE THREAD

**Issue by ericsoup** [vdesabou/alfred-spotify-mini-player#519]
Hi there,

Your mini player is fantastic.  

It would be cool to be able to mark a song as LIKED from alfred.  (as far as I can tell this is not currently possible).

I would be nice to be able to just assign a hot key so that a song could be quickly marked as liked instead of needing to go to the app and click the heart icon.  

Thanks again.

**Comment by vdesabou** [comment]
A song that is liked (heart in Spotify desktop) is basically adding the track in « your music » in the workflow. See https://alfred-spotify-mini-player.com/articles/alfred-playlist/ for how to quickly control your music using the workflow.

also there are direct commands to add or remove tracks from your music, see https://github.com/vdesabou/alfred-spotify-mini-player/issues/494

**Comment by ericsoup** [comment]
Amazing.  Thank you so much!  Such a simple solution.  I really appreciate it.
