### ISSUE TITLE
Prioritise song and artist in search rather than playlist

### ISSUE THREAD

**Issue by kenanmike** [vdesabou/alfred-spotify-mini-player#520]
Whenever I search 'online'  through the mini player, it comes up with all these playlists by random people, rather than yielding song and artist search results. I want to see in the alfred player the results similar to what would come up in Spotify. 
For example see these results for '7 days' in the mini player compared to spotify in the screenshot. I would want to see the song 7 Days by Craig David come up as near the top of the search results as it would on Spotify, Google, etc., rather than someone's playlist called 7 Days.

![image](https://user-images.githubusercontent.com/85374001/130352623-05e740dc-f24a-4e3d-ba9f-e40a1def9a2b.png)

VS

![image](https://user-images.githubusercontent.com/85374001/130352631-38428560-36ce-4a43-9591-83492881f2d3.png)

**Comment by vdesabou** [comment]
That should already be working if you change search order in the workflow settings. Let me know if that works for you

**Comment by kenanmike** [comment]
Thanks very much for your reply. I had looked at the workflow settings but unfortunately I can’t find which item in the workflow settings I need to change - can you drop a screenshot?

**Comment by vdesabou** [comment]
![CleanShot 2021-08-22 at 15 25 03@2x](https://user-images.githubusercontent.com/4061923/130356900-eb6f097c-05e5-4819-a627-6ce1e6a1d533.jpg)

**Comment by kenanmike** [comment]
Great, got it and works much better now! 
Thanks so much 🙌
