### ISSUE TITLE
Looking for beta-testers !

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#537]
I've requested an[ Extended Quota Mode](https://developer.spotify.com/community/news/2021/05/27/improving-the-developer-and-user-experience-for-third-party-apps/) for my workflow, so that users don't have to create their Spotify Application anymore during setup (only authenticate with their Spotify credentials). 

I'm looking for around 20 beta testers in order for Spotify to look into my request.

Please DM me or ping me on twitter (@TheMiniPlayer) if you want to be part of the beta group

**Comment by ryan-efendy** [comment]
@vdesabou I'm interested 👋🏼 . My email is heyryanefendy@gmail.com.

**Comment by vdesabou** [comment]
@ryan-efendy I sent you an email. Thanks!

**Comment by vdesabou** [comment]
I will give up the idea because the Spotify api key and secrets would have to be shared publicly (Alfred workflows are ZIP files where code is available there), Spotify would never accept that

**Comment by cands** [comment]
Hi! I saw this rather late and it seems like it is relevant to be a beta tester anymore, in case it's needed in the future I'll be happy to help out.

**Comment by hendryque** [comment]
+1
