### ISSUE TITLE
Add option to launch setup page again

### ISSUE THREAD

**Issue by jrgd** [vdesabou/alfred-spotify-mini-player#539]
This should probably just be a suggestion: documentation could mention how to setup the app on the Spotify side. Once understood and overcome the process is really pretty simple but still I was confused about what didn't work and had to dig in closed issues on GitHub to understand I should have inserted a url in the dev Spotify panel.
For some reason there was no walk-in guide or on boarding and the documentation on this specific point verges on minimalism :) 

This said, now I understand a bit better all the moving part of the mini player and how Alfred is used to glue bits together; I find this fascinating! So one could argue that had there been a better documentation I would have missed this opportunity to learn. (Thank you!)
In any case, (double) thanks for sharing your work and for the impressive continuous support you provided.

**Comment by vdesabou** [comment]
Everything should be explained when this page opens in your browser:

![CleanShot 2021-11-10 at 17 55 19@2x](https://user-images.githubusercontent.com/4061923/141157610-936fae1f-891e-402e-b569-f6c9c37e25f0.jpg)

Didn't you see it ?


In next version, I've added this option to open the setup page again:

![CleanShot 2021-11-10 at 17 54 38@2x](https://user-images.githubusercontent.com/4061923/141157448-e2dd47f0-e774-465b-99ac-0f25e68ab883.jpg)
