### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by radjar** [vdesabou/alfred-spotify-mini-player#54]
Hi,
I received after try to autentificate Spot Mini this result: The requested resource / was not found on this server
![Uploading Snímek obrazovky 2015-02-04 v 12.08.15.png . . .]()
![screenshot_2015-02-04_12 08 15](https://cloud.githubusercontent.com/assets/10847404/6039536/43f25bf0-ac68-11e4-8515-9a7712599edb.png)

**Comment by vdesabou** [comment]
Hi,

Can you follow steps here http://alfred-spotify-mini-player.com/articles/support/ and send me TGZ file to the email address mentioned on the article?
Also I cannot see the screenshot, Github has issues when file name contains spaces in it, try to rename the screenshot before uploading it

Thanks

**Comment by radjar** [comment]
I just sent to your email

**Comment by vdesabou** [comment]
Thanks.

So when I start the web server to process oAuth authentication, I use port 15298 and on your machine it is already used:

```
[Wed Feb  4 12:21:43 2015] Failed to listen on localhost:15298 (reason: Address already in use)
```

Can you execute command:

```
lsof -n -i4TCP:15298
```

and print output?

**Comment by radjar** [comment]
--
Radek

**Comment by vdesabou** [comment]
and 

```netstat -an | grep 15298``` ?

**Comment by radjar** [comment]
Last login: Wed Feb  4 12:41:46 on ttys000
Radek-MBP:~ radek$ netstat -an | grep 15298
tcp4       0      0  127.0.0.1.15298        *.*                    LISTEN     
tcp6       0      0  ::1.15298              *.*                    LISTEN     
Radek-MBP:~ radek$ 
--
Radek

**Comment by vdesabou** [comment]
And this one:

```
lsof -i | grep LISTEN
```

I want to know why you have something listening on this port. If this is another application or the server which has been launched twice..

**Comment by radjar** [comment]
Last login: Wed Feb  4 13:47:51 on ttys000
Radek-MBP:~ radek$ lsof -i | grep LISTEN
EEventMan   260 radek   16u  IPv4 0x961584e6bc4bab3      0t0  TCP *:enpp (LISTEN)
Skype       269 radek  100u  IPv4 0x961584e6cb60043      0t0  TCP *:50749 (LISTEN)
imagent     305 radek    5u  IPv4 0x961584e7002e383      0t0  TCP *:52613 (LISTEN)
2BUA8C4S2   418 radek   27u  IPv4 0x961584e6cf0bea3      0t0  TCP localhost:6258 (LISTEN)
2BUA8C4S2   418 radek   28u  IPv6 0x961584e61de7cd3      0t0  TCP localhost:6258 (LISTEN)
2BUA8C4S2   418 radek   29u  IPv4 0x961584e6dcd6ab3      0t0  TCP localhost:6263 (LISTEN)
2BUA8C4S2   418 radek   30u  IPv6 0x961584e61de77d3      0t0  TCP localhost:6263 (LISTEN)
Dropbox10 14204 radek   39u  IPv4 0x961584e771571e3      0t0  TCP *:17500 (LISTEN)
Dropbox10 14204 radek   48u  IPv4 0x961584e77182913      0t0  TCP localhost:17600 (LISTEN)
BetterTou 19775 radek   23u  IPv4 0x961584e6cb61ab3      0t0  TCP *:61986 (LISTEN)
BetterTou 19775 radek   24u  IPv6 0x961584e61de5ed3      0t0  TCP *:61986 (LISTEN)
SpotifyWe 19987 radek    6u  IPv4 0x961584e6bc4b1e3      0t0  TCP localhost:4370 (LISTEN)
SpotifyWe 19987 radek    7u  IPv4 0x961584e76004ea3      0t0  TCP localhost:4380 (LISTEN)
Spotify   19993 radek   17u  IPv4 0x961584e6f176ab3      0t0  TCP localhost:4381 (LISTEN)
Spotify   19993 radek   18u  IPv4 0x961584e776e01e3      0t0  TCP localhost:4371 (LISTEN)
Spotify   19993 radek   46u  IPv4 0x961584e6e8611e3      0t0  TCP localhost:8099 (LISTEN)
Spotify   19993 radek   57u  IPv4 0x961584e75b6eea3      0t0  TCP *:57621 (LISTEN)
php       20501 radek    7u  IPv6 0x961584e7a4d38d3      0t0  TCP localhost:15298 (LISTEN)
php       20755 radek    7u  IPv4 0x961584e7838b1e3      0t0  TCP localhost:15298 (LISTEN)
Alfred    21856 radek    4u  IPv4 0x961584e6ed0aea3      0t0  TCP *:50710 (LISTEN)
Alfred    21856 radek    7u  IPv6 0x961584e61de6dd3      0t0  TCP *:50710 (LISTEN)
Transmiss 22597 radek   25u  IPv4 0x961584e6fbf8ab3      0t0  TCP *:51413 (LISTEN)
Transmiss 22597 radek   26u  IPv6 0x961584e61de68d3      0t0  TCP *:51413 (LISTEN)

--
Radek

**Comment by vdesabou** [comment]
ok so you have two php processes using the port, looks to me there are the web server the workflow is starting..

- Can you execute in Alfred ```spot_mini_kill``` ? It should kill the processes
- Then check processes are killed:

```ps -efx | grep "php -S localhost:15298"``` it should return empty

-  lsof -i | grep LISTEN | grep 15298 should return empty

if that's not the case, let me know.
If that's the case, then try again to invoke the workflow and click Authenticate to Spotify

**Comment by radjar** [comment]
this returned

Last login: Wed Feb  4 15:51:10 on ttys000
Radek-MBP:~ radek$ ps -efx | grep "php -S localhost:15298"
  501 20501     1   0 11:06dp ??         0:00.80 php -S localhost:15298
  501 20755     1   0 11:16dp ??         0:00.79 php -S localhost:15298
  501 25120 25116   0  3:51od ttys000    0:00.00 grep php -S localhost:15298
Radek-MBP:~ radek$ lsof -i | grep LISTEN | grep 15298
php       20501 radek    7u  IPv6 0x961584e7a4d38d3      0t0  TCP localhost:15298 (LISTEN)
php       20755 radek    7u  IPv4 0x961584e7838b1e3      0t0  TCP localhost:15298 (LISTEN)
Radek-MBP:~ radek$ 

--
Radek

**Comment by vdesabou** [comment]
ok so do:

```
kill -9 20501 20755
```

And then try again

**Comment by radjar** [comment]
Last login: Wed Feb  4 15:51:48 on ttys000
Radek-MBP:~ radek$ kill -9 20501 20755
Radek-MBP:~ radek$ ps -efx | grep "php -S localhost:15298"
  501 25187 25183   0  3:56od ttys000    0:00.00 grep php -S localhost:15298
Radek-MBP:~ radek$ lsof -i | grep LISTEN | grep 15298
Radek-MBP:~ radek$ 

--
Radek

**Comment by vdesabou** [comment]
Ok so you can try again now to Authenticate...that should work

**Comment by radjar** [comment]
--
Radek

**Comment by vdesabou** [comment]
?

**Comment by radjar** [comment]
It wrote me Invalid client. 

Odesláno z iPhonu

4. 2. 2015 v 16:28, Vincent <notifications@github.com>:

**Comment by radjar** [comment]
Problem of Safari?

Odesláno z iPhonu

4. 2. 2015 v 16:28, Vincent <notifications@github.com>:

**Comment by vdesabou** [comment]
did you click "save" as explained in red here http://alfred-spotify-mini-player.com/setup/

**Comment by radjar** [comment]
Yes. 

Odesláno z iPhonu

4. 2. 2015 v 16:37, Vincent <notifications@github.com>:

**Comment by vdesabou** [comment]
Try the process again, there is no reason it does not work if you follow exactly steps here http://alfred-spotify-mini-player.com/setup/:

-spot_mini_kill
-spot_mini_reset_settings
-Follow http://alfred-spotify-mini-player.com/setup/

**Comment by radjar** [comment]
perfect, working, problem was with slash at the end of adress http://localhost:15298/callback.php/ <http://localhost:15298/callback.php/>
thank you
--
Radek

**Comment by vdesabou** [comment]
ok cool.
closing the issue then
