### ISSUE TITLE
Mini player does't play - just opens Spotify

### ISSUE THREAD

**Issue by Gusman10000** [vdesabou/alfred-spotify-mini-player#542]
Hi all,

I have just been trying to install the mini player for the first time on a new M1 mac. It has been a process with a few issues:

I had issues trying to get the player to create the library. There would be a problem loading the localhost page after I authorize on Spotify, and the create library step would time out.

With debug mode ON, the localhost page still does not load after Spotify authorization, but it does seem to successfully build the library (I'm getting album art when searching and can look through my playlists).

(Note I've tried Chrome, Firefox and Safari as default browsers when trying to go through the mini player setup)

Lastly, when I go to play a song, the mini player will open the song in the official Spotify app, including bringing the full-size app on-screen. Is this what the mini player is meant to do, or is it meant to play the songs 'itself'?

So I guess to summarize there are two, maybe three issues here:

- The localhost landing page after Spotify authorization does not work

- The mini player will not successfully complete the 'Create Library' step if debug mode is not on(
(Debug mode is off by default, meaning the mini player will not work unless the user does some digging on this Github page)

- The Mini player is bringing up the Spotify app when completing 

Lastly, as a side note, does deleting the workflow in Alfred clear out the mini players local files (Such as album artwork and all that)?

**Comment by vdesabou** [comment]
Can you follow those steps https://github.com/vdesabou/alfred-spotify-mini-player/issues/534#issuecomment-954092447

i would need some logs to investigate.

to answer you question about deleting workflow, no it does not remove artworks and local DB library: they are stored in application support folder.
There is an option available to delete artwork folder easily

**Comment by vdesabou** [comment]
Debug mode shouldn’t have any impact on library update progress

**Comment by vdesabou** [comment]
The workflow needs to have Spotify desktop running, so yes it opens it in background.
If you are a premium user you can use Spotify connect and select a favorite connect device. In that case Spotify desktop will not have to be opened at all

**Comment by vdesabou** [comment]
Please update to 11.6 as well

**Comment by Gusman10000** [comment]
Email is sent. As I mentioned in the email, I tried out 11.6 after deleting the workflow and its local files and the installation went smoothly this time without debug mode on. Something in 11.6 must have fixed the issues I was having.

The landing page after Spotify authorisation still doesn't work, but the rest works fine.
