### ISSUE TITLE
auth problem , I tried safari chrome and Mozilla . none of them worked 

### ISSUE THREAD

**Issue by zweiche** [vdesabou/alfred-spotify-mini-player#546]
my firewall is off . I have no proxy 
i also checked altered settings which was unticked anyway. tried 3 different browser all getting same error . also I installed php

**Comment by vdesabou** [comment]
I would need the error and a better description to troubleshoot 
What do you see? What do you get in https://www.alfredapp.com/help/workflows/utilities/debug/

**Comment by vdesabou** [comment]
Closing as no feedback
