### ISSUE TITLE
can't download artwork

### ISSUE THREAD

**Issue by NuPlay** [vdesabou/alfred-spotify-mini-player#548]
Press the library refresh button to refresh my playlists but not download Artwork

To be exact, workflow gets images of my playlists, but I can't get images of each song inside.

Also, even if I refresh it, workflow doesn't show me downloading artwork.

Artworks was enabled, and just in case, I deleted the workflow and reinstalled it.

Also, it does not show the capacity in the column showing the capacity of the current Artworks.

<img width="662" alt="스크린샷 2021-11-26 오전 10 11 15" src="https://user-images.githubusercontent.com/73557895/143512576-06568526-2c14-46ed-bf81-a1092ecb6a4b.png">

<img width="662" alt="스크린샷 2021-11-26 오전 10 10 54" src="https://user-images.githubusercontent.com/73557895/143512568-425886a5-fc2d-43ea-b431-5ce72f3ef92e.png">

Alfred 4.6[1266]
macOS 12.0.1

**Comment by vdesabou** [comment]
As explained there https://alfred-spotify-mini-player.com/articles/update-library/ the download is done in background, so what you see is expected

**Comment by vdesabou** [comment]
Closing. If there is still an issue, update it

**Comment by NuPlay** [comment]
Sorry for answering late.

Before I update macOS to Monterey,
When I click Update Library, it shows that downloading Artwork, and downloading to the background proceeded.

But after updating macOS, it doesn't seem to be downloading in the background.
(I've been waiting for more than 8 hours, but there's no additional artwork to download after downloading the playlist artwork)

But when I play a song through this workflow, downloaded that artwork of the song.

**Comment by vdesabou** [comment]
@NuPlay Let's followup by email because I need to see your logs.
Can you send me a debug email as explained here https://alfred-spotify-mini-player.com/articles/support/

**Comment by NuPlay** [comment]
@vdesabou I sent you an email

**Comment by vdesabou** [comment]
For follow-up, this will be fixed with #551
