### ISSUE TITLE
Updated to 6.0.3, all my online playlist gone from the workflow DB

### ISSUE THREAD

**Issue by sollymay** [vdesabou/alfred-spotify-mini-player#55]
Hey vdesabou, how are you?

I just updated the workflow to the latest version.

Tried to look for my playlists and they are gone, only local playlists (iTunes) are the ones stored.

Tried to delete all the library, readd it, actually created a new app on spotify to see if it was a problem.

Authentication works but nothing is pulled from it to my workflow DB. I only see my local files playlists.

**Comment by vdesabou** [comment]
Hello,

I'm fine thanks :smile: 
Can you send by email the TGZ file (everything is explained here http://alfred-spotify-mini-player.com/articles/support/), I'll have a look

So to understand, which version was working before?

**Comment by sollymay** [comment]
WOOPS, forgot to say, version 5.2

-- 
Salomon May
Sent with Airmail

On February 6, 2015 at 1:18:55 AM, Vincent (notifications@github.com) wrote:

Hello,

I'm fine thanks  
Can you send by email the TGZ file (everything is explained here http://alfred-spotify-mini-player.com/articles/support/), I'll have a look

So to understand, which version was working before?

**Comment by vdesabou** [comment]
It is strange indeed, I can only see 5 playlists, but when I got to your profile in Spotify, that's all I can see as well:

![tmp](https://cloud.githubusercontent.com/assets/4061923/6077086/8dd4687e-adeb-11e4-9061-8fc8dc315c6b.png)

In these playlists, there are about 230 tracks, but all local tracks, so they are ignored (there is a way to try to match them with spotify tracks, see known issues http://alfred-spotify-mini-player.com/known-issues/) 

Can you tell me more about your library? How many playlists do you have in total? Are they all collaborative playlists ? (because it is not supported by Spotify WEB API yet) 

In fact there is no error at all, it is just as if you only have 5 playlists on your Spotify account...

**Comment by sollymay** [comment]
So I actually have 33 playlists + those 5 from iTunes (I actually don’t use iTunes anymore) hehehe.

Not all of them are available online, but most of the playlists are.

None of them are collaborative playlists.

It is as if the workflow is ignoring all my playlists created using spotify.

Just to make sure, I just created another playlist and it was not detected as a change even when rebuilding the library or updating it on the workflow

**Comment by vdesabou** [comment]
The problem I have here is that it is not a workflow problem, it is Spotify WEB API only returning 5 playlists. You can test by yourself here https://developer.spotify.com/web-api/console/get-playlists/
If you put your username, there are only 5 playlists returned...
Are you sure they're not collaborative?

**Comment by sollymay** [comment]
As an example, showing you it is not collaborative.

So spotify is actually not getting the right data off my DB.

Also, really strange. Those used to be my playlist in iTunes like a really long time ago.

I don’t have playlist on iTunes anymore!

They don’t show on spotify but when you query it, they show!

**Comment by sollymay** [comment]
Ok, I seem to know what the problem is.

my free account was created as sollymay. My premium account was created with a Facebook login.

I just authenticated my my premium account login ID, did the whole process again, but it is still pointing at the same playlists.

This is really weird.

It used to work no problems before!

**Comment by sollymay** [comment]
http://open.spotify.com/user/1255413740

Thats my profile on the new and premium spotify, but the workflow keeps pointing to the old user although I already signed out of it on the website and logged in with the new (premium user).

Both the old and new accounts have the same email address, so it might be that because of the same email address something could be going on?

**Comment by vdesabou** [comment]
>http://open.spotify.com/user/1255413740

Thats my profile on the new and premium spotify, but the workflow keeps pointing to the old user although I already signed out of it on the website and logged in with the new (premium user).

Try this:-

-invoke spot_mini_reset_settings
-Delete library.db (you can reach it by invoking spot_mini_debug and then choose Browse to App Support folder)
-do setup process again (http://alfred-spotify-mini-player.com/setup/). Make sure you're using the account  http://open.spotify.com/user/1255413740 when creating the application and when you login to authorize the application

Let me know if that helps. If not, please send again the new TGZ file after you've done this

**Comment by vdesabou** [comment]
>SOLVED!

ok, did not see this update. thanks for the update
