### ISSUE TITLE
Command for getting current lyrics is broken

### ISSUE THREAD

**Issue by AleksIralda** [vdesabou/alfred-spotify-mini-player#554]
An amazing feature is lyrics finder, is my favorite option and the most used for me everyday but simply not longer work anymore.

Previously I publish a ticket here
https://github.com/vdesabou/alfred-spotify-mini-player/issues/523#issue-997547729
After a few days published the ticket worked again.

But, after a couple months the bug is back again, this time the debug log not show any info.

I understand the effort to maintain this amazing workflow. But You have any Idea  about it?

Thanks in advanced!

**Comment by vdesabou** [comment]
I just tried on 3 random songs and it worked:

Example:

![CleanShot 2021-12-09 at 17 34 34@2x](https://user-images.githubusercontent.com/4061923/145437413-5a640799-772b-4b9f-811b-a51558b0e592.jpg)

Is it 100% reproducible on your side ? or only on some songs?

**Comment by vdesabou** [comment]
@AleksIralda Can you clarify when exactly you get the error ?

**Comment by AleksIralda** [comment]
I'm trying get more info about bug but I can't get any data, I'm using a old version of spotify, but I tried with recent version and error is the same. The log in alfred not show any data. 


![Screen Shot 2021-12-12 at 19 55 20](https://user-images.githubusercontent.com/10256929/145740755-516fe473-0df9-481c-af82-f9f4d3c50006.png)

**Comment by AleksIralda** [comment]
> I just tried on 3 random songs and it worked:
> 
> Example:
> 
> ![CleanShot 2021-12-09 at 17 34 34@2x](https://user-images.githubusercontent.com/4061923/145437413-5a640799-772b-4b9f-811b-a51558b0e592.jpg)
> 
> Is it 100% reproducible on your side ? or only on some songs?
 

100% on my side, simply not work at all

**Comment by vdesabou** [comment]
Post a screenshot of what do you see and a link to the track having the issue

**Comment by AleksIralda** [comment]
Hi, I think that I found the cause, probably is my error but I'll try to explain to give knowledge about it.

I notice that I need start the "spot_mini" command for it to work.

![Screen Shot 2021-12-13 at 2 55 04](https://user-images.githubusercontent.com/10256929/145785595-31a5f97f-074f-456b-8cd2-2b65ce39bf84.png)

It's not was obvious for me, because I've been using for more than a year the function without starting the command

I previously used the (shortcut) "ly" on alfred (see image)
![Screen Shot 2021-12-13 at 3 21 59](https://user-images.githubusercontent.com/10256929/145785498-04d0ab73-e005-40dd-ad0b-30299afade7b.png)

Unlike, here is not an alfred feedback after I push enter. Same occurs when I try set a keyboard shortcut.

The lyrics function it's works but the shortcuts don't.

**Comment by vdesabou** [comment]
Thanks, now I can reproduce. It will be fixed in next release 11.8.
