### ISSUE TITLE
Limit Random Album to albums saved in Spotify Library

### ISSUE THREAD

**Issue by patrickrushton** [vdesabou/alfred-spotify-mini-player#555]
A couple of years ago Spotify introduced the feature to save albums to the library, for example by right-clicking an album and choosing "Add to Your Library" or by tapping the heart icon on an album view.

I had expected the Random Album workflow to select from these albums. Instead, it also considers individual tracks that are in the user's Liked Songs list and will play a complete album for any of the songs in that list. Edit: and apparently **completely ignores the saved albums**.

For me it would be preferable to only consider full albums in the library. Perhaps this could be an option?

**Comment by patrickrushton** [comment]
Including a link to the relevant API https://developer.spotify.com/console/get-current-user-saved-albums/

**Comment by vdesabou** [comment]
I prefer it your way, the change will be included in 11.8

if people complain, I can make it as an option later
