### ISSUE TITLE
Any plans to integrate a similar plugin with Raycast?

### ISSUE THREAD

**Issue by Belco90** [vdesabou/alfred-spotify-mini-player#556]
Hi there!

It's obvious that this plugin is attached to Alfred just by looking at its name, but I was wondering if you had any plan for integrating it somehow with [Raycast](https://www.raycast.com/). This is the only extension I miss from Alfred, preventing me from switching 100%.

Cheers.

**Comment by vdesabou** [comment]
No plan, sorry:

- I don't use Raycast
- This workflow is written in PHP, Raycast only supports React, Node.js and TypeScript, so that would be a big re-write. But code is available here, anyone can work on it 😄

**Comment by Belco90** [comment]
Thanks for the quick response!

**Comment by youtextme** [comment]
If the gap is “I want this Spotify flow in Raycast”: there’s already a Raycast Spotify extension in the Store, and Script Commands can wrap the same AppleScript the Alfred workflow uses. Worth trying free Raycast alongside Alfred before waiting on a port.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
