### ISSUE TITLE
The requested resource / was not found on this server.

### ISSUE THREAD

**Issue by qmlowery** [vdesabou/alfred-spotify-mini-player#56]
When trying to Authenticate, a webpage opens stating Not Found: The requested resource / was not found on this server.

I've tried regenerating keys, removing, and redownloading the workflow, but nothing has helped.

**Comment by vdesabou** [comment]
Hi,

Can you follow steps here http://alfred-spotify-mini-player.com/articles/support/ and send me TGZ file to the email address mentioned on the article?

**Comment by vdesabou** [comment]
Also, make sure the Application page is correctly set with Redirect URL ```http://localhost:15298/callback.php```and you clicked ```Save``` Button.

**Comment by qmlowery** [comment]
The URI was correct, and I had clicked save. I just emailed you the tgz file.

**Comment by vdesabou** [comment]
You have same problem as https://github.com/vdesabou/alfred-spotify-mini-player/issues/54, i.e the port is already in used (https://github.com/vdesabou/alfred-spotify-mini-player/issues/54#issuecomment-72840885)

So can you follow, for example this comment https://github.com/vdesabou/alfred-spotify-mini-player/issues/54#issuecomment-72857443

**Comment by qmlowery** [comment]
I ran spot_mini_kill and then ps -efx | grep "php -S localhost:15298"
ps -efx | grep "php -S localhost:15298"  command returned 1 item, but
the lsof -i | grep LISTEN | grep 15298 command returned empty.

**Comment by vdesabou** [comment]
can you display the result of ```ps -efx | grep "php -S localhost:15298"```
I will tell you how to kill it

**Comment by qmlowery** [comment]
output is
501   657   635   0 11:11AM ttys000    0:00.00 grep php -S localhost:15298

**Comment by vdesabou** [comment]
Ok so you can try again now to Authenticate...that should work.

If it does not, send me a the new generated TGZ file

**Comment by qmlowery** [comment]
I was sent to the Authentication page, but then was forwarded to an error page stating:

There was an error during the authentication (exception exception 'SpotifyWebAPI\SpotifyWebAPIException' with message 'Invalid client' in /Users/quentinlowery/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.35ECE71D-DAAE-4F82-A1EA-71B595C7D9C6/vendor/jwilsson/spotify-web-api-php/src/Request.php:139 Stack trace: #0 /Users/quentinlowery/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.35ECE71D-DAAE-4F82-A1EA-71B595C7D9C6/vendor/jwilsson/spotify-web-api-php/src/Request.php(26): SpotifyWebAPI\Request->send('POST', 'https://account...', Array, Array) #1 /Users/quentinlowery/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.35ECE71D-DAAE-4F82-A1EA-71B595C7D9C6/vendor/jwilsson/spotify-web-api-php/src/Session.php(211): SpotifyWebAPI\Request->account('POST', '/api/token', Array) #2 /Users/quentinlowery/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.35ECE71D-DAAE-4F82-A1EA-71B595C7D9C6/callback.php(24): SpotifyWebAPI\Session->requestToken('AQDo60dayGPQfUZ...') #3 {main})


I will also email you the debug file again if you'd like.

**Comment by vdesabou** [comment]
Are you sure the Application you have created https://developer.spotify.com/my-applications was done with same Spotify account that you used during authentication?
Also please check that Client Id And Client Secret are sames as the one in Application, and you correctly set Redirect URL and clicked Save button..

There is no reason why it would not work..

**Comment by qmlowery** [comment]
The secrets probably aren't the same anymore because I reset them when I was having troubles, but couldn't figure out how to change them in the mini player

**Comment by vdesabou** [comment]
Spot_mini_reset_settings and start process again

Vincent

**Comment by qmlowery** [comment]
Doing this never asks for my client ID or client secret again. It sends me straight to the connect page, which fails when I click okay.

**Comment by vdesabou** [comment]
spot_mini_reset_settings should work as it deletes the settings.son file...
If it does not work then I would like to see the TGZ file when you execute this command.

You can delete the file by invoking spot_mini_debug and then browse to App Support folder and then delete settings.son file.

**Comment by qmlowery** [comment]
I am emailing you the tgz file generated after running spot_mini_reset_settings and then spot_mini_debug

**Comment by qmlowery** [comment]
After deleting the file manually, the problem seems to be fixed.

**Comment by vdesabou** [comment]
>After deleting the file manually, the problem seems to be fixed.

I'm really surprised spot_mini_reset_settings did not delete your settings file..Would be worth debugging that..

Anyway, it is working now, so enjoy
