### ISSUE TITLE
can't seem to import library

### ISSUE THREAD

**Issue by lostbro99** [vdesabou/alfred-spotify-mini-player#560]
hi I just installed the Spotify mini player (v11.8) and can't seem to import my library into the workflow. 

whenever I type in a song title, it gives me the option of searching it on Spotify or songs not in my library. when I click it, it brings me to the app. 

It says that I have 0 track, 0 playlist and 0 shows. I'm confused because during the set up process, I did agree to import and connect it to my Spotify account.

I tried reinstalling it but the result is the same.

please help! I really like this workflow but can't seem to get it to work!

**Comment by vdesabou** [comment]
https://alfred-spotify-mini-player.com/articles/support/

Send me a debug email I will have a look

can you join some screenshots of what you see in that email.
Will Follow up by email
