### ISSUE TITLE
Potential bug at launch

### ISSUE THREAD

**Issue by sanspot** [vdesabou/alfred-spotify-mini-player#562]
Might be related to the fact this is a new M1 chip mac, but when I try and launch the app I get an error message:

"Reason: launch path not accessible

/usr/bin/php

Check that the selected language exists on your system.

If you're syncing Alfred's preferences, also check that all related workflow files exist locally.

Related Workflow Info...
Name: 'Spotify Mini Player'
Folder:/Users/sandro.macchioli/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1AB02DC2-8986-4B32-B21F-418B3FEAF5C1"

Not sure what to do but maybe it's useful for you to know. Thank you!

**Comment by vdesabou** [comment]
You need to use latest version of Alfred + the workflow

And you need to install PHP by following https://alfred-spotify-mini-player.com/setup/#install-php-macos-monterey-and-above
