### ISSUE TITLE
Add to queue not working

### ISSUE THREAD

**Issue by PapaPakistan** [vdesabou/alfred-spotify-mini-player#564]
The feature where I hold the command and option keys to queue a song does not work

**Comment by vdesabou** [comment]
It works only if you use Spotify connect option https://alfred-spotify-mini-player.com/articles/spotify-connect/ (premium only)

**Comment by PapaPakistan** [comment]
Is there a way to add to my queue while I am playing music on my computer?

Thank you

**Comment by vdesabou** [comment]
Select a track with ⌘+⌥ (cmd+alt key) to add track to queue ([Spotify Connect](https://alfred-spotify-mini-player.com/articles/spotify-connect/) users only)

**Comment by PapaPakistan** [comment]
Ok I'm just dumb I didn't have connect activated, thank you!
