### ISSUE TITLE
The workflow does not work

### ISSUE THREAD

**Issue by Aya-Yang** [vdesabou/alfred-spotify-mini-player#565]
Hi, I have macOS 12.3.1 installed, and I found the workflow does not work,
![image](https://user-images.githubusercontent.com/12084255/162403234-51f64cc6-145f-40ca-b7e5-e6341fa138ab.png)
Then I press ENTER, it would be like 
![image](https://user-images.githubusercontent.com/12084255/162403370-0c0770b0-858b-4e0e-8756-f7e080389d25.png)

How can I fix this, there is no error log

**Comment by SheriffOfNotts** [comment]
https://www.alfredapp.com/help/kb/python-2-monterey/

**Comment by Aya-Yang** [comment]
> https://www.alfredapp.com/help/kb/python-2-monterey/

It's a matter of PATH variable, see https://www.alfredapp.com/help/workflows/advanced/understanding-scripting-environment/

The workflow directly use php, but my php path is /usr/local/bin/php, so it can not be found.
I replace all php with /usr/local/bin/php, and it works

**Comment by vdesabou** [comment]
you shouldn't have to do that if you follow this https://alfred-spotify-mini-player.com/setup/#install-php-macos-monterey-and-above

and use the latest Alfred version

**Comment by Aya-Yang** [comment]
By design, Alfred does not see this custom environment. Its PATH is /usr/bin:/bin:/usr/sbin:/sbin and isn't affected by your shell's configuration files.
brew install php, the path is /usr/local/bin/php，so the scripts not found the path

And I am using both latest Alfred and the workflow

**Comment by vdesabou** [comment]
Alfred supports home-brew installs since 4.6:

```
Alfred 4.6
Build 1266, Friday 15th October 2021
macOS Monterey Support
• Added compatibility enhancements for macOS Monterey
• Improved handling of missing bin path when running a Workflow script 
• Log debug info into the workflow debugger when relevant
• Add options on popup alert dialog to open or disable the relevant workflow when attempting to run
• Check alternative Homebrew install locations for bins when missing from default location
• Homebrew installed php on macOS 12 will be found in either /opt/homebrew/bin/php (Apple Silicon) or /usr/local/bin/php (Intel)
```

The workflow definitely works with Monterey, I have it installed
Maybe you have an old version of the workflow

**Comment by Raheemshah2809** [comment]
It works perfectly fine on Mac OS 12.3 (21E230); I had to install PHP, (brew install PHP) and followed the steps:
https://alfred-spotify-mini-player.com/setup/#install-php-macos-monterey-and-above 
And it works!

**Comment by vdesabou** [comment]
closing
