### ISSUE TITLE
Now playing notification breaks when certain settings are touched

### ISSUE THREAD

**Issue by ViaxCo** [vdesabou/alfred-spotify-mini-player#568]
The Now playing notification breaks whenever I toggle these settings: "Disable Track Rating" or "Disable Now Playing notifications" and doesn't come back until I completely remove the workflow from Alfred and also remove the data from `~/Library/Application Support/Alfred/Workflow Data`. Double clicking the app under "Alfred.alfredpreferences" doesn't work either.

**Comment by vdesabou** [comment]
I just tested and it works fine. Send a debug email if you still have the issue
