### ISSUE TITLE
Invalid redirect uri even after follow prev issues' solution

### ISSUE THREAD

**Issue by ulises-castro** [vdesabou/alfred-spotify-mini-player#570]
I followed all steps and even previous same issues on this repo (make sure click on save button) but every time I tried to "Authenticate": the same errors appers.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/17864276/175968007-76619201-afe9-44b5-b009-435f676cf726.png">

**Comment by vdesabou** [comment]
@Lovro1107 I'm not sure how I can do better than that ! 😄 

![CleanShot 2022-11-24 at 13 12 42](https://user-images.githubusercontent.com/4061923/203781825-7b014e86-f090-47dd-8bfc-6361be027a40.jpg)

**Comment by Lovro1107** [comment]
Where is this written, I didn't find it anywhere 🤔

**Comment by vdesabou** [comment]
If you use Alfred 5 it is directly within the workflow configuration in Alfred settings window

**Comment by Lovro1107** [comment]
OMG how did I miss that 🤦‍♂️ Sorry, everything is well written, my bad 😄
