### ISSUE TITLE
No coverart in the notification on the latest macOS Montery

### ISSUE THREAD

**Issue by FleXoft** [vdesabou/alfred-spotify-mini-player#571]
![image](https://user-images.githubusercontent.com/1357569/176956252-e21338fe-378d-4ec7-9464-9b6548075d08.png)

**Comment by vdesabou** [comment]
Type `spot_mini_debug`and select those 2 options:

![CleanShot 2022-07-02 at 09 59 08](https://user-images.githubusercontent.com/4061923/176992156-2ad72fd2-a01a-49f5-9e12-7cd0eb8f2409.jpg)

Also reboot generally helps

**Comment by FleXoft** [comment]
Thnks for your advice. Still no coverart in the notifications just in Alfred list.

**Comment by FleXoft** [comment]
Sorry, after reboott there's icon now:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/1357569/176998533-eeb24bc3-05c1-4a6d-ad5a-18017fc1c04a.png">

but don't I remember well that the cover used to appear there?

**Comment by vdesabou** [comment]
Yes but i think it does not Work anymore since Big Sur, if I recall correctly

**Comment by vdesabou** [comment]
Yeah it is caused by https://github.com/julienXX/terminal-notifier/issues/283

**Comment by FleXoft** [comment]
Thanks for your help and your time.
