### ISSUE TITLE
Not working on Alfred 5

### ISSUE THREAD

**Issue by luchian94** [vdesabou/alfred-spotify-mini-player#572]
The workflow doesn't seem to work on latest alfred version.

Tried to reinstall it and configure again but the setup flow doesn't show up:

![image](https://user-images.githubusercontent.com/34107266/178984251-e434be3a-7b63-43a6-8836-300d31afd762.png)
![image](https://user-images.githubusercontent.com/34107266/178984497-3df81be0-f76c-48ad-8395-b10b4a0da027.png)

**Comment by anaulin** [comment]
I just upgraded to Alfred 5 and then installed this workflow for the first time. The setup steps seemed to work fine, but it doesn't seem to be creating the library. Every time I open the mini player my only option is "Create Library":

https://user-images.githubusercontent.com/6729309/179059481-de53bf75-cacf-429f-8fb3-0ec297048527.mp4

I also tried executing the "Fix Permissions" workflow, but it doesn't seem to do anything?

This is the debug info from the debug option:
----------------------------------------------
🕐 Generated: 2022-07-14 18:46:33
----------------------------------------------
ENCRYPTED TOKENS ELIDED

----------------------------------------------
📁 fetch_artworks.db is not present
📁 library.db is not present
📁 library_new.db is not present
📁 library_old.db is not present
The directory /Users/anaulin/Library/Application Support/Alfred/Workflow Data/com.vdesabou.spotify.mini.player/users is not present
Darwin Anas-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
12.4
hw.memsize: 17179869184
alfred_version:5.0
alfred_version_build:2057
alfred_workflow_version:11.8
alfred_debug:
reduce_notifications:0
automatically_refresh_library:0
automatically_open_spotify_app:0
Spotify desktop version:1.1.86.857.g3751ee08
PREMIUM
xattr Spotify Mini Player.app returned: 
com.apple.quarantine
user.drive.can_manage_team_drive_members
user.drive.email
user.drive.id
user.drive.md5
user.drive.mime_type
user.drive.shortcut.target.stableid
user.drive.stableid
user.drive.team_drive_id

xattr terminal-notifier returned: 
com.apple.quarantine
user.drive.can_manage_team_drive_members
user.drive.email
user.drive.id
user.drive.md5
user.drive.mime_type
user.drive.shortcut.target.stableid
user.drive.stableid
user.drive.team_drive_id

----------------------------------------------
Settings
----------------------------------------------
__all_playlists=1
__now_playing_notifications=1
__mopidy_port=6680
__last_check_update_time=0
__userid=anaulin
__is_autoplay_playlist=1
__search_order=playlist▹artist▹track▹album▹show▹episode
__max_results=50
__debug=0
__alfred_playlist_uri=
__artwork_folder_size=
__alfred_playlist_name=
__always_display_lyrics_in_browser=0
__use_artworks=1
__automatic_refresh_library_interval=0
__quick_mode=0
__workflow_version=
__use_growl=0
__is_public_playlists=0
__preferred_spotify_connect_device_pushcut_webhook_json_body=
__radio_number_tracks=30
__theme_color=green
__mopidy_server=127.0.0.1
__output_application=APPLESCRIPT
__country_code=US
__fuzzy_search=0
__is_alfred_playlist_active=1
__display_name=Ana Ulin
__preferred_spotify_connect_device=
__oauth_client_id=SEEKRET
__podcasts_enabled=1
__is_display_rating=1
__use_facebook=0
__oauth_redirect_uri=http://localhost:15298/callback.php
__oauth_refresh_token=SEEKRET
__preferred_spotify_connect_device_pushcut_webhook=
__volume_percent=20
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
----------------------------------------------
File: action.log
----------------------------------------------
2022-07-14 18:35:25|Starting Spotify desktop...
2022-07-14 18:35:31|Info(fix_permissions) for fzf
2022-07-14 18:35:31|Info(fix_permissions) for terminal-notifier
2022-07-14 18:35:31|Info(fix_permissions) for Spotify Mini Player

----------------------------------------------
File: spotify_mini_player_web_server.log
----------------------------------------------

**Comment by vdesabou** [comment]
I haven’t spotted any specific issue with Alfred 5.
@luchian94 can you show the Alfred debug console output when you type next command.
This behaviors happens when workflow produce invalid json and the only way to see the problem is with Alfred debug console

**Comment by luchian94** [comment]
> I haven’t spotted any specific issue with Alfred 5. @luchian94 can you show the Alfred debug console output when you type next command. This behaviors happens when workflow produce invalid json and the only way to see the problem is with Alfred debug console

I closed the issue as I was able to solve the problem by updating alfred to latest version and restarting the PC. After that the authentication flow was showing up and I was able to complete it successfully. It was my PC problem probsably
