### ISSUE TITLE
Alfred 5 Bug: Notifications with wrong icon or not showing at all

### ISSUE THREAD

**Issue by chrisgrieser** [vdesabou/alfred-spotify-mini-player#574]
Since upgrading to Alfred 5, the notifications only showed a a Terminal symbol instead of the spotify mini player icon like before. I tried to re-install the workflow, but that caused notifications to completely stop showing up.

**Comment by vdesabou** [comment]
See https://github.com/vdesabou/alfred-spotify-mini-player/issues/571

**Comment by chrisgrieser** [comment]
ah, that helped, thanks!
