### ISSUE TITLE
Many identical results shown when searching for an album in Your Music

### ISSUE THREAD

**Issue by cands** [vdesabou/alfred-spotify-mini-player#575]
When searching for an album in "Your Music" the workflow seems to show one hit for each song in the album, which bloats the search view. Please see below screenshot as an example. If possible it would be nice if only one hit was shown in this case (although a minor thing). Thanks again for this lovely workflow.

![20220807_10-08-09_screenshot_alfred-spotify-mini-player](https://user-images.githubusercontent.com/3845017/183281953-ae15f0e6-cab2-4a4a-a613-4141c775ab14.png)

**Comment by vdesabou** [comment]
I cannot reproduce the issue with latest version. Which version are you using ?
Can you give more info on the steps to reproduce ?

**Comment by cands** [comment]
I'm using version v11.8 and Alfred 5.0.3 (macOS 12.6). There are just two steps I use:

1. Activate the workflow (I do this through external call to 'spot_mini')
2. Start searching (I use the 'Fuzzy Search for music in "Your Music" only' functionality)

**Comment by cands** [comment]
I confirm issue seems to be solved in version 12.3, thanks!
