### ISSUE TITLE
Can the mini-player not show up under Alfred hotkey, only under mini-player's?

### ISSUE THREAD

**Issue by kongpuishun** [vdesabou/alfred-spotify-mini-player#577]
I have set the mini-player hotkey as control-option-return, and set the Alfred hotkey as command-space.
Is it possible to only see the options of the mini-player under its hotkey only? It would be great because I only want to see the Spotify content when I use that mini-player hotkey. Many thanks!

**Comment by vdesabou** [comment]
Not sure to understand the issue, can you share screenshots and more explanations ?

**Comment by kongpuishun** [comment]
<img width="703" alt="Screen Shot 2022-08-21 at 11 02 30 AM" src="https://user-images.githubusercontent.com/106246957/185773479-995c1949-b441-4d5f-872c-669888f177af.png">

Basically, is it possible to not show the mini-player result under regular Alfred hotkey (and under mini-player hotkey only)? In the screenshot, I used the Alfred hotkey, and as you can see, the last three results are from the mini-player. Thanks!

**Comment by vdesabou** [comment]
Ok so you can rename commands with values that will never appear in results or set them to empty (I have not tested), see https://alfred-spotify-mini-player.com/articles/customization/

![B771D74F-B664-4C7E-90D0-75F0CD0EBD64](https://user-images.githubusercontent.com/4061923/185780976-743e6bca-e888-4b82-b7e0-d61e244404c3.jpeg)

let me know if that helps

**Comment by kongpuishun** [comment]
I am sorry but I am not sure how it works.
Should I rename all the Variables "name" to something different? Tick
"Don't Export" for all the variables? Or change the "Value" of the
variables?
Thanks for the reply.

Vincent de Saboulin ***@***.***> 於 2022年8月21日週日 下午3:42寫道：

**Comment by vdesabou** [comment]
let's take the "Play" command as example:

instead of

![CleanShot 2022-08-22 at 09 10 33](https://user-images.githubusercontent.com/4061923/185860879-5a48a93a-38a7-4d71-aa54-247deb300977.jpg)


You update it with blank value:

![CleanShot 2022-08-22 at 09 11 27](https://user-images.githubusercontent.com/4061923/185860909-72aae9f8-7b37-4874-8cd7-e031b033d804.jpg)


Then Play will not appear anymore in Alfred results

**Comment by kongpuishun** [comment]
Thanks! That works out wonderfully.


Vincent de Saboulin ***@***.***> 於 2022年8月22日週一 下午3:13寫道：

**Comment by vdesabou** [comment]
👍🏻
