### ISSUE TITLE
Limit the number of episodes in shows

### ISSUE THREAD

**Issue by Anthony9802** [vdesabou/alfred-spotify-mini-player#578]
I want to be able to search podcasts and shows, but the loading process takes way too long because some of the shows have hundreds of thousands of episode in it. My suggestion would be that a future update will have an option to allow only the recent 10 or 20 or 30 episodes to be included when the library is being updated.

**Comment by vdesabou** [comment]
![CleanShot 2022-12-03 at 15 59 18@2x](https://user-images.githubusercontent.com/4061923/205447206-8bee0eaf-50b6-4bf9-a675-30f24af1c9d0.jpg)
