### ISSUE TITLE
Add / Remove not showing up

### ISSUE THREAD

**Issue by j4hangir** [vdesabou/alfred-spotify-mini-player#579]
I have the latest version `11.8` installed, today suddenly realized the `Add` and 'Remove' options have disappeared.

Refreshing the DB, killing the process and even reinstalling from scratch didn't fix it.

Is it only for me or anyone else facing this?

**Comment by vdesabou** [comment]
It is still there
It's only when there is a library update in the background that it is not displayed.

**Comment by j4hangir** [comment]
> It is still there It's only when there is a library update in the background that it is not displayed.

Strange, I don't see any update going on, is there a way to check if one is progressing in the background? As far as I can see, it has fully scanned and finished, yet Add and Remove are missing.

**Comment by vdesabou** [comment]
Add/ Remove are possible in multiple places. For example
https://alfred-spotify-mini-player.com/articles/add/

Where is it missing exactly?
-- 
Vincent de Saboulin

**Comment by j4hangir** [comment]
Thanks, if I select the current track then `Add` is indeed enlisted, it was previously however available through the `shortcut -> main command`.

Is there a way to restore the old behavior or modify the available actions when using the shortcut?

**Comment by vdesabou** [comment]
Sorry I dont’t understand what you mean by shortcut main command.
Can you elaborate and or copy some screenshots of what you mean ?

**Comment by j4hangir** [comment]
Not a problem, we need to set a shortcut to open `Spotify Mini Player`, I've set a shortcut and before, I could use the shortcut, then type either `Add` or `Remove`, and immediately perform that action.

Now what you said has added an extra step, I need to use the shortcut, select `Current track`, then type Add/Remove to perform the action.

**Comment by vdesabou** [comment]
You mean this ?

![CleanShot 2022-10-20 at 18 23 22](https://user-images.githubusercontent.com/4061923/197004747-f3a940bc-55bd-45cf-ba9e-070236678c80.jpg)

**Comment by j4hangir** [comment]
Exactly, I have to say after upgrading Alfred and deleting refreshing the library multiple times it's showing up again! 

Thank you for paying attention, I'm gonna close this issue for now and keep an eye for it whether it reoccurs.
