### ISSUE TITLE
Music won't play

### ISSUE THREAD

**Issue by dr-code** [vdesabou/alfred-spotify-mini-player#587]
Not sure what's going on but I followed all the instructions. I was initially having trouble authenticating but that worked itself out. But now I can't play any music. I have attached a video file showing you but no music is played. I apologize for the bad quality, used Adobe Express to convert the video into a GIF. 

I do not get any notifications either whether something has failed or not.

Thanks

![Uploading Screen_Recording_2022-11-19_at_8_46_58_AM_AdobeExpress.gif…]()

**Comment by vdesabou** [comment]
I can’t see the video. Let’s continue the troubleshooting by email. Please follow https://alfred-spotify-mini-player.com/articles/support/
