### ISSUE TITLE
Setup is stuck on initialisation phase

### ISSUE THREAD

**Issue by pawlinsky** [vdesabou/alfred-spotify-mini-player#588]
Hi,

I don't now if this is related to the Spotify API itself or if its a workflow kinda problem, but after authentication I got stuck during the setup process in the initialisation process. Message is: `Waiting for Spotify servers to return required data... `Since yesterday I cannot initialise my library.

Any help/ideas?

**Comment by vdesabou** [comment]
You can kill library update with spot_mini_kill command and try again

if still working send an email by following https://alfred-spotify-mini-player.com/articles/support/

**Comment by pawlinsky** [comment]
Ok, I've killed it many times. I started new library update today, and now it's creating the library. 

Thx
