### ISSUE TITLE
can't authenticate

### ISSUE THREAD

**Issue by bikeatefoucault** [vdesabou/alfred-spotify-mini-player#59]
i'm on php 5.6

does it need to be 5.5?

**Comment by vdesabou** [comment]
I'm not sure I've never tested with PHP 5.6, but  it depends on the error you get. Can you describe a little bit more what's the problem?
Can you follow instructions here http://alfred-spotify-mini-player.com/articles/support/ and send me TGZ file to the email indicated in the page.

**Comment by bikeatefoucault** [comment]
i'm on 10.8.5...seems that's the problem.

**Comment by vdesabou** [comment]
Yes you need PHP version 5.4+, see the list of known issues on the site and the link to workaround. You will need to edit the action.php file for authentication to point to your PHP 5.6 installation. I am using PHP builtin server for authentication. So PHP 5.4+ shall be necessary only for this step.
Let me know if you need more techy details..


Vincent

**Comment by bikeatefoucault** [comment]
once i finally figured out how to open the workflow (first time, was trying to extract with pacifist at first) it seems to be working. whatever localhost callback page is supposed to come up after authorizing with spotify failed to load, but it seems to be working (library is being created)

**Comment by vdesabou** [comment]
>once i finally figured out how to open the workflow (first time, was trying to extract with pacifist at first) it seems to be working. whatever localhost callback page is supposed to come up after authorizing with spotify failed to load, but it seems to be working (library is being created)

Ok let me know if you get other issues.
I'll think about improving this process..
