### ISSUE TITLE
Doesn't work after update 12.1

### ISSUE THREAD

**Issue by romantech** [vdesabou/alfred-spotify-mini-player#590]
It worked very well when I used the 12.0 version of the workflow. 
However, after updating to version [12.1](https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v-12.1), when I type `spot_mini` in the Alfred window, nothing appears. 

## What I tried
- Check Client ID/Secret were entered correctly
- Deleting and reinstalling the workflow
- Re-authenticate to Spotify
- Delete artwork folder

## Debug console
The output of the debug console at the time of entering `spot_mini` is as follows:

![20221127_135754@2x](https://user-images.githubusercontent.com/8604840/204120304-11f332b1-94a8-4110-b9af-44e5c4d9c08a.png)

## Other relevant information
- macOS Version: 13.0.1 (Ventura)
- Alfred Version: 5.0.5
- PHP Version: PHP 8.1.13 (Installed via brew)

**Comment by joninho88** [comment]
Same issue for me!

**Comment by vdesabou** [comment]
Sorry about that, 12.1 is a pretty big change in terms of config handling..

Can you download 12.2 and then activate debug:

![CleanShot 2022-11-27 at 11 42 01@2x](https://user-images.githubusercontent.com/4061923/204131076-5427379c-009c-4d1e-8e84-e608cdcaa3f2.jpg)

Then click on debug mode in Alfred:

![CleanShot 2022-11-27 at 11 42 17@2x](https://user-images.githubusercontent.com/4061923/204131090-41dc298c-5017-4c96-b2dc-54b080567d58.jpg)

Then call the workflow again and share the results you get in debug window at the bottom

**Comment by romantech** [comment]
> Sorry about that, 12.1 is a pretty big change in terms of config handling..
> 
> Can you download 12.2 and then activate debug:
> 
> ![CleanShot 2022-11-27 at 11 42 01@2x](https://user-images.githubusercontent.com/4061923/204131076-5427379c-009c-4d1e-8e84-e608cdcaa3f2.jpg)
> 
> Then click on debug mode in Alfred:
> 
> ![CleanShot 2022-11-27 at 11 42 17@2x](https://user-images.githubusercontent.com/4061923/204131090-41dc298c-5017-4c96-b2dc-54b080567d58.jpg)
> 
> Then call the workflow again and share the results you get in debug window at the bottom

![20221127_204448@2x](https://user-images.githubusercontent.com/8604840/204133520-341cf2bf-c8fc-447b-acdf-9f176922f31c.png)

**Comment by vdesabou** [comment]
Should

**Comment by vdesabou** [comment]
Should be fixed with 12.3, can you confirm ?

**Comment by romantech** [comment]
> Should be fixed with 12.3, can you confirm ?

Works fine 🎉
<img width="718" alt="20221127_231908@2x" src="https://user-images.githubusercontent.com/8604840/204140082-d84a819f-b8ad-47de-a0c1-b3cd0e706ae0.png">
