### ISSUE TITLE
Hotkey to Spotify Connect to Preferred Device

### ISSUE THREAD

**Issue by jwmann** [vdesabou/alfred-spotify-mini-player#596]
I'm not sure what the config for Preferred Spotify Connect Device is used for but it would be super useful to tell Spotify to Connect to my preferred device manually via Hotkey

Please let me know if that's possible.

Thank you!

**Comment by vdesabou** [comment]
If you use Spotify Connect and set preferred device, it will always use it for the output. Not sure hotkey would be relevant here.

**Comment by jwmann** [comment]
> If you use Spotify Connect and set preferred device, it will always use it for the output. Not sure hotkey would be relevant here.

It's for when Spotify is already playing from a different device, I'd like to switch it to my computer (my preferred device) without having to pause/play the music. Say if I'm listening to spotify in my house and then sit at my computer, I can just press a button to change the device to my computer.

**Comment by vdesabou** [comment]
@jwmann That makes sense, I'll add it in 12.5:

![CleanShot 2023-01-02 at 21 35 54@2x](https://user-images.githubusercontent.com/4061923/210276235-954b6feb-3fbf-415b-abfe-29caf99dd584.jpg)
