### ISSUE TITLE
Spotify 10000 track limit

### ISSUE THREAD

**Issue by patrickrushton** [vdesabou/alfred-spotify-mini-player#599]
I'm curious about what's written on the [Known Issues](https://alfred-spotify-mini-player.com/known-issues/) page:

> You cannot have more than 10000 tracks in Your Music.

Now that Spotify has [removed the 10000 tracks limitation](https://community.spotify.com/t5/Community-Blog/Save-save-save/ba-p/4963349) in the library, how does that affect the API. If there's still a limit in place, what are the implications of this for the mini player? Will it only shuffle the first 10000 tracks or does it simply stop functioning altogether?

**Comment by vdesabou** [comment]
Thanks for reporting, I was not aware it was removed.
I think the workflow should be fine. I've removed this limitation in the docs.
