### ISSUE TITLE
Can't save songs on latest version of Workflow

### ISSUE THREAD

**Issue by veerapursandesh** [vdesabou/alfred-spotify-mini-player#601]
I have been using the workflow for the past one year and I have faced no issues until after the recent update. 
I can no more save current playing song to my Spotify library. Earlier there would be an option called as `Add Current song to Library` which would save the current playing song into my account's `liked songs` playlist. The option `Add Current song to Library` is not available at all any more when I search for different action options available on the workflow. Please help!

**Comment by Cardosaum** [comment]
Sorry for reopening, but I'm facing the same issue and I don't know how to fix... Any direction on how to solve it?
