### ISSUE TITLE
Keyboard media controller not working

### ISSUE THREAD

**Issue by adautovjr** [vdesabou/alfred-spotify-mini-player#606]
On my MacOs Ventura 13.4, once I use spot_mini_player to choose a song to be played, I can no longer press my keyboard's play/pause, next and previous songs button to control my music. Everything works well with spot_mini_player controls, but something seems to be blocking my media controls on the keyboard.

Please let me know if I can help out with any more details.

**Comment by vdesabou** [comment]
I really don't see how the workflow could block that.

**Comment by adautovjr** [comment]
Yeah. I believe it's not the workflow causing this. I have another instance of macOs running without the workflow and it still happens. Sorry for that, I'll be closing this issue.
