### ISSUE TITLE
[FR] Remove from all playlists 

### ISSUE THREAD

**Issue by csss1234** [vdesabou/alfred-spotify-mini-player#607]
I have a hundred or more playlists, ever since I moved (and matched) from iTunes years ago. IFTTT adds to some of them automatically, it’s a complex setup.

sometimes I hear a song I hate, and see that it’s on 3 different playlists. Would love an option to remove from all.

**Comment by vdesabou** [comment]
Sorry but I don't think that's a feature (library cleanup) that fits for this workflow. I'll close that one.
