### ISSUE TITLE
Cannot modify library while in progress

### ISSUE THREAD

**Issue by geraldaddey** [vdesabou/alfred-spotify-mini-player#608]
After adding a few songs to my playlists, I went ahead to refresh my Spotify library. 

The status after 48 hours shows : Refresh Library in progress since 22hr 25min.  The refresh however doesn't seem to complete. I am unable to add or remove from playlists. I also have custom keywords for many actions and uninstalling the workflow won't help.
 
 NB: I changed my command from 'spot_mini' to 'sp'
 
![screenshot  2023-07-05 at 4 00 49 PM](https://github.com/vdesabou/alfred-spotify-mini-player/assets/42818198/f65c7f06-f128-4dfe-9bb0-7c206e22b9e7)

anytime i try to made an addition to my library, i'm prompted with this error.
![screenshot  2023-07-05 at 4 15 58 PM](https://github.com/vdesabou/alfred-spotify-mini-player/assets/42818198/3f5eb436-fd32-43de-8ce7-2bf49c162738)

**Comment by jwmann** [comment]
I had this issue recently and fixed it by running the kill update library command.

Even if you renamed `spot_mini` to `sp` use `spot_mini` to find it
![image](https://github.com/vdesabou/alfred-spotify-mini-player/assets/436270/70daefcc-76ba-4129-b7c5-d21cb51cafa6)

Once it's killed I'd recommend rebuilding the library from scratch which you can find within the Settings.
This option only shows up once the library is no longer refreshing (after you've killed it)

![image](https://github.com/vdesabou/alfred-spotify-mini-player/assets/436270/45e6dc64-730f-42e2-9d96-5c3fef57c9e9)

**Comment by geraldaddey** [comment]
@jwmann Thanks for the solution. It works as expected.
