### ISSUE TITLE
The workflow cannot be authenticated when using Sonoma Beta

### ISSUE THREAD

**Issue by gaaiyeoi** [vdesabou/alfred-spotify-mini-player#609]
Encounter: After configuring ClientID and ClinetSecret, now I can't wake up the identity authentication interface with spot_mini. The results are shown in the figure.
![image](https://github.com/vdesabou/alfred-spotify-mini-player/assets/129256589/407b4096-07d4-4caf-ad55-b52132c91f54)
Current configuration:
![image](https://github.com/vdesabou/alfred-spotify-mini-player/assets/129256589/0584bc46-b8d2-4a5a-bc5d-97959599af00)
![image](https://github.com/vdesabou/alfred-spotify-mini-player/assets/129256589/1281fb02-62e7-4351-9993-b3225f7f4e59)
![image](https://github.com/vdesabou/alfred-spotify-mini-player/assets/129256589/c4fe5454-ebc7-4523-9638-7a7117794a01)
![image](https://github.com/vdesabou/alfred-spotify-mini-player/assets/129256589/cea7b16e-e37e-4f90-b451-c942f17e5d5b)
**After I updated the MacOS 17 Sonoma Beta version, there seems to be a problem with this workflow. I tried to use the debug command, but it didn't seem to be triggered. I'm sorry to bother the developer to check this problem. I'm looking forward to receiving a reply from the developer!!!**

**Comment by gaaiyeoi** [comment]
@vdesabou

**Comment by jaczkal** [comment]
same problem

**Comment by jcarlos7121** [comment]
same here

**Comment by vdesabou** [comment]
I can't install Sonoma Beta so cannot reproduce the issue.
You might need to check debug logs when you type spot_mini:

![CleanShot 2023-08-29 at 09 41 28@2x](https://github.com/vdesabou/alfred-spotify-mini-player/assets/4061923/9b20daa4-e304-4035-b89b-58f29304962b)


What output do you get ?

**Comment by gaaiyeoi** [comment]
@vdesabou Hello vdesabou,This is output:
<img width="1503" alt="image" src="https://github.com/vdesabou/alfred-spotify-mini-player/assets/129256589/4098d911-a468-4935-ad0e-27df7c826443">


> I can't install Sonoma Beta so cannot reproduce the issue. You might need to check debug logs when you type spot_mini:
> 
> ![CleanShot 2023-08-29 at 09 41 28@2x](https://user-images.githubusercontent.com/4061923/263939703-9b20daa4-e304-4035-b89b-58f29304962b.jpg)
> 
> What output do you get ?

**Comment by vdesabou** [comment]
It's not really a workflow issue, but rather a homebrew/php installation issue..

I've found 2 links that might be relevant:
https://nono.ma/dyld-library-not-loaded-opt-home-brew-opt-icu4c-lib-libicuio-68-dylib
https://github.com/Homebrew/homebrew-core/issues/120854

**Comment by gaaiyeoi** [comment]
> https://nono.ma/dyld-library-not-loaded-opt-home-brew-opt-icu4c-lib-libicuio-68-dylib

this link seems works !!!thanks!!! @vdesabou 
and  @jcarlos7121 @jaczkal you guys can try it !
<img width="1547" alt="image" src="https://github.com/vdesabou/alfred-spotify-mini-player/assets/129256589/236bfcb5-93f6-4ab9-9760-cf28c9f24ed3">
