### ISSUE TITLE
Dialog box keeps popping up

### ISSUE THREAD

**Issue by jdaeira** [vdesabou/alfred-spotify-mini-player#611]
I mapped a few key combinations to control moving to the next track and previous track just to name a few. All of sudden more often than not I receive I get this dialog box after I click on the key combination. Any idea how to get rid of this dialog box from always coming up?

Thank you in advance for any information. 

![spotify](https://github.com/vdesabou/alfred-spotify-mini-player/assets/9750361/1bfa264e-b16f-4307-872a-8fb37be55bea)

**Comment by jwmann** [comment]
I also have this issue with this dialog popping up randomly when a song changes

**Comment by vdesabou** [comment]
I've seen it myself, but not sure why this happens.

I'm using https://github.com/vitorgalvao/notificator, I'll ask him if he has an idea about this

**Comment by vdesabou** [comment]
> The good news is that I know why it happens. The dialog pops up if <kbd>⌃</kbd> (ctrl) is pressed at the time the app is run. You can try it easily by holding it down before a notification shows.
> 
> 
> 
> The bad news is that I searched for it many years back and found no way to prevent that. It’s an AppleScript app thing. In the past I even tried various tricks such as detecting if <kbd>⌃</kbd> was held down before the script was run and delaying it until it was released, but ultimately I could still trigger, it’ll always be a timing matter.

I will close this issue since this is identified and can't do anything about it
