### ISSUE TITLE
Feature request: Notificator icon matches Now Playing song/album cover, so does the Now Playing episode

### ISSUE THREAD

**Issue by Ender-Wang** [vdesabou/alfred-spotify-mini-player#614]
It would be great if you can consider this feature, making the Notificator icon matches the album cover, it would look fantastic. This is what looks like ATM:
<img width="348" alt="image" src="https://github.com/vdesabou/alfred-spotify-mini-player/assets/33310255/fc368562-5ed6-454a-9594-2d3f87d62955">

This is what could look like for every song:
<img width="348" alt="image" src="https://github.com/vdesabou/alfred-spotify-mini-player/assets/33310255/f4c27e34-6c20-4e5c-984a-3b18773dcb55">

**Comment by vdesabou** [comment]
It was possible at some point in previous Mac OS versions (I was using https://github.com/julienXX/terminal-notifier which was using a private method for that), but it is no more possible now.

I switched to https://github.com/vitorgalvao/notificator now.

But this is still not possible to set a specific icon in the notification
