### ISSUE TITLE
Refresh Library Hanging Forever

### ISSUE THREAD

**Issue by stdavis** [vdesabou/alfred-spotify-mini-player#621]
For the past few months, I've been stuck on "Refresh Library in progress...".
<img width="722" alt="image" src="https://github.com/vdesabou/alfred-spotify-mini-player/assets/1326248/313f2839-c48c-4c9a-aac5-97976a392d4f">

macOS: `Ventura 13.6.1`
Mini Player Workflow version: `v13.0`

I've tried running `spot_mini_kill` and restarting the refresh with no luck. It seems to always be stuck on a podcast. I've removed a bunch of podcasts from my library but it still seems to get stuck. I wondered if it was because I have the explicit filter turned on and some episodes are unavailable.

I'll send you the debug logs in an email.

Thanks so much for this awesome project. I love it!

**Comment by csss1234** [comment]
Mine is stuck here, I never see the count of process. Was working fine a couple weeks ago
![image](https://github.com/vdesabou/alfred-spotify-mini-player/assets/45954264/626c519b-780f-4ef3-a57d-03ab225ba3ca)
```
Warning: Undefined array key "error" in /Users/xxx/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.574202A7-FF85-413B-8109-511345062ED9/callback.php on line 134
There was an error during authentication (exception SpotifyWebAPI\SpotifyWebAPIException: code 429 Too many requests at SpotifyWebAPI.Request.handleResponseError(Request.php:59) at SpotifyWebAPI.Request.send(Request.php:242) at SpotifyWebAPI.Request.api(Request.php:132) at SpotifyWebAPI.SpotifyWebAPI.sendRequest(SpotifyWebAPI.php:124) at SpotifyWebAPI.SpotifyWebAPI.me(SpotifyWebAPI.php:1556) at (main)(callback.php:29))
```

Did a little googling. Others say they cant access https://open.spotify.com but I can.

So then I tried re-authenticating and I get the same 429 error. Emailed debug

**Comment by stdavis** [comment]
I'm still having the issue as well. I miss using this workflow!

**Comment by csss1234** [comment]
> I'm still having the issue as well. I miss using this workflow!

do you have a billion tracks like i do? I can't think of anything else I changed recently except adding ~20k tracks in several playlists.

**Comment by stdavis** [comment]
No, I don't have that many tracks. The refresh hangs on podcasts.

**Comment by csss1234** [comment]
![image](https://github.com/vdesabou/alfred-spotify-mini-player/assets/45954264/34088684-f595-4291-ac41-5e5774009d9a)
@stdavis Have you checked your developer dashboard? https://developer.spotify.com/dashboard

**Comment by csss1234** [comment]
Yes that was it. Had to create a new app in the dashboard.

**Comment by stdavis** [comment]
Yes, I checked it and mine shows "Development mode" under "App Status". @vdesabou does that sound correct to you?

**Comment by csss1234** [comment]
Strange. Since getting it working, i have a new problem. Spot mini library keeps disappearing, and I am back to the main startup workflow with one option: create library. So, it is creating the library, and then everything works, but then 6-12 hours later, there is no library/not working.

**Comment by vdesabou** [comment]
@stdavis Can you send me another debug email please ? I'll have to try to create your library on my end to see exactly what happens. The playlist I investigated the other time was working fine for me, so it must be something else
