### ISSUE TITLE
authentication not working after upgrading to 13.2

### ISSUE THREAD

**Issue by anguila** [vdesabou/alfred-spotify-mini-player#625]
Hi,
The workflow used to work perfectly, I updated to latest version (which now i deeply regret..) and then auth stopped working.

I tried to:
- reinstall workflow
- downgrade workflow to different versions >10, 12, 13
- reset settings
- re-authenticate many times
- manually remove workflow folder
- create a new spotify app with new client id & secret
- uninstall spotify and reinstall
- close/open alfred

Nada :(

After a successful authentication i'm getting stuck at this when i trigger hotkey
![image](https://github.com/vdesabou/alfred-spotify-mini-player/assets/6177590/757cefc1-1bda-40a5-b94f-9cab60234c61)

Has anyone been experiencing this too? Any idea what could I do to get it to work again?

Thanks,

David

**Comment by vdesabou** [comment]
Hey David,

I just tested again with 13.2 and all is working for me.

If you have successful auth, normally you should see some values set in there:

![CleanShot 2024-03-10 at 10 19 49@2x](https://github.com/vdesabou/alfred-spotify-mini-player/assets/4061923/5a63e9ca-1eca-4ea4-a613-13be3bbe52dd)

If that's not the case, it means Alfred is not saving the values.

We've seen it in the past with old version of Alfred, see https://github.com/vdesabou/alfred-spotify-mini-player/issues/585#issuecomment-1337704835

What's your Alfred version?

**Comment by vdesabou** [comment]
Just seeing your email:

```
alfred_version:5.0
alfred_version_build:2064
```

Looks like you're using the impacted Alfred version ?

Please upgrade Alfred
