### ISSUE TITLE
"The application spot mini player cannot be opened"

### ISSUE THREAD

**Issue by kashour** [vdesabou/alfred-spotify-mini-player#628]
Hi
I'm on Sonoma 14.2.1 but had this problem on other versions and usually give up on installing the workflow
I'm following the instructions exactly 
I get to the point up to adding client and secret ID then there is an instruction to launch spot_mini through alfred to build a library and i keep getting the error in the subject line, it shows in a native MacOs prompt
Thanks

**Comment by vdesabou** [comment]
Which version are you using ? SpotifyMiniPlayer app was removed in 13.0, see "Update workflow for Alfred Gallery #603"
