### ISSUE TITLE
Tracks are not getting added to my library

### ISSUE THREAD

**Issue by waynehoover** [vdesabou/alfred-spotify-mini-player#630]
When I add a track to "Your Music" it's not showing up in my liked songs in Spotify. 

Also when I add a track to a playlist it is not showing up in Spotify. But if I "Play Alfred Playlist" (A playlist I created in the mini player) then it plays all the songs, but in Spotify there is no such playlist.

I do believe this was working but it seems to have stopped.

I have the "Your Music" option selected, and I don't see anything suspicious in the bug pain in Alfred or the event log.

**Comment by vdesabou** [comment]
just tested, still working on my side.. you can check the logs using https://alfred-spotify-mini-player.com/articles/support/

**Comment by waynehoover** [comment]
I have sent you a debug email.

**Comment by waynehoover** [comment]
Looks like this was a data issue, when I deleted all my files and rebuilt the cache it started working again.
