### ISSUE TITLE
"Web API Exception: 400 - Missing required field: ids" when add current song to My Music

### ISSUE THREAD

**Issue by csss1234** [vdesabou/alfred-spotify-mini-player#631]
This just started happening a day or two ago, for all tracks, whether I trigger via applescript or through the menu. Other features are working fine, though. 

emailed debug to you Sep 29 '24

**Comment by vdesabou** [comment]
I reproduce the same error. Looks like Spotify changed their [API](https://developer.spotify.com/documentation/web-api/reference/save-tracks-user)..

I depend on external library so I opened https://github.com/jwilsson/spotify-web-api-php/issues/278

**Comment by SideMatter** [comment]
+1 to this, I'm having this issue as well.
