### ISSUE TITLE
Do not switch back to the Spotify app

### ISSUE THREAD

**Issue by madchap** [vdesabou/alfred-spotify-mini-player#632]
Hi there,

Thanks a lot for your workflow :)

I have one minor question, I could not find in the documentation or in the settings. Is it possible to _not_ switch back to the main Spotify app whenever we choose a new album to play, etc... ?

Thank you.

**Comment by vdesabou** [comment]
Hey, 

I'm not able to reproduce this, see https://www.alfredforum.com/topic/1892-spotify-mini-player-control-your-spotify-library-at-your-fingertips/page/23/#findComment-111497

**Comment by madchap** [comment]
Merci Vincent.

I am a premium user, and I do use Connect to put the music through external speakers. At the same time, I have Desktop opened at all times. I never used Connect through the workflow, however.

Not sure if it changes anything, but for a test, I put the music through my computer  (Spotify Desktop only then I guess?), navigated to a different Space, invoked the workflow through Alfred and it also brought me back to the Space where Spotify Desktop is running.

**Comment by liCells** [comment]
Hey,

I'm having this problem too.

When using the Spotify Mini Player Workflow to select and play a song from a playlist, the Spotify main window automatically gains focus. However, this issue does not occur when using the "Previous" or "Next" track controls.

### Environment Information

Device: MacBook M1
Operating System: macOS Ventura 13.4.1
Alfred Spotify mini player: Version [13.4]
PHP:
```zsh
PHP 8.3.9 (cli) (built: Jul 2 2024 14:10:14) (NTS)  
Copyright (c) The PHP Group  
Zend Engine v4.3.9, Copyright (c) Zend Technologies  
    with Zend OPcache v8.3.9, Copyright (c), by Zend Technologies
```
Spotify:
```
Spotify for macOS (Apple Silicon)  
Version: 1.2.51.345.gcc39d911  
```

**Comment by vdesabou** [comment]
I can finally get same behaviour

Seems like applescript command like 

```
tell application "Spotify" to play track "spotify:track:6rqhFgbbKwnb9MLmUQDhG6"
```

is forcing now the window to activate. This was not the case before..

I don't see what I can do about that, it's a change in Spotify Applescript app..

The workaround is to use Spotify Connect (if you're premium user)

**Comment by vdesabou** [comment]
All I can do is to close window right after it activates, that will still show a glitch though. This will be available in 13.5

**Comment by liCells** [comment]
My usual habit is to keep different apps on separate desktops.😂

Right now, the behavior is that it switches to Spotify (and also to its desktop) and then hides the corresponding window.

End, I just see a blank desktop.

Sorry for my poor English.

> I tried Spotify Connect and it worked perfectly.

**Comment by chadify** [comment]
The bug is still present, I'm a spotify premium user as well.
