### ISSUE TITLE
"Alfred Playlist" not taking precedence over "Your Music" 

### ISSUE THREAD

**Issue by repsejnworb** [vdesabou/alfred-spotify-mini-player#634]
Maybe I am misunderstanding something, but I understood the settings as disabling "Control Your Music" would make the playlist I've set as "Alfred Playlist" to be the default of searches etc.

<img width="507" alt="image" src="https://github.com/user-attachments/assets/1abd4f58-1996-4f62-bb46-6cc2c6ec16bf" />

But it still limits its searching to "Your Music" (notice the "path" under hits)

<img width="701" alt="image" src="https://github.com/user-attachments/assets/5c3bceb4-4c72-4ee4-bd1a-3a35beb01c60" />

<img width="704" alt="image" src="https://github.com/user-attachments/assets/7bd22f83-5ada-49b1-bdbb-9c1faa974c8d" />

As someone who has had Spotify since before it went public, I have had all my music in a single ultimate playlist, never moving to the "new ways" that Spotify has put forth year after year.
And searching in that playlist as default is the only way for me to enjoy this workflow.

**Comment by vdesabou** [comment]
what "control alfred playlist" does is described there https://alfred-spotify-mini-player.com/articles/alfred-playlist/
it is not meant for what you're looking for, sorry
