### ISSUE TITLE
Important: workflow not working with Spotify version < 1.0.3 (fixed with 1.0.3)

### ISSUE THREAD

**Issue by chriscarter90** [vdesabou/alfred-spotify-mini-player#66]
Hi @vdesabou,

Thanks for making this awesome extension. It's really useful... __when it seems to work__. _hmph_

It seems that the Alfred extension is working well - whenever I run any commands it shows me the little toast notification in the top corner.

When I have version `0.9.15.27.g87efe634` installed, everything works well. I get that version from downloading the installer from the Spotify site. However, when it updates itself to (what I can only presume is the newest version) 1.x, it stops working. Spotify completely ignores all my commands to it.

I've filled out the __My Applications__ section on the developer site as instructed by your guide, using the correct Client ID and Secret...

Am I missing something daft?

Thanks in advance!

**Comment by vdesabou** [comment]
Hi,

0.9.x version is the supported version.
1.x version is in Beta and has not AppleScript support, that's why the workflow can't work with this version yet.

But normally, Spotify should not auto-update from 0.9.x to 1.x... 
I've SpotifyBeta (1.x) installed on my laptop but I downloaded it from Spotify forums. 
Are you sure it was an auto-update?

**Comment by chriscarter90** [comment]
Ah okay. I wasn't aware - I tried trawling the Spotify site briefly to try and find some kind of versioning but didn't get anywhere. I will keep an eye on it and see what happens. Could it be that when I removed Spotify from Applications it was "caching" somehow a newer version which I had installed previously?

**Comment by vdesabou** [comment]
No idea.

As I understand it, if you get the Spotify Beta from here, https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Welcome-to-the-Desktop-Beta/td-p/932803 it is a separate SpotifyBeta application. If you download from the main download link, it is 0.9 version. 

You should use 0.9 version to use the workflow.

**Comment by chriscarter90** [comment]
Okay thanks for clearing that up.

**Comment by chriscarter90** [comment]
Ah hah, here we go. I just got a banner in Spotify, from v0.9:

![screen shot 2015-03-03 at 11 36 05](https://cloud.githubusercontent.com/assets/1398210/6461630/972d2b4c-c199-11e4-9ca0-f0f3f3fa0d85.png)

I clicked it to see what version it would update to, and turns out it's `1.0.1.1060.gc75ebdfd`...

**Comment by chriscarter90** [comment]
And bam, the extension stops working.

**Comment by vdesabou** [comment]
Hmm ok..is this the version with lyrics included?
I will have a look, but if they removed apple script supoort..that's not good at all...

Vincent

**Comment by chriscarter90** [comment]
I'm guessing by this at the bottom that it is:

![screen shot 2015-03-03 at 11 49 01](https://cloud.githubusercontent.com/assets/1398210/6461781/53e09db8-c19b-11e4-8154-1687f61244be.png)

Sorry to be the bearer of bad news - I love this workflow and if I need to avoid updating Spotify to keep it I will!

**Comment by vdesabou** [comment]
Ok I've been able to upgrade Spotify to ```1.0.1.1060.gc75ebdfd```and I have applied workaround explained in this [post](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Apple-scripting-broken-in-1-0-1-988-g8f17a348/td-p/1029434)

Can you give it a try as well? You'll need to restart Spotify after modifying info.plist

On my side, commands like next/mute/play/etc. are working, but command play track is not working..
So the workflow cannot launch tracks or playlists for example..

**Comment by chriscarter90** [comment]
Yeah I get the same. I can do basic things but not launch tracks, playlists, or get the info of the current song or anything like that.

**Comment by vdesabou** [comment]
It's strange that you cannot get the info on current track, it s working for me "Current Track"

I reported the issue to Spotify. We'll need to wait for a fix I'm afraid..

**Comment by chriscarter90** [comment]
Glad to be of help. (ish.)

**Comment by vdesabou** [comment]
Maybe you can install again 0.9.x and prevent auto-update, there is a tutorial for this here http://supraliminal.net/blog/2013/4/21/how-to-revert-back-to-the-older-better-spotify-client , see from "3 . Stop Spotify auto updating" for OS X

**Comment by chriscarter90** [comment]
Wonderful. Thanks!

**Comment by vdesabou** [comment]
Blog post about this problem: 

http://alfred-spotify-mini-player.com/blog/issue-with-latest-spotify-update/

**Comment by vdesabou** [comment]
Version 6.1.1 will help to detect the problem, see https://github.com/vdesabou/alfred-spotify-mini-player/issues/67

**Comment by vdesabou** [comment]
AppleScript is working again with Spotify 1.0.3, see [release notes](https://community.spotify.com/t5/Spotify-Announcements/Release-Notes-Spotify-for-Desktop/m-p/1075314)

**Comment by vdesabou** [comment]
Closing. I expect everybody is now updated to 1.0.3
