### ISSUE TITLE
Delete Client ID and Client Secret

### ISSUE THREAD

**Issue by Lucaaas** [vdesabou/alfred-spotify-mini-player#69]
Hi,

I try to delete my client ID and my Client Secret for the app but I can't !

spot_mini_reset doesn't work !

How can I totally reset the workflow ? 

I've tried to delete it but it doesn't work too.

Thank you :)

**Comment by Lucaaas** [comment]
I've tried to authentify but it doesn't work neither.

INVALID_CLIENT: Failed to get client

**Comment by vdesabou** [comment]
Hi,

>spot_mini_reset doesn't work !

I really would like to understand why it doesn't work, do you invoke alfred, type 'spot_mini_reset' and then hit enter? Do you get a notification saying the file cannot be deleted?

Can you send me the TGZ file as explained here http://alfred-spotify-mini-player.com/articles/support/ ?


To reset the workflow manually, you can invoke `spot_mini_debug ` and then choose Browse to App Support folder, then in Finder, delete the file settings.json and then invoke the workflow again

**Comment by Lucaaas** [comment]
Hi,

Thank you for your response

When I type "spot_mini_reset" and then hit enter, I have no notification.

I can't add a TGZ file to this comment so here it is : http://we.tl/Vu6fTDHIPn

I manually delete the file settings.json and I start again... It's working !!!!

Thank you very much !!

P.S. You can close ;)
