### ISSUE TITLE
Syntax error with AppleScript

### ISSUE THREAD

**Issue by Lucaaas** [vdesabou/alfred-spotify-mini-player#70]
Hey,

I'm sorry but I have another issue : 
"spot_mini_debug AppleScript Exception: 48:53: syntax error: Expected “then”, etc. but found identifier. (-2741)"

My version of spotify is : 1.0.2.6.g9977a14b

So the player start but not the tracks.

Thank you

**Comment by vdesabou** [comment]
Everything is explained here http://alfred-spotify-mini-player.com/blog/issue-with-latest-spotify-update/

There is a big red banner when you go on the web site http://alfred-spotify-mini-player.com :smile:

**Comment by vdesabou** [comment]
Duplicate https://github.com/vdesabou/alfred-spotify-mini-player/issues/66

**Comment by Lucaaas** [comment]
Ok thank You, I'm waiting the next version of Spotify :P

**Comment by vdesabou** [comment]
Normally it is fixed with 1.0.3, but I did not get the auto-update yet, and
there is no way to force it ,
https://twitter.com/TheMiniPlayer/status/582596809513652224

On Tue, Mar 31, 2015 at 12:15 PM, Lucaaas <notifications@github.com> wrote:

> Ok thank You, I'm waiting the next version of Spotify :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vdesabou/alfred-spotify-mini-player/issues/70#issuecomment-88029135>
> .
>



-- 
Vincent
