### ISSUE TITLE
"Playlist" (browse by playlist) list is empty

### ISSUE THREAD

**Issue by MartinAyla** [vdesabou/alfred-spotify-mini-player#72]
When I select "Playlist (browse by playlist)", the list is empty until I type 3 search characters.
 
I would like it to display all my Spotify playlists without having to type a search query, how do I do that?

**Comment by vdesabou** [comment]
This was caused by this playlist https://open.spotify.com/user/1267053306/playlist/2hiomd0iojOwz1H83Ky5SD having ```"```in its name. I fixed the code to handle this properly 

Can you try with this beta release http://inft.ly/HD6dQZX ?

You'll need to re-create the library from scratch (in Settings menu)

**Comment by MartinAyla** [comment]
It works with the beta release, thank you.
