### ISSUE TITLE
Mini  Player is loading playlists are from iTunes not from Spotify

### ISSUE THREAD

**Issue by jahco1980** [vdesabou/alfred-spotify-mini-player#75]
Hi, 

My mini player is loading all the playlists from my iTunes and not from Spotify. I have been using the mini player since 2013 and, before an update (I don't remember which one exactly, around August or September of 2014) the mini player was recognizing playlists from Spotify. After the update, the mini player just recognizes the playlists from iTunes. Any help with this would be great. Thanks.  

PS. This is perhaps the best workflow ever invented!! Thank you for that.

**Comment by vdesabou** [comment]
Hi, as as I sent you by email, it seems related to account when login in. Same as https://github.com/vdesabou/alfred-spotify-mini-player/issues/55 where user had a free account with email and premium account with Facebook, can you check this ?

**Comment by vdesabou** [comment]
Closing as per user's feedback " I just signed out, obtained my credentials for the Facebook account in the API and everything runs smoothly again!!!"
