### ISSUE TITLE
Trouble with Authenticating, don't think it is the same problem that is covered in known issues.

### ISSUE THREAD

**Issue by juskaiser** [vdesabou/alfred-spotify-mini-player#76]
I’m having some trouble completing the authentication step of the setup. When I initiate Spotify Mini Player in Alfred and then initiate the “Authenticate to Spotify” option a new browser tab opens. If I’m already logged in to my Spotify account I get the following error:

White browser page with this text below
“INVALID_CLIENT: Invalid redirect URI”

If I’m logged out of my account and initiate  the “Authenticate to Spotify” option I also get the new browser tab as expected. Also, I do get the normal login screen. However when I put in my credentials and try to log in nothing happens. However, I am able to log in to my Spotify account normally, it’s just  when I’m trying to authenticate that the log in isn’t processed.

I thought maybe this was related to the PHP version explained in the known issues. However, when I checked my PHP version in terminal it said that I had PHP version 5.5, so it doesn’t seem like it’s the same issue. Here is the PHP version that I got from terminal:

PHP 5.5.14 (cli) (built: Sep  9 2014 19:09:25) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

Sorry if I'm missing something here.

**Comment by vdesabou** [comment]
Closing.

From user: "Upon further inspection I saw the Redirect URI hadn’t been saved somehow. So after updating that everything works fine now."
