### ISSUE TITLE
Just 5 albums in "My Music"

### ISSUE THREAD

**Issue by eriksatie** [vdesabou/alfred-spotify-mini-player#78]
I can see only the last five added albums in "My music". Is it possibile to set a different number (higher)?

**Comment by vdesabou** [comment]
I see what's the problem. I'll work on a fix

**Comment by vdesabou** [comment]
Can you try this Beta release and let me know if everything is ok?

http://inft.ly/NHYFGPM

**Comment by eriksatie** [comment]
Now it works as before (many albums listed), but albums are in alphabetical order

**Comment by vdesabou** [comment]
Forgot to mention: try to add a track in your music to force update of the library

Vincent

**Comment by eriksatie** [comment]
great! it works

Davide Massussi

> Il giorno 16/apr/2015, alle ore 16:31, Vincent <notifications@github.com> ha scritto:
> 
> Forgot to mention: try to add a track in your music to force update of the library
> 
> Vincent
>

**Comment by vdesabou** [comment]
:+1: 
Closing
