### ISSUE TITLE
keyword input

### ISSUE THREAD

**Issue by pexxi2** [vdesabou/alfred-spotify-mini-player#79]
"You can also invoke keyword inputs from the main menu. You can access the list of keyword inputs by starting your search by a space, see example:-"

It´s not possible for me to input a space as first sign. If I do so Alfred replaces with a " ' " - sign

Thanks
a

**Comment by vdesabou** [comment]
Hi,

It's when you invoke the workflow with the hotkey as explained here http://alfred-spotify-mini-player.com/articles/hotkeys/ that you can use <space>.

Otherwise if you do not use hotkey (not recommended), you can invoke the hidden menu by typing <spot_mini  > (there are two spaces)

**Comment by pexxi2** [comment]
Hi,

OK i thought it was right from Alfred menu …thank you

A

**Comment by vdesabou** [comment]
No problem!
