### ISSUE TITLE
Add back volmid and volmax commands

### ISSUE THREAD

**Issue by roccitman** [vdesabou/alfred-spotify-mini-player#80]
Just wondering if you could suggest a tweak so when I use volume down it cuts the volume to say 30. Similar to using straight up applescript to cut 'sound volume'.
Thanks!

**Comment by vdesabou** [comment]
Hi,

You can eventually edit action.php file, line 1066 you have:

```
			} else if ($other_action == "volume_up") {
				if ($use_mopidy) {
					invokeMopidyMethod($w, "core.mixer.set_volume", array('volume' => invokeMopidyMethod($w, "core.mixer.get_volume", array()) * 1.1 ));
				} else {
					exec("osascript -e 'tell application \"Spotify\"
	                if it is running then
	                    set sound volume to (sound volume * 1.1)
	                end if
	            end tell'");
				}
				displayNotificationWithArtwork("Spotify volume has been increased", './images/volume_up.png', 'Volume Up');
				return;
			} else if ($other_action == "volume_down") {
				if ($use_mopidy) {
					invokeMopidyMethod($w, "core.mixer.set_volume", array('volume' => invokeMopidyMethod($w, "core.mixer.get_volume", array()) * 0.9 ));
				} else {
					exec("osascript -e 'tell application \"Spotify\"
	                if it is running then
	                    set sound volume to (sound volume * 0.9)
	                end if
	            end tell'");
				}
				displayNotificationWithArtwork("Spotify volume has been decreased", './images/volume_down.png', 'Volume Down');
				return;
			}
```

You see that I increase or decrease volume by 10% each time. You can change applescript to whatever you like.

If I understand correctly, you would like to be able to specify the sound volume by yourself, for example typing in Alfred ```volume 30```? Is that correct ?

**Comment by roccitman** [comment]
Ahh found it. Thanks. So by default it increments the volume up or down by ten percent.

So I changed those lines from:
set sound volume to (sound volume * 1.1)
set sound volume to (sound volume * 0.9)

to
set sound volume to 99
set sound volume to 30

(oddly, it didn’t work when I used 100, but does when I use 99)

Thanks!! Didn’t see a place on your site to donate to the development fund, let me know if I missed it.
-rocco

**Comment by vdesabou** [comment]
>So I changed those lines from:
set sound volume to (sound volume * 1.1)
set sound volume to (sound volume * 0.9)

>to
set sound volume to 99
set sound volume to 30

I see.. I will add a 'volmid' and 'volmax' commands (they used to exist at some point, but for some reason, I've removed them :smile: )
I'll add in next version !

>Thanks!! Didn’t see a place on your site to donate to the development fund, let me know if I missed it.

Yes there is a Paypal *Donate* button in my signature in every article for example http://alfred-spotify-mini-player.com/articles/mopidy/ :smiley: 

Thanks!

**Comment by vdesabou** [comment]
Hey thanks for the donation!! Really appreciated!!

**Comment by roccitman** [comment]
You bet!

**Comment by vdesabou** [comment]
I added volmid and volmax commands:


![capture d ecran 2015-05-01 a 13 40 55](https://cloud.githubusercontent.com/assets/4061923/7429754/c795d1a2-f007-11e4-9a73-8d1921b9e2cf.png)


Here is a link to Beta version of 6.2.2 if you want to test: http://inft.ly/4j9rdAZ

**Comment by roccitman** [comment]
Thanks man. Awesome! Again, oddly the vol max doesn’t work unless I change it to 99 (instead of 100). Must be my install or something. Oh well, nice work.

Really getting into the power of Spotify this year, and this is an excellent piece of software (and amazing use of Alfred). Next project is Mopidy but I’m bollocks with the command line so that’s a journey. The OS X client for Spotify is soo klunky.

**Comment by roccitman** [comment]
Btw here’s my changes: http://d.pr/n/1eaPS
