### ISSUE TITLE
No back button

### ISSUE THREAD

**Issue by rlipke** [vdesabou/alfred-spotify-mini-player#83]
Using the latest (6.2.1), I do not see a back button like the screenshots

![screen shot on 2015-05-27 at 20_16_06](https://cloud.githubusercontent.com/assets/222259/7850247/75a663f6-04ad-11e5-926e-d2269dbb6cbe.png)

I've tried all of the normal things: reinstalling (both Alfred and the workflow), refreshing library, etc.  

Any ideas?

**Comment by vdesabou** [comment]
Have a look at:
http://alfred-spotify-mini-player.com/articles/back-button/

Vincent

**Comment by rlipke** [comment]
Haha, wow how did I miss that?  Thank you much!
