### ISSUE TITLE
Issues on library creation

### ISSUE THREAD

**Issue by caceiro** [vdesabou/alfred-spotify-mini-player#84]
My Library for some reason is taking more than 30minutes to be updated, so with that the player is not working.

I have to kill the library and doesn't work.

**Comment by vdesabou** [comment]
Can you send TGZ file to email address here (http://alfred-spotify-mini-player.com/articles/support/)

I will have a look on Monday as I am on holidays abroad.


Vincent

**Comment by vdesabou** [comment]
Waiting for the TGZ file, I can't help without it

**Comment by vdesabou** [comment]
I'm really curious to see what's the problem. let me know when you can provide the TGZ file!

**Comment by vdesabou** [comment]
Closing as no way to investigate.
Re-open if you can provide the TGZ file..
