### ISSUE TITLE
Workflow takes Spotify app to foreground

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#88]
From this tweet: https://twitter.com/tomasherman/status/629761664372613120

I've reproduced the problem and it seems it only happens when Spotify window is minimized but Spotify is still selected as the current app, see screenshot below:

![capture_d ecran_2015-08-08_a_10_23_22](https://cloud.githubusercontent.com/assets/4061923/9149741/f4d07872-3db7-11e5-8e17-c2575f12b931.jpg)

There is nothing much I can do on my side, as I'm just using AppleScript and I don't use 'Activate'. To me it's more a bug with Spotify..

But if you're using other programs and run workflow commands, then I haven't seen the Spotify window taking focus, so most of the times it does not cause any issue.

**Comment by tomasherman** [comment]
Hi, i am the dude that made the tweet. Yep, it seems to only happen when spotify is selected. I will keep that in mind. By the way thanks for putting this workflow together, it's amazing. Im sure it took a lot of work!
