### ISSUE TITLE
Missing required parameter when authorize

### ISSUE THREAD

**Issue by CCOS** [vdesabou/alfred-spotify-mini-player#89]
When trying to authorize I get a " Missing required parameter" from the https://accounts.spotify.com/authorize/?client_id=xxxxxxxx

&response_type=code&scope=user-library-read+user-read-email+user-read-private+user-library-modify+user-follow-modify+user-follow-read+playlist-read-private+playlist-modify-public+playlist-modify-private+playlist-read-collaborative&show_dialog=true&state=

Using Chrome 45.0.2454.78 beta (64-bit) om OSX 10.11 Beta (15A262e)

**Comment by vdesabou** [comment]
Hi,

Your settings.xml file seems to be corrupted or not complete. 
Can you do execute in Alfred command:

```spot_mini_reset_settings```

It should delete settings.xml and then at next invocation of workflow, the setup process shall be done again.
After doing that and if it still not work, can you send another debug TGZ file by email?

Thanks

**Comment by CCOS** [comment]
Hi, still no luck

I am wondering how to reset the workflow so I have to insert the Client ID
and Client Secret again. Just deleting the workflow and installing it don't
do the trick so where do it store the Client ID and Client Secret ?

Jesper

I prefer dangerous freedom over peaceful slavery
The power to win lies in the courage to fail

Jesper Jepsen
23 36 54 39

2015-08-31 9:53 GMT+02:00 Vincent <notifications@github.com>:

**Comment by vdesabou** [comment]
You just need to call alfred and type ```spot_mini_reset_settings```

![screen shot 2015-08-31 a 10 41 41](https://cloud.githubusercontent.com/assets/4061923/9575058/dbd6a72a-4fcc-11e5-90e1-2ae1416479de.jpg)

And press enter

**Comment by CCOS** [comment]
2015-08-31 10:41 GMT+02:00 Vincent <notifications@github.com>:

> spot_mini_reset_settings


​There is maybe the problem, It dosen't do anything than leads me back to
the authentication process which fails :(  ​

Jesper


I prefer dangerous freedom over peaceful slavery
The power to win lies in the courage to fail

Jesper Jepsen
23 36 54 39

**Comment by vdesabou** [comment]
>​There is maybe the problem, It dosen't do anything than leads me back to
the authentication process which fails :(  ​

Ok, that's weird, can you provide a debug TGZ file for this?

To delete manually, choose Browse to App Support folder like this:

![screen shot 2015-08-31 a 11 25 33](https://cloud.githubusercontent.com/assets/4061923/9575832/f525676a-4fd2-11e5-9887-4718bcb58963.jpg)

And then delete the settings.son file

**Comment by vdesabou** [comment]
Did you solve your problem ?

**Comment by CCOS** [comment]
No it didn't. Not even deleting the files manually and installing a new
download did help.



I prefer dangerous freedom over peaceful slavery
The power to win lies in the courage to fail

Jesper Jepsen
23 36 54 39

2015-09-02 12:55 GMT+02:00 Vincent <notifications@github.com>:

**Comment by vdesabou** [comment]
Please send a new TGZ debug file in that case, i will have a look

**Comment by CCOS** [comment]
Got it...

Looks like I deleted files the wrong place. After removing them and
reinstalling the workflow I got it working.

thx for the support.

Jesper

I prefer dangerous freedom over peaceful slavery
The power to win lies in the courage to fail

Jesper Jepsen
23 36 54 39

2015-09-02 14:51 GMT+02:00 Vincent <notifications@github.com>:

**Comment by vdesabou** [comment]
Good :smile: 
No problem ! Bye
