### ISSUE TITLE
No longer playing tracks

### ISSUE THREAD

**Issue by templeman** [vdesabou/alfred-spotify-mini-player#90]
Spotify mini player has been working beautifully up until yesterday, when it began giving an error message any time I tried to play any track (local or not). I have no trouble browsing to the song or album, but upon selection Alfred gives the message:

Applescript execution failed!
sh: ./src/track_info.ksh Permission denied

I am using Spotify version 0.9.17.6.ge7d46329

**Comment by vdesabou** [comment]
Can you use ```spot_mini_debug ```command and then choose 'browse to Alfred Workflow folder', then open this folder into terminal and run:

cd src
ls -lrt 

And display results here, example:

```
$ ls -lrt
total 1184
-rwxr-xr-x  1 vdesabou  staff   17489 Feb 23  2015 workflows.php*
-rw-r--r--  1 vdesabou  staff    5467 Feb 23  2015 country_names.json
-rwxr-xr-x  1 vdesabou  staff     619 Mar 12 15:13 track_info.ksh*
-rwxr-xr-x  1 vdesabou  staff    4178 Mar 31 14:49 spotify_mini_player_notifications.ksh*
-rw-r--r--  1 vdesabou  staff   11498 Apr 17 10:28 debug.php
-rw-r--r--  1 vdesabou  staff   17786 Apr 20 10:36 main.php
-rw-r--r--@ 1 vdesabou  staff  182660 Jul 17 10:21 functions.php
-rw-r--r--@ 1 vdesabou  staff  287757 Jul 17 10:35 menu.php
-rw-r--r--@ 1 vdesabou  staff   53717 Jul 24 14:21 action.php
```

**Comment by templeman** [comment]
I seem to have resolved my issue after looking at #89. I saw that same "Missing required parameter" message after trying to clear settings and re-authenticate when I first ran into my issue. For me though, I was somehow able to reach the Spotify authentication page on subsequent tries. Then, after clicking Okay on Spotify, the callback page was giving an error and not displaying the success message that I was expecting. This behavior persisted despite my triggering spot_mini_reset_settings. Manually deleting the settings.json file allowed me to start over and complete the authentication process successfully. Now I can play tracks as before and everything appears to be working fine.

**Comment by vdesabou** [comment]
Ok thanks for the feedback.
I would be interested by a debug TGZ file as I don't understand why the reset settings is no working.
Can you send it by email ?

Thanks

**Comment by vdesabou** [comment]
Thanks for TGZ, I'm still puzzled why spot_mini_reset_settings is not working for some users..I can't find an explanation..

Also, even though authorization is working now, I still see errors:

```
sh: ./src/spotify_mini_player_notifications.ksh: Permission denied
sh: ./terminal-notifier.app/Contents/MacOS/terminal-notifier: Permission denied
```

So it means you do not get any notification..
It would be good if you can provide information requested in my first comment to help you fix this.

Thanks

**Comment by templeman** [comment]
Well interestingly the same issue was cropping up on another computer as well. Deleting the settings.json file didn't work in this case (although it had solved the problem on the first machine). I ran

```
ls -lrt
```
as suggested and saw

```
-rw-------  1 templeman  staff    17K Feb 23  2015 workflows.php
-rw-------  1 templeman  staff   619B Feb 23  2015 track_info.ksh
-rw-------  1 templeman  staff   5.3K Feb 23  2015 country_names.json
-rw-------  1 templeman  staff   4.1K Mar 31 12:01 spotify_mini_player_notifications.ksh
-rw-------  1 templeman  staff    11K Apr 11 03:00 debug.php
-rw-------  1 templeman  staff    17K Apr 19 09:14 main.php
-rw-------  1 templeman  staff   280K May 14 01:22 menu.php
-rw-------  1 templeman  staff    52K May 23 02:44 action.php
-rw-------  1 templeman  staff   176K Jun 27 03:02 functions.php
```
Sure enough, it looks like my permissions got hosed somehow. I fixed them and now I can launch tracks as usual. Not sure how my permissions changed all of a sudden, but it seems to have been nothing more in the end.

**Comment by vdesabou** [comment]
So you have another issue on the other computer even when you delete manually settings.json? 

For permissions, that's indeed strange.. Anyway if you fixed them it should be fine now

Cheers

Vincent
