### ISSUE TITLE
Provide a toggle in the settings to disable the integration with terminal-notifier

### ISSUE THREAD

**Issue by Ketouem** [vdesabou/alfred-spotify-mini-player#91]
Would be nice to have a way to deactivate the display of the current track after the initial setup.

**Comment by vdesabou** [comment]
Hi,

You already have a way to diable Now Playing notifications (http://alfred-spotify-mini-player.com/articles/now-playing/):

![screen shot 2015-09-01 a 12 20 43](https://cloud.githubusercontent.com/assets/4061923/9601744/f929adea-50a3-11e5-9941-6ef010cab960.jpg)

Isn't it what you need?

Note: Even if disable this setting, you'll still get notifications when you execute commands (example: Next, add a track to playlist, etc..)

**Comment by Ketouem** [comment]
I was thinking more of a quiet/distraction-free mode that would disable the notification workflow-wide.

**Comment by vdesabou** [comment]
I see..
In that case, I would rather recommend to disable notifications using the standard OS X way, i.e in preferences:

![screen shot 2015-09-01 a 13 54 28](https://cloud.githubusercontent.com/assets/4061923/9603433/10d91072-50b1-11e5-9fa9-7c0d453f7132.jpg)

**Comment by Ketouem** [comment]
Indeed, but in that case it would disable `terminal-notifier` totally and not only with `spotify-mini-player`, wouldn't it ?

**Comment by vdesabou** [comment]
No it should not, the workflow has its own version of terminal-notifier, so it should not impact something else.
Give it a try :smile: !

**Comment by Ketouem** [comment]
I've set the `terminal-notifier` alert style to "None" and I can still see the notification popping up :(

**Comment by vdesabou** [comment]
You should disable ```Spotify Mini Player``` not ```terminal-notifier```, there is a dedicated entry in the preferences list, see my screenshot in previous comment

**Comment by Ketouem** [comment]
I can't see it in the list, must be explaining my troubles ^^

**Comment by vdesabou** [comment]
strange.. Do you get notifications that looks like this, i.e with the Spotify Mini Player logo:

![screen shot 2015-09-01 a 14 56 27](https://cloud.githubusercontent.com/assets/4061923/9604758/aa3f9f76-50b9-11e5-9c19-9c1fdde3c8f0.jpg)

Also you can try to use ```spot_mini_debug ```and choose Browse to Alfred Workflow folder, and then double click on Spotify Mini Player.app
Maybe this will add the app to the list...

**Comment by Ketouem** [comment]
I see the notification that you've attached, but when browsing the to the workflow folder I can't the .app file.

![screen shot 2015-09-01 at 15 09 23](https://cloud.githubusercontent.com/assets/4333817/9605029/7d5506fc-50bb-11e5-895e-153f2a1a680f.png)

**Comment by vdesabou** [comment]
You did not select the correct one, see:

![screen shot 2015-09-01 a 15 11 42](https://cloud.githubusercontent.com/assets/4061923/9605075/d51dc2f2-50bb-11e5-9070-876e637c887b.jpg)

**Comment by Ketouem** [comment]
I've just realised my mistake, silly me ! After clicking on the good app file I got the OS X warning pop-up regarding the application being from an unknown developer. After authorising  the launch of the application, Mini Player finally appeared in the notification preference pane :smile:

**Comment by vdesabou** [comment]
hmm ok, that's what I expected...
So everything should be working now, right?

**Comment by Ketouem** [comment]
Yep, totally. I'll close the issue as it is already handled by OS X itself.
