### ISSUE TITLE
Volume controls not working (does not decrease)

### ISSUE THREAD

**Issue by bjensen** [vdesabou/alfred-spotify-mini-player#92]
Hi guys, 

First off, hands down to you for making such a cool tool :fist: 

When I select the "Volume down" then I get the notification "spotify volume has been decreased by 20%", however the slider in spotify has moved up! Thus increasing the volume and when I use the Volume up option the volume is set to 100%!

What have I done wrong?

The version of the spotify client is 1.0.13.108.gcd94e7db 

I am controlling a speaker through spotify connect, I dont know if that has anything to do with it..

I just installed the app and made a spotify app etc, so everything is the latest version.

**Comment by vdesabou** [comment]
Hi,

That's strange, even when I control a speaker using spotify connect, I do not see this behavior.
What I notice is that the volume slider does not move at all when I use Spotify Connect on my side, but the sound itself is decreased or increased..

Is it reproducible every time on your side ?
What happens if you do not use a spotify connect speaker? Is volume decrease working in that case?

Thanks

**Comment by vdesabou** [comment]
Oh..I upgraded to 1.0.13.108.gcd94e7db and now it looks like everything related to volume is messed up..
Looks like another new AppleScript bug :(

**Comment by bjensen** [comment]
Hi vdesabou, 

Thanks for the response.

Yes, its very weird...I just did some more testing without spotify connect

When I first first started out using volume up then it worked just fine..

seams like volume up sets the sound to about 20%
and volume down sets it to 90%

**Comment by vdesabou** [comment]
This issue has been reported [here](https://community.spotify.com/t5/Help-Desktop-Mac/AppleScript-volume-issue/td-p/1199021), you can Kudo it to have this fixed.

This is a regression, I'm not sure I can do much on my side to work around this..

**Comment by bjensen** [comment]
Well according to the poster of the link a fix would be to set the volume and pause and start the music again? Perhaps it could be so hard one wouldn't notice... Well we could do this till the script is fixed?



Brian JensenNordplaner ApS

www.nordplaner.dk

+45 607 12000

**Comment by vdesabou** [comment]
I've implemented the workaround, but I don't like it as there is a small interruption of the track when we increase/decrease/mute/unmute volume...

Anyway, here is a link of a Beta if you want to try: https://infinit.io/_/hYGMjDg

**Comment by bjensen** [comment]
Im currently using your beta and I hardly notice the interruption and considering the alternative would be to deactivate the volume control since it is broken then I think its a great workaround :-)  (y)

**Comment by vdesabou** [comment]
Version 6.2.3 is live
