### ISSUE TITLE
Add volume percent configuration in Settings menu

### ISSUE THREAD

**Issue by kjarnet** [vdesabou/alfred-spotify-mini-player#94]
Thanks for this awesome workflow! :)
I'm trying to figure out how to increase the volume by 10% instead of the default 20%. I've found that the volume_percent variable used [here](https://github.com/vdesabou/alfred-spotify-mini-player/blob/master/spotify-mini-player/src/action.php#L1088) is fetched from some json [(here)](https://github.com/vdesabou/alfred-spotify-mini-player/blob/master/spotify-mini-player/src/action.php#L48), but I can't figure out where these settings are read from (I've tried looking through the "spot_mini Settings" options).
As I'm guessing these settings are already customisable, I think all that is missing is some documentation on how to do this.

**Comment by vdesabou** [comment]
Hi, 

Thanks :smile:

You can invoke ```spot_mini_debug``` and then choose ```Browse to App Support folder``` and then edit settings.son file with a text editor and change at the end the value "volume_percent":10 by "volume_percent":20 for example and then save the file.

**Comment by kjarnet** [comment]
Wow, awesome response time! :) Thanks again! Is this documented somewhere - did I just miss it?

**Comment by vdesabou** [comment]
No it's not. I was thinking adding this in the Settings menu but I've never done it. i'll use this issue to track this

**Comment by kjarnet** [comment]
Great! That's an even better solution :+1:

**Comment by vdesabou** [comment]
Hey Thanks for the donation :beers: :smile: !!

**Comment by kjarnet** [comment]
You're welcome :) Btw, the donation button was really hard to find :p

**Comment by vdesabou** [comment]
Here is a [link](https://infinit.io/_/3kGdUHt) to Beta version if you want to test

**Comment by kjarnet** [comment]
Thanks a lot! Sadly, I've just lost my macbook(!), so it'll have to wait until I get a new one :(

**Comment by kjarnet** [comment]
Works like a charm :) Got my new macbook yesterday and this was probably the 3rd app I installed - it's just indispensable!

**Comment by vdesabou** [comment]
Thanks! Very appreciated!

Vincent
