### ISSUE TITLE
Play 'Songs' playlist?

### ISSUE THREAD

**Issue by tjurczyk** [vdesabou/alfred-spotify-mini-player#95]
Hi,

I just started using the Spotify mini player, great work! 
My music is organized like this: I have many playlists (genres, artists) and all my music from all these playlists is in My Music, so if I want to play a mix of all my music I play 'Songs' playlist (but it's not a playlist per se, it is just a list of all songs that I added to My Music) in Spotify. Is there a way in SMP to play this playlist?

Thanks!

**Comment by vdesabou** [comment]
Hello,

Thanks!
Unfortunately, the Spotify AppleScript API does not allow to 'play' My Music. The API only allows to play tracks, albums, playlists, but not 'My Music'.
That's technically unfeasible with what Spotify is providing to me.

**Comment by rgehan** [comment]
Hi @vdesabou,

Do you know if it is now possible to play songs from "My Music" now ?
It's something I quite miss and would really like to see in spoti_mini.

Thanks a lot !

**Comment by vdesabou** [comment]
@rgehan Unfortunately, no. Same status as in https://github.com/vdesabou/alfred-spotify-mini-player/issues/95#issuecomment-145815250

**Comment by rgehan** [comment]
Thanks for your answer, hopefully they will update their API to allow this kind of feature

**Comment by vdesabou** [comment]
Yes, however I'm very pessimistic for AppleScript support.

The only workaround I see is to make a copy of "My Music" into a Playlist (the size limit for both is 10000 tracks if I'm correct).
Also, you can use [IFTTT](https://ifttt.com/applets/48460704d-save-a-track-in-spotify-and-add-to-playlist) to add automatically a track you added in "My Music" into a playlist.

**Comment by rgehan** [comment]
I didn't know about IFTTT, it is an awesome tool!

I created an applet to sync all my liked songs to a specific playlist. The only issue is that it doesn't on already added songs.
