### ISSUE TITLE
Can not correct my client ID and secret number

### ISSUE THREAD

**Issue by bixpix** [vdesabou/alfred-spotify-mini-player#96]
Hi Vincent (what a great name !),
I missed the configuration and the result is that my client number is wrong. I tried to reset it with keyword _spot_mini_reset_settings_ and _spot_mini_kill_ but I cannot get the invitation to set my __client ID__ and __secret number__

I tried to delete the workflow, but it didn't change anything.
Thx in advance for your help.

Vincent

**Comment by vdesabou** [comment]
Hello,

Ok, that's weird, can you provide a debug TGZ file for this?

To delete manually the settings.json file, choose 'Browse to App Support folder' when invoking ```spot_mini_debug```

And then delete the settings.json file in Finder

**Comment by bixpix** [comment]
Everything is ok. I corrected my ID and secret directly in the **settings.json** file. 
Just to be curious (because i'm not a developer): is it secure to save these data in a json file?

Thank you for your help and your awesome workflow.
Bye.
Vincent

**Comment by bixpix** [comment]
Btw, are you french ?

**Comment by vdesabou** [comment]
Oui je suis Français :)

With data in the file, a person who has access to it can only have access to your Spotify library, not the password, so he cannot log in with your account at all..!
If your computer got compromised, you can unauthorize the application, to revoke access, this is explained in this page at the bottom, in blue:

http://alfred-spotify-mini-player.com/articles/support/

Vincent

**Comment by bixpix** [comment]
OK, merci !
