### ISSUE TITLE
Search does not handle spaces

### ISSUE THREAD

**Issue by overnine** [vdesabou/alfred-spotify-mini-player#97]
If for example i enter a multi-worded search query like this:

https://www.dropbox.com/s/auk1gt24vnfcckz/Screenshot%202015-10-12%2001.25.10.png?dl=0

the search will only pass the first word to Spotify (Notice the "Showing results for <query>."):

https://www.dropbox.com/s/gfl772xozve2v8n/Screenshot%202015-10-12%2001.27.11.png?dl=0

 compared to what the real query in Spotify (Again notice the "Showing results for <query>."):

https://www.dropbox.com/s/9dvvlry5qhzsdzs/Screenshot%202015-10-12%2001.26.30.png?dl=0

**Comment by vdesabou** [comment]
Thanks for reporting this. I can reproduce, I will fix that soon

Vincent

**Comment by vdesabou** [comment]
Here is a [link](https://infinit.io/_/3ptxicR) to the beta if you want to test
