### ISSUE TITLE
Add possibillity to remove stars/ratings from track names 

### ISSUE THREAD

**Issue by overnine** [vdesabou/alfred-spotify-mini-player#98]
They really do take up a lot of information and add literally 0 information (imo), but instead just reduces the amount of relevant info showed in Alfred:

https://www.dropbox.com/s/4xuxh3eammom6pp/Screenshot%202015-10-12%2001.29.00.png?dl=0

**Comment by overnine** [comment]
I changed my local version of functions.php on line 2855 to the following:
```
displayNotificationWithArtwork(escapeQuery($results[1]) . "\n" . escapeQuery($results[2]), getTrackOrAlbumArtwork($w, $results[4], true), escapeQuery($results[0]));
```

**Comment by vdesabou** [comment]
Link to beta release: https://infinit.io/_/k6AhjMC
