### ISSUE TITLE
Add autoplay when starting radio

### ISSUE THREAD

**Issue by overnine** [vdesabou/alfred-spotify-mini-player#99]
I was thinking it might be nice to have a modifier to start the spotify radio, both for playlists but also artists etc. For example the fn or ctrl modifier might be a good candidate.

**Comment by vdesabou** [comment]
Hi, 

Thanks for the suggestion!
I like the idea to autoplay the playlist radio when we create it. I'll add it in next version 6.2.4.
However, I don't want to touch existing modifiers and there are only 5 possible modifiers allowed by Alfred App right now.

If you want to quickly create an artist or song radio for current song, you can stil use ```artist_radio```or ```song_radio```commands, or set an hotkey, or use Alfred Remote.

**Comment by vdesabou** [comment]
I've opened https://github.com/vdesabou/alfred-spotify-mini-player/issues/102 to track your query to change modifier keys for other actions.
